"""
Extended food library batch 2 — food_311 onward. All values per 100g.
"""
from typing import Dict, List

EXTENDED_FOODS_2: List[Dict] = [

    # ── MORE BEEF CUTS ────────────────────────────────────────────────────────
    {"food_id":"food_311","name_he":"בריסקט","name_en":"Beef Brisket",
     "category":"protein","calories_kcal":271.0,"protein_g":26.0,"carbs_g":0.0,"fat_g":18.0,
     "default_serving_g":200.0,"aliases_he":["חזה בקר"],"aliases_en":["slow-cooked brisket","smoked brisket"],"source":"curated"},
    {"food_id":"food_312","name_he":"שק עורף","name_en":"Chuck Roast",
     "category":"protein","calories_kcal":263.0,"protein_g":26.0,"carbs_g":0.0,"fat_g":17.0,
     "default_serving_g":200.0,"aliases_he":["צלי בקר","רוסטביף"],"aliases_en":["pot roast","beef roast","slow roast beef"],"source":"curated"},
    {"food_id":"food_313","name_he":"פלנק סטייק","name_en":"Flank Steak",
     "category":"protein","calories_kcal":192.0,"protein_g":28.0,"carbs_g":0.0,"fat_g":8.0,
     "default_serving_g":150.0,"aliases_he":["סטייק מנגל"],"aliases_en":["skirt steak","bavette"],"source":"curated"},
    {"food_id":"food_314","name_he":"לשון בקר","name_en":"Beef Tongue",
     "category":"protein","calories_kcal":272.0,"protein_g":20.0,"carbs_g":0.3,"fat_g":21.0,
     "default_serving_g":100.0,"aliases_he":["לשון"],"aliases_en":["ox tongue","pickled tongue"],"source":"curated"},

    # ── LAMB ──────────────────────────────────────────────────────────────────
    {"food_id":"food_315","name_he":"כתף כבש","name_en":"Lamb Shoulder",
     "category":"protein","calories_kcal":258.0,"protein_g":23.0,"carbs_g":0.0,"fat_g":18.0,
     "default_serving_g":150.0,"aliases_he":["כבש כתף","בשר כבש"],"aliases_en":["braised lamb","roast lamb shoulder"],"source":"curated"},
    {"food_id":"food_316","name_he":"צלעות כבש","name_en":"Lamb Chops",
     "category":"protein","calories_kcal":294.0,"protein_g":25.0,"carbs_g":0.0,"fat_g":21.0,
     "default_unit":"unit","default_serving_g":120.0,"aliases_he":["קוטלטות כבש"],"aliases_en":["grilled lamb chops","rack of lamb"],"source":"curated"},
    {"food_id":"food_317","name_he":"בשר כבש טחון","name_en":"Ground Lamb",
     "category":"protein","calories_kcal":282.0,"protein_g":22.0,"carbs_g":0.0,"fat_g":21.0,
     "default_serving_g":100.0,"aliases_he":["כבש טחון","קציצת כבש"],"aliases_en":["minced lamb","lamb mince"],"source":"curated"},

    # ── VEAL ──────────────────────────────────────────────────────────────────
    {"food_id":"food_318","name_he":"עגל","name_en":"Veal",
     "category":"protein","calories_kcal":172.0,"protein_g":26.0,"carbs_g":0.0,"fat_g":7.0,
     "default_serving_g":150.0,"aliases_he":["עגל צלוי","שניצל עגל"],"aliases_en":["veal chop","veal cutlet","wiener schnitzel"],"source":"curated"},

    # ── MORE POULTRY ──────────────────────────────────────────────────────────
    {"food_id":"food_319","name_he":"פסטרמה הודו","name_en":"Turkey Pastrami",
     "category":"protein","calories_kcal":115.0,"protein_g":20.0,"carbs_g":2.0,"fat_g":3.0,
     "default_unit":"slice","default_serving_g":30.0,"aliases_he":["פסטרמה","הודו פסטרמה"],"aliases_en":["turkey breast deli","smoked turkey"],"source":"curated"},
    {"food_id":"food_320","name_he":"עוף שלם צלוי","name_en":"Roast Chicken",
     "category":"protein","calories_kcal":215.0,"protein_g":27.0,"carbs_g":0.0,"fat_g":12.0,
     "default_serving_g":150.0,"aliases_he":["עוף צלוי","עוף בתנור"],"aliases_en":["whole roasted chicken","rotisserie chicken"],"source":"curated"},
    {"food_id":"food_321","name_he":"אווז","name_en":"Goose",
     "category":"protein","calories_kcal":305.0,"protein_g":26.0,"carbs_g":0.0,"fat_g":22.0,
     "default_serving_g":150.0,"aliases_he":["חזה אווז"],"aliases_en":["roast goose","goose breast"],"source":"curated"},

    # ── MORE SEAFOOD ──────────────────────────────────────────────────────────
    {"food_id":"food_322","name_he":"אוקטופוס","name_en":"Octopus",
     "category":"protein","calories_kcal":82.0,"protein_g":15.0,"carbs_g":2.2,"fat_g":1.0,
     "default_serving_g":100.0,"aliases_he":["תמנון","אוקטופוס מבושל"],"aliases_en":["cooked octopus","grilled octopus"],"source":"curated"},
    {"food_id":"food_323","name_he":"מולים","name_en":"Mussels",
     "category":"protein","calories_kcal":172.0,"protein_g":24.0,"carbs_g":7.0,"fat_g":4.5,
     "default_serving_g":100.0,"aliases_he":["תמנן ים"],"aliases_en":["steamed mussels","blue mussels"],"source":"curated"},
    {"food_id":"food_324","name_he":"צדפות","name_en":"Oysters",
     "category":"protein","calories_kcal":68.0,"protein_g":7.0,"carbs_g":3.9,"fat_g":2.5,
     "default_unit":"unit","default_serving_g":50.0,"aliases_he":["אוסטריות"],"aliases_en":["raw oysters","pacific oysters"],"source":"curated"},
    {"food_id":"food_325","name_he":"קלמרי מטוגן","name_en":"Fried Calamari",
     "category":"protein","calories_kcal":175.0,"protein_g":18.0,"carbs_g":8.0,"fat_g":7.0,
     "default_serving_g":100.0,"aliases_he":["קלאמארי"],"aliases_en":["battered squid","calamari rings"],"source":"curated"},
    {"food_id":"food_326","name_he":"אצות ואקמה","name_en":"Wakame Seaweed",
     "category":"vegetable","calories_kcal":45.0,"protein_g":3.0,"carbs_g":9.1,"fat_g":0.6,
     "fiber_g":0.5,"default_serving_g":50.0,"aliases_he":["אצות ים","אצות"],"aliases_en":["dried seaweed salad","sea vegetables"],"source":"curated"},

    # ── EGGS (varieties) ──────────────────────────────────────────────────────
    {"food_id":"food_327","name_he":"חביתה","name_en":"Omelette",
     "category":"protein","calories_kcal":154.0,"protein_g":10.0,"carbs_g":0.4,"fat_g":12.0,
     "default_unit":"unit","default_serving_g":120.0,"aliases_he":["אומלט","ביצת חביתה"],"aliases_en":["egg omelet","french omelette"],"source":"curated"},
    {"food_id":"food_328","name_he":"ביצים מקושקשות","name_en":"Scrambled Eggs",
     "category":"protein","calories_kcal":149.0,"protein_g":10.0,"carbs_g":1.6,"fat_g":11.0,
     "default_serving_g":100.0,"aliases_he":["ביצים טרופות","שקשוקה ביצים"],"aliases_en":["scrambled egg","soft scramble"],"source":"curated"},
    {"food_id":"food_329","name_he":"ביצה עלומה","name_en":"Poached Egg",
     "category":"protein","calories_kcal":143.0,"protein_g":12.6,"carbs_g":0.7,"fat_g":9.5,
     "default_unit":"unit","default_serving_g":50.0,"aliases_he":["ביצה מוברשת"],"aliases_en":["soft poached egg","eggs benedict"],"source":"curated"},

    # ── ADDITIONAL DAIRY ──────────────────────────────────────────────────────
    {"food_id":"food_330","name_he":"יוגורט רגיל","name_en":"Plain Yogurt",
     "category":"dairy","calories_kcal":61.0,"protein_g":3.5,"carbs_g":4.7,"fat_g":3.3,
     "default_serving_g":150.0,"aliases_he":["יוגורט טבעי","יוגורט רגיל"],"aliases_en":["whole milk yogurt","natural yogurt","bio yogurt"],"source":"curated"},
    {"food_id":"food_331","name_he":"גלידת שוקולד","name_en":"Chocolate Ice Cream",
     "category":"dairy","calories_kcal":216.0,"protein_g":3.8,"carbs_g":28.0,"fat_g":11.0,
     "default_serving_g":100.0,"aliases_he":["גלידה שוקולד"],"aliases_en":["chocolate gelato","dark chocolate ice cream"],"source":"curated"},
    {"food_id":"food_332","name_he":"פרוזן יוגורט","name_en":"Frozen Yogurt",
     "category":"dairy","calories_kcal":127.0,"protein_g":3.0,"carbs_g":22.0,"fat_g":3.2,
     "default_serving_g":100.0,"aliases_he":["פרויו","יוגורט קפוא"],"aliases_en":["froyo","low fat frozen yogurt"],"source":"curated"},
    {"food_id":"food_333","name_he":"שוקו חם","name_en":"Hot Chocolate",
     "category":"beverage","calories_kcal":100.0,"protein_g":3.5,"carbs_g":17.0,"fat_g":2.5,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["קקאו חם","שוקולד חם"],"aliases_en":["hot cocoa","drinking chocolate"],"source":"curated"},
    {"food_id":"food_334","name_he":"פנה קוטה","name_en":"Panna Cotta",
     "category":"dairy","calories_kcal":198.0,"protein_g":3.0,"carbs_g":21.0,"fat_g":12.0,
     "default_serving_g":120.0,"aliases_he":["פאנה קוטה"],"aliases_en":["vanilla panna cotta","italian cream dessert"],"source":"curated"},

    # ── GRAIN & BREAD VARIETIES ───────────────────────────────────────────────
    {"food_id":"food_335","name_he":"אורז פרא","name_en":"Wild Rice",
     "category":"grain","calories_kcal":101.0,"protein_g":4.0,"carbs_g":21.0,"fat_g":0.3,
     "fiber_g":1.8,"default_serving_g":150.0,"aliases_he":["אורז בר"],"aliases_en":["wild rice blend","black rice"],"source":"curated"},
    {"food_id":"food_336","name_he":"לחם שיפון-כוסמין","name_en":"Spelt Bread",
     "category":"grain","calories_kcal":252.0,"protein_g":10.0,"carbs_g":46.0,"fat_g":3.0,
     "fiber_g":6.0,"default_unit":"slice","default_serving_g":35.0,"aliases_he":["לחם כוסמין","לחם כוסמת"],"aliases_en":["spelt loaf","ancient grain bread"],"source":"curated"},
    {"food_id":"food_337","name_he":"גריסים","name_en":"Grits",
     "category":"grain","calories_kcal":71.0,"protein_g":1.7,"carbs_g":15.0,"fat_g":0.5,
     "fiber_g":0.9,"default_serving_g":200.0,"aliases_he":["גרוסים","דייסת תירס"],"aliases_en":["cooked grits","stone-ground grits"],"source":"curated"},
    {"food_id":"food_338","name_he":"אנצ'ילדה","name_en":"Enchilada Tortilla",
     "category":"grain","calories_kcal":168.0,"protein_g":5.0,"carbs_g":27.0,"fat_g":5.0,
     "fiber_g":2.5,"default_unit":"unit","default_serving_g":60.0,"aliases_he":["אנצ'ילדה","טורטייה בנה"],"aliases_en":["corn enchilada","rolled tortilla"],"source":"curated"},
    {"food_id":"food_339","name_he":"אטריות סובה","name_en":"Soba Noodles",
     "category":"grain","calories_kcal":99.0,"protein_g":5.0,"carbs_g":21.0,"fat_g":0.1,
     "fiber_g":0.0,"default_serving_g":160.0,"aliases_he":["סובה","אטריות כוסמת"],"aliases_en":["buckwheat noodles","japanese soba"],"source":"curated"},
    {"food_id":"food_340","name_he":"אטריות אודון","name_en":"Udon Noodles",
     "category":"grain","calories_kcal":132.0,"protein_g":3.5,"carbs_g":27.0,"fat_g":0.6,
     "fiber_g":0.5,"default_serving_g":180.0,"aliases_he":["אודון","אטריות עבות"],"aliases_en":["thick japanese noodles","udon soup noodles"],"source":"curated"},
    {"food_id":"food_341","name_he":"רוטי","name_en":"Roti",
     "category":"grain","calories_kcal":297.0,"protein_g":9.8,"carbs_g":55.0,"fat_g":4.7,
     "fiber_g":2.3,"default_unit":"unit","default_serving_g":40.0,"aliases_he":["לחם הודי שטוח","צ'פאטי"],"aliases_en":["chapati","flatbread roti"],"source":"curated"},
    {"food_id":"food_342","name_he":"קרפ","name_en":"Crêpe",
     "category":"grain","calories_kcal":200.0,"protein_g":6.0,"carbs_g":26.0,"fat_g":8.0,
     "default_unit":"unit","default_serving_g":50.0,"aliases_he":["קרפ דק","קרפ צרפתי"],"aliases_en":["french crepe","thin pancake"],"source":"curated"},
    {"food_id":"food_343","name_he":"פופאדום","name_en":"Papadum",
     "category":"grain","calories_kcal":350.0,"protein_g":22.0,"carbs_g":56.0,"fat_g":2.0,
     "fiber_g":13.0,"default_unit":"unit","default_serving_g":10.0,"aliases_he":["פאפאדום","לחמנייה הודית"],"aliases_en":["poppadom","indian crispy bread"],"source":"curated"},
    {"food_id":"food_344","name_he":"לחם שאור כוסמין","name_en":"Einkorn Sourdough",
     "category":"grain","calories_kcal":258.0,"protein_g":9.0,"carbs_g":50.0,"fat_g":2.0,
     "fiber_g":4.0,"default_unit":"slice","default_serving_g":40.0,"aliases_he":["לחם כוסמין"],"aliases_en":["heritage grain bread","ancient wheat bread"],"source":"curated"},
    {"food_id":"food_345","name_he":"ביסקוויט","name_en":"Digestive Biscuit",
     "category":"grain","calories_kcal":471.0,"protein_g":7.0,"carbs_g":63.0,"fat_g":21.0,
     "fiber_g":3.5,"default_unit":"unit","default_serving_g":15.0,"aliases_he":["ביסקוויט חיטה","עוגיית חיטה"],"aliases_en":["graham cracker","digestive"],"source":"curated"},

    # ── MORE VEGETABLES ───────────────────────────────────────────────────────
    {"food_id":"food_346","name_he":"פלפל חריף אדום","name_en":"Red Chili Pepper",
     "category":"vegetable","calories_kcal":40.0,"protein_g":1.9,"carbs_g":8.8,"fat_g":0.4,
     "fiber_g":1.5,"default_unit":"unit","default_serving_g":45.0,"aliases_he":["פלפל חריף","צ'ילי"],"aliases_en":["hot chili","red chili","dried chili"],"source":"curated"},
    {"food_id":"food_347","name_he":"קצות אספרגוס","name_en":"Asparagus Tips",
     "category":"vegetable","calories_kcal":20.0,"protein_g":2.2,"carbs_g":3.9,"fat_g":0.1,
     "fiber_g":2.1,"default_serving_g":100.0,"aliases_he":["אספרגוס חרוך"],"aliases_en":["grilled asparagus","roasted asparagus"],"source":"curated"},
    {"food_id":"food_348","name_he":"עלי מנגולד","name_en":"Collard Greens",
     "category":"vegetable","calories_kcal":32.0,"protein_g":3.0,"carbs_g":5.7,"fat_g":0.6,
     "fiber_g":4.0,"default_serving_g":100.0,"aliases_he":["ירוק עלים","עלים ירוקים"],"aliases_en":["collards","southern greens"],"source":"curated"},
    {"food_id":"food_349","name_he":"פול סויה בשל","name_en":"Cooked Soybeans",
     "category":"legume","calories_kcal":173.0,"protein_g":17.0,"carbs_g":10.0,"fat_g":9.0,
     "fiber_g":6.0,"default_serving_g":150.0,"aliases_he":["גרעיני סויה","סויה מבושלת"],"aliases_en":["whole soybeans","boiled soy"],"source":"curated"},
    {"food_id":"food_350","name_he":"שעועית מנגד","name_en":"Mung Beans",
     "category":"legume","calories_kcal":105.0,"protein_g":7.0,"carbs_g":19.0,"fat_g":0.4,
     "fiber_g":7.6,"default_serving_g":150.0,"aliases_he":["שעועית ירוקה קטנה"],"aliases_en":["cooked mung beans","green mung"],"source":"curated"},
    {"food_id":"food_351","name_he":"שעועית פינטו","name_en":"Pinto Beans",
     "category":"legume","calories_kcal":143.0,"protein_g":9.0,"carbs_g":27.0,"fat_g":0.7,
     "fiber_g":9.0,"default_serving_g":150.0,"aliases_he":["שעועית מנוקדת"],"aliases_en":["cooked pinto beans","refried pinto"],"source":"curated"},
    {"food_id":"food_352","name_he":"עדשים שחורות","name_en":"Black Lentils",
     "category":"legume","calories_kcal":116.0,"protein_g":9.0,"carbs_g":20.0,"fat_g":0.4,
     "fiber_g":8.0,"default_serving_g":150.0,"aliases_he":["עדשים שחורות קטנות","בלוגה"],"aliases_en":["beluga lentils","black beluga"],"source":"curated"},
    {"food_id":"food_353","name_he":"ירקות שורש מרוסקים","name_en":"Mashed Root Vegetables",
     "category":"vegetable","calories_kcal":89.0,"protein_g":1.8,"carbs_g":20.0,"fat_g":0.5,
     "fiber_g":2.5,"default_serving_g":200.0,"aliases_he":["פירה ירקות","פירה"],"aliases_en":["mashed parsnip","vegetable mash"],"source":"curated"},
    {"food_id":"food_354","name_he":"תפוח אדמה מרוסק","name_en":"Mashed Potatoes",
     "category":"vegetable","calories_kcal":113.0,"protein_g":2.0,"carbs_g":18.0,"fat_g":4.5,
     "fiber_g":1.6,"default_serving_g":200.0,"aliases_he":["פירה","פורי","פירה חמאה"],"aliases_en":["mashed potato","buttery mash"],"source":"curated"},
    {"food_id":"food_355","name_he":"תפוח אדמה אפוי","name_en":"Baked Potato",
     "category":"vegetable","calories_kcal":93.0,"protein_g":2.5,"carbs_g":21.0,"fat_g":0.1,
     "fiber_g":2.2,"default_unit":"unit","default_serving_g":200.0,"aliases_he":["תפוח אדמה מהתנור"],"aliases_en":["jacket potato","loaded baked potato"],"source":"curated"},
    {"food_id":"food_356","name_he":"צ'יפס תפוח אדמה בתנור","name_en":"Baked Potato Wedges",
     "category":"vegetable","calories_kcal":150.0,"protein_g":2.5,"carbs_g":26.0,"fat_g":4.0,
     "fiber_g":2.5,"default_serving_g":150.0,"aliases_he":["פוטייטו וודג'ס","וודגס"],"aliases_en":["potato wedges","oven fries"],"source":"curated"},
    {"food_id":"food_357","name_he":"כרוב אדום","name_en":"Red Cabbage",
     "category":"vegetable","calories_kcal":31.0,"protein_g":1.4,"carbs_g":7.4,"fat_g":0.2,
     "fiber_g":2.1,"default_serving_g":100.0,"aliases_he":["כרוב סגול"],"aliases_en":["purple cabbage","red coleslaw"],"source":"curated"},
    {"food_id":"food_358","name_he":"קישוא שרוף","name_en":"Grilled Zucchini",
     "category":"vegetable","calories_kcal":17.0,"protein_g":1.2,"carbs_g":3.1,"fat_g":0.3,
     "fiber_g":1.0,"default_serving_g":150.0,"aliases_he":["זוקיני שרוף"],"aliases_en":["charred zucchini","grilled courgette"],"source":"curated"},
    {"food_id":"food_359","name_he":"ברוקולי מוקפץ","name_en":"Stir-Fried Broccoli",
     "category":"vegetable","calories_kcal":37.0,"protein_g":2.8,"carbs_g":7.0,"fat_g":0.7,
     "fiber_g":2.5,"default_serving_g":150.0,"aliases_he":["ברוקולי מטוגן"],"aliases_en":["sauteed broccoli","wok broccoli"],"source":"curated"},
    {"food_id":"food_360","name_he":"דלעת מקורמלת","name_en":"Roasted Pumpkin",
     "category":"vegetable","calories_kcal":30.0,"protein_g":1.0,"carbs_g":7.5,"fat_g":0.1,
     "fiber_g":0.5,"default_serving_g":150.0,"aliases_he":["דלעת צלויה","דלעת אפויה"],"aliases_en":["roasted squash","baked pumpkin"],"source":"curated"},
    {"food_id":"food_361","name_he":"פסל מקורמל","name_en":"Caramelized Onions",
     "category":"vegetable","calories_kcal":56.0,"protein_g":0.9,"carbs_g":13.0,"fat_g":0.5,
     "fiber_g":1.2,"default_serving_g":60.0,"aliases_he":["בצל מקורמל","בצל מוכן"],"aliases_en":["sauteed onion","caramelised onion"],"source":"curated"},

    # ── MORE FRUITS ───────────────────────────────────────────────────────────
    {"food_id":"food_362","name_he":"אפרסמון","name_en":"Persimmon",
     "category":"fruit","calories_kcal":127.0,"protein_g":0.8,"carbs_g":34.0,"fat_g":0.4,
     "fiber_g":3.6,"default_unit":"unit","default_serving_g":150.0,"aliases_he":["שרון","שרון פרי"],"aliases_en":["sharon fruit","fuyu persimmon"],"source":"curated"},
    {"food_id":"food_363","name_he":"ג'ק פרוט","name_en":"Jackfruit",
     "category":"fruit","calories_kcal":95.0,"protein_g":1.7,"carbs_g":23.0,"fat_g":0.6,
     "fiber_g":1.5,"default_serving_g":100.0,"aliases_he":["פרי ג'ק"],"aliases_en":["canned jackfruit","green jackfruit"],"source":"curated"},
    {"food_id":"food_364","name_he":"גויאבה","name_en":"Guava",
     "category":"fruit","calories_kcal":68.0,"protein_g":2.6,"carbs_g":14.0,"fat_g":1.0,
     "fiber_g":5.4,"default_unit":"unit","default_serving_g":100.0,"aliases_he":["גויאווה"],"aliases_en":["guava fruit","pink guava"],"source":"curated"},
    {"food_id":"food_365","name_he":"סברס","name_en":"Prickly Pear",
     "category":"fruit","calories_kcal":41.0,"protein_g":0.7,"carbs_g":10.0,"fat_g":0.5,
     "fiber_g":3.6,"default_unit":"unit","default_serving_g":100.0,"aliases_he":["תאנת בר","תאנת ברברי"],"aliases_en":["cactus pear","sabra"],"source":"curated"},
    {"food_id":"food_366","name_he":"דרגון פרוט","name_en":"Dragon Fruit",
     "category":"fruit","calories_kcal":60.0,"protein_g":1.2,"carbs_g":13.0,"fat_g":0.0,
     "fiber_g":3.0,"default_unit":"unit","default_serving_g":200.0,"aliases_he":["פיטייה","פירות דרקון"],"aliases_en":["pitaya","dragonfruit"],"source":"curated"},
    {"food_id":"food_367","name_he":"ענבים ירוקים","name_en":"Green Grapes",
     "category":"fruit","calories_kcal":67.0,"protein_g":0.6,"carbs_g":17.0,"fat_g":0.4,
     "fiber_g":0.9,"sugar_g":16.3,"default_serving_g":100.0,"aliases_he":["ענבים לבנים","ענבי שרדוניי"],"aliases_en":["white grapes","seedless grapes","muscatel"],"source":"curated"},
    {"food_id":"food_368","name_he":"ענבים אדומים","name_en":"Red Grapes",
     "category":"fruit","calories_kcal":70.0,"protein_g":0.7,"carbs_g":18.0,"fat_g":0.2,
     "fiber_g":0.9,"sugar_g":15.5,"default_serving_g":100.0,"aliases_he":["ענבים שחורים"],"aliases_en":["black grapes","red seedless grapes"],"source":"curated"},
    {"food_id":"food_369","name_he":"קלמנטינה","name_en":"Clementine",
     "category":"fruit","calories_kcal":47.0,"protein_g":0.9,"carbs_g":12.0,"fat_g":0.2,
     "fiber_g":1.7,"default_unit":"unit","default_serving_g":80.0,"aliases_he":["מנדרינה","קלמנטינה"],"aliases_en":["mandarin","tangerine","satsuma"],"source":"curated"},
    {"food_id":"food_370","name_he":"מיץ מנגו","name_en":"Mango Juice",
     "category":"beverage","calories_kcal":60.0,"protein_g":0.4,"carbs_g":15.0,"fat_g":0.1,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["מיץ אמבה"],"aliases_en":["mango nectar","tropical juice"],"source":"curated"},

    # ── INTERNATIONAL CUISINE ─────────────────────────────────────────────────
    {"food_id":"food_371","name_he":"קארי ירוק","name_en":"Thai Green Curry",
     "category":"other","calories_kcal":165.0,"protein_g":7.0,"carbs_g":14.0,"fat_g":9.0,
     "fiber_g":1.8,"default_serving_g":300.0,"aliases_he":["קארי ירוק תאילנדי"],"aliases_en":["green curry chicken","thai curry"],"source":"curated"},
    {"food_id":"food_372","name_he":"ביביםבאפ","name_en":"Bibimbap",
     "category":"other","calories_kcal":148.0,"protein_g":7.0,"carbs_g":24.0,"fat_g":2.6,
     "fiber_g":2.0,"default_serving_g":350.0,"aliases_he":["אורז קוריאני","ביביאמבאפ"],"aliases_en":["korean rice bowl","mixed rice bowl"],"source":"curated"},
    {"food_id":"food_373","name_he":"פו","name_en":"Pho",
     "category":"other","calories_kcal":45.0,"protein_g":4.0,"carbs_g":6.0,"fat_g":1.0,
     "fiber_g":0.5,"default_serving_g":500.0,"aliases_he":["מרק וייטנאמי"],"aliases_en":["vietnamese pho","beef pho"],"source":"curated"},
    {"food_id":"food_374","name_he":"טומ יאם","name_en":"Tom Yum Soup",
     "category":"other","calories_kcal":35.0,"protein_g":2.5,"carbs_g":3.5,"fat_g":1.2,
     "fiber_g":0.5,"default_serving_g":350.0,"aliases_he":["מרק תאילנדי"],"aliases_en":["thai soup","lemongrass shrimp soup"],"source":"curated"},
    {"food_id":"food_375","name_he":"פאלאק פאניר","name_en":"Palak Paneer",
     "category":"other","calories_kcal":173.0,"protein_g":8.0,"carbs_g":8.0,"fat_g":12.0,
     "fiber_g":2.5,"default_serving_g":250.0,"aliases_he":["תרד עם גבינה הודית"],"aliases_en":["saag paneer","indian spinach curry"],"source":"curated"},
    {"food_id":"food_376","name_he":"חומוס מסורתי","name_en":"Traditional Hummus",
     "category":"other","calories_kcal":177.0,"protein_g":8.0,"carbs_g":14.0,"fat_g":10.0,
     "fiber_g":6.0,"default_serving_g":100.0,"aliases_he":["חומוס מסעדה","חומוס עם שמן"],"aliases_en":["fresh hummus","hummus with olive oil"],"source":"curated"},
    {"food_id":"food_377","name_he":"בנש","name_en":"Borscht",
     "category":"other","calories_kcal":37.0,"protein_g":1.6,"carbs_g":7.0,"fat_g":0.5,
     "fiber_g":1.5,"default_serving_g":300.0,"aliases_he":["מרק סלק","בורשט"],"aliases_en":["beet soup","ukrainian borscht"],"source":"curated"},
    {"food_id":"food_378","name_he":"גולאש","name_en":"Goulash",
     "category":"other","calories_kcal":138.0,"protein_g":11.0,"carbs_g":10.0,"fat_g":6.0,
     "fiber_g":1.5,"default_serving_g":300.0,"aliases_he":["גולש","תבשיל בקר"],"aliases_en":["hungarian goulash","beef stew"],"source":"curated"},
    {"food_id":"food_379","name_he":"ברבקיו ריבס","name_en":"BBQ Pork Ribs",
     "category":"other","calories_kcal":295.0,"protein_g":22.0,"carbs_g":10.0,"fat_g":19.0,
     "default_serving_g":200.0,"aliases_he":["ריבס ברביקיו","צלעות מעושנות"],"aliases_en":["smoked ribs","slow-cooked pork ribs"],"source":"curated"},
    {"food_id":"food_380","name_he":"מוצקה","name_en":"Moussaka",
     "category":"other","calories_kcal":185.0,"protein_g":10.0,"carbs_g":10.0,"fat_g":12.0,
     "fiber_g":2.0,"default_serving_g":250.0,"aliases_he":["מוסקה","מוסקה חציל"],"aliases_en":["greek moussaka","eggplant casserole"],"source":"curated"},
    {"food_id":"food_381","name_he":"פאייה","name_en":"Paella",
     "category":"other","calories_kcal":190.0,"protein_g":11.0,"carbs_g":25.0,"fat_g":5.5,
     "fiber_g":1.5,"default_serving_g":300.0,"aliases_he":["פאייה ים תיכונית"],"aliases_en":["seafood paella","valencian paella"],"source":"curated"},
    {"food_id":"food_382","name_he":"שקשוקה","name_en":"Shakshuka",
     "category":"other","calories_kcal":152.0,"protein_g":8.0,"carbs_g":9.0,"fat_g":9.0,
     "fiber_g":2.0,"default_serving_g":250.0,"aliases_he":["ביצים ברוטב עגבניות"],"aliases_en":["eggs in tomato sauce","middle eastern shakshuka"],"source":"curated"},
    {"food_id":"food_383","name_he":"פיתה ממולאת","name_en":"Stuffed Pita",
     "category":"other","calories_kcal":220.0,"protein_g":9.0,"carbs_g":30.0,"fat_g":8.0,
     "fiber_g":2.5,"default_unit":"unit","default_serving_g":180.0,"aliases_he":["סנדוויץ' פיתה"],"aliases_en":["pita sandwich","pita wrap"],"source":"curated"},
    {"food_id":"food_384","name_he":"מנסף","name_en":"Mansaf",
     "category":"other","calories_kcal":250.0,"protein_g":12.0,"carbs_g":25.0,"fat_g":11.0,
     "fiber_g":1.0,"default_serving_g":300.0,"aliases_he":["מנסף ירדני","תבשיל כבש"],"aliases_en":["jordanian lamb dish","lamb with rice"],"source":"curated"},
    {"food_id":"food_385","name_he":"מג'דרה","name_en":"Mujaddara",
     "category":"other","calories_kcal":134.0,"protein_g":5.0,"carbs_g":24.0,"fat_g":3.0,
     "fiber_g":4.5,"default_serving_g":200.0,"aliases_he":["מג'דרה","עדשים עם אורז"],"aliases_en":["lentil and rice pilaf","levantine dish"],"source":"curated"},

    # ── BREAKFAST FOODS ───────────────────────────────────────────────────────
    {"food_id":"food_386","name_he":"פרנץ' טוסט","name_en":"French Toast",
     "category":"other","calories_kcal":229.0,"protein_g":9.6,"carbs_g":29.0,"fat_g":9.0,
     "default_unit":"slice","default_serving_g":65.0,"aliases_he":["לחם טבול בביצה","טוסט צרפתי"],"aliases_en":["eggy bread","pain perdu"],"source":"curated"},
    {"food_id":"food_387","name_he":"אבוקדו על טוסט","name_en":"Avocado Toast",
     "category":"other","calories_kcal":195.0,"protein_g":4.5,"carbs_g":17.0,"fat_g":12.0,
     "fiber_g":5.0,"default_serving_g":150.0,"aliases_he":["טוסט עם אבוקדו"],"aliases_en":["smashed avocado toast","avo toast"],"source":"curated"},
    {"food_id":"food_388","name_he":"ביצה עם בייקון","name_en":"Eggs and Bacon",
     "category":"other","calories_kcal":230.0,"protein_g":18.0,"carbs_g":0.5,"fat_g":17.5,
     "default_serving_g":150.0,"aliases_he":["ארוחת בוקר אנגלית"],"aliases_en":["full english breakfast","eggs bacon"],"source":"curated"},
    {"food_id":"food_389","name_he":"יוגורט עם פירות","name_en":"Yogurt Parfait",
     "category":"other","calories_kcal":107.0,"protein_g":5.0,"carbs_g":18.0,"fat_g":2.0,
     "fiber_g":1.5,"default_serving_g":200.0,"aliases_he":["פארפה יוגורט","יוגורט עם גרנולה"],"aliases_en":["greek yogurt parfait","yogurt with berries"],"source":"curated"},
    {"food_id":"food_390","name_he":"חביתת ירקות","name_en":"Vegetable Omelette",
     "category":"other","calories_kcal":131.0,"protein_g":9.0,"carbs_g":5.0,"fat_g":9.0,
     "fiber_g":1.5,"default_serving_g":150.0,"aliases_he":["חביתה עם ירקות","אומלט ירקות"],"aliases_en":["veggie omelet","spanish omelette"],"source":"curated"},
    {"food_id":"food_391","name_he":"שייק אחרי אימון","name_en":"Post-Workout Shake",
     "category":"beverage","calories_kcal":180.0,"protein_g":25.0,"carbs_g":20.0,"fat_g":2.0,
     "default_unit":"cup","default_serving_g":350.0,"aliases_he":["שייק בנאנה פרוטאין","שייק מנצחים"],"aliases_en":["recovery shake","mass gainer","protein smoothie"],"source":"curated"},
    {"food_id":"food_392","name_he":"גאצ'פאצ'ו","name_en":"Gazpacho",
     "category":"other","calories_kcal":35.0,"protein_g":1.0,"carbs_g":6.5,"fat_g":1.5,
     "fiber_g":1.5,"default_serving_g":300.0,"aliases_he":["מרק עגבניות קר","גספאצ'ו"],"aliases_en":["cold tomato soup","spanish gazpacho"],"source":"curated"},

    # ── BEVERAGES (more) ──────────────────────────────────────────────────────
    {"food_id":"food_393","name_he":"יין לבן","name_en":"White Wine",
     "category":"beverage","calories_kcal":82.0,"protein_g":0.1,"carbs_g":2.6,"fat_g":0.0,
     "default_unit":"cup","default_serving_g":150.0,"aliases_he":["יין לבן יבש","שרדוניי"],"aliases_en":["dry white wine","sauvignon blanc"],"source":"curated"},
    {"food_id":"food_394","name_he":"ספרסו כפול","name_en":"Double Espresso",
     "category":"beverage","calories_kcal":6.0,"protein_g":0.4,"carbs_g":0.0,"fat_g":0.0,
     "default_unit":"cup","default_serving_g":60.0,"aliases_he":["אספרסו כפול","ריסטרטו"],"aliases_en":["double shot espresso","ristretto"],"source":"curated"},
    {"food_id":"food_395","name_he":"מיץ ירוק","name_en":"Green Juice",
     "category":"beverage","calories_kcal":45.0,"protein_g":2.0,"carbs_g":9.0,"fat_g":0.3,
     "fiber_g":1.5,"default_unit":"cup","default_serving_g":240.0,"aliases_he":["מיץ תרד תפוח","שייק ירוק"],"aliases_en":["spinach apple juice","kale juice","green smoothie"],"source":"curated"},
    {"food_id":"food_396","name_he":"מיץ סלק","name_en":"Beet Juice",
     "category":"beverage","calories_kcal":45.0,"protein_g":1.6,"carbs_g":10.0,"fat_g":0.2,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["מיץ סלק טרי"],"aliases_en":["beetroot juice","beet shot"],"source":"curated"},
    {"food_id":"food_397","name_he":"משקה אנרגיה","name_en":"Energy Drink",
     "category":"beverage","calories_kcal":45.0,"protein_g":0.5,"carbs_g":11.0,"fat_g":0.0,
     "default_unit":"cup","default_serving_g":250.0,"aliases_he":["רד בול","מונסטר"],"aliases_en":["red bull","monster energy","energy shot"],"source":"curated"},
    {"food_id":"food_398","name_he":"תה קמומיל","name_en":"Chamomile Tea",
     "category":"beverage","calories_kcal":1.0,"protein_g":0.0,"carbs_g":0.2,"fat_g":0.0,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["תה עשבים","קמומיל"],"aliases_en":["herbal tea","calming tea"],"source":"curated"},
    {"food_id":"food_399","name_he":"משקה ספורט","name_en":"Sports Drink",
     "category":"beverage","calories_kcal":26.0,"protein_g":0.0,"carbs_g":6.7,"fat_g":0.0,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["גאטורייד","פאוורייד"],"aliases_en":["gatorade","powerade","electrolyte drink"],"source":"curated"},

    # ── OILS & SPREADS (more) ─────────────────────────────────────────────────
    {"food_id":"food_400","name_he":"שמן חמנייה","name_en":"Sunflower Oil",
     "category":"fat","calories_kcal":884.0,"protein_g":0.0,"carbs_g":0.0,"fat_g":100.0,
     "default_unit":"tablespoon","default_serving_g":14.0,"aliases_he":["שמן חמניות"],"aliases_en":["vegetable sunflower oil","high oleic sunflower"],"source":"curated"},
    {"food_id":"food_401","name_he":"שמן תירס","name_en":"Corn Oil",
     "category":"fat","calories_kcal":884.0,"protein_g":0.0,"carbs_g":0.0,"fat_g":100.0,
     "default_unit":"tablespoon","default_serving_g":14.0,"aliases_he":[],"aliases_en":["maize oil","cooking oil"],"source":"curated"},
    {"food_id":"food_402","name_he":"ממרח אגוזים","name_en":"Cashew Butter",
     "category":"fat","calories_kcal":587.0,"protein_g":17.0,"carbs_g":27.0,"fat_g":49.0,
     "fiber_g":3.0,"default_unit":"tablespoon","default_serving_g":32.0,"aliases_he":["חמאת קשיו"],"aliases_en":["cashew spread","nut butter"],"source":"curated"},
    {"food_id":"food_403","name_he":"שמן אגוז מלך","name_en":"Walnut Oil",
     "category":"fat","calories_kcal":884.0,"protein_g":0.0,"carbs_g":0.0,"fat_g":100.0,
     "default_unit":"tablespoon","default_serving_g":14.0,"aliases_he":["שמן אגוזים"],"aliases_en":["cold-pressed walnut oil"],"source":"curated"},

    # ── SWEETENERS & BAKING ───────────────────────────────────────────────────
    {"food_id":"food_404","name_he":"סוכר לבן","name_en":"White Sugar",
     "category":"other","calories_kcal":387.0,"protein_g":0.0,"carbs_g":100.0,"fat_g":0.0,
     "default_unit":"teaspoon","default_serving_g":5.0,"aliases_he":["סוכר","סוכר גבישי"],"aliases_en":["granulated sugar","table sugar"],"source":"curated"},
    {"food_id":"food_405","name_he":"סוכר חום","name_en":"Brown Sugar",
     "category":"other","calories_kcal":380.0,"protein_g":0.0,"carbs_g":98.0,"fat_g":0.0,
     "default_unit":"teaspoon","default_serving_g":5.0,"aliases_he":["סוכר חום כהה","דמררה"],"aliases_en":["dark brown sugar","demerara","muscovado"],"source":"curated"},
    {"food_id":"food_406","name_he":"סירופ מייפל","name_en":"Maple Syrup",
     "category":"other","calories_kcal":260.0,"protein_g":0.0,"carbs_g":67.0,"fat_g":0.1,
     "default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["מייפל","סירופ ארז"],"aliases_en":["pure maple syrup","grade A maple"],"source":"curated"},
    {"food_id":"food_407","name_he":"דבש ממרח","name_en":"Agave Nectar",
     "category":"other","calories_kcal":310.0,"protein_g":0.1,"carbs_g":76.0,"fat_g":0.5,
     "default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["נקטר אגבה","אגבה"],"aliases_en":["agave syrup","agave sweetener"],"source":"curated"},
    {"food_id":"food_408","name_he":"שוקולד לבן","name_en":"White Chocolate",
     "category":"other","calories_kcal":539.0,"protein_g":5.9,"carbs_g":59.2,"fat_g":32.0,
     "fiber_g":0.2,"default_serving_g":30.0,"aliases_he":[],"aliases_en":["white choc","ivory chocolate"],"source":"curated"},
    {"food_id":"food_409","name_he":"שוקולד 70%","name_en":"Dark Chocolate 70%",
     "category":"other","calories_kcal":546.0,"protein_g":5.0,"carbs_g":60.0,"fat_g":31.0,
     "fiber_g":7.0,"default_serving_g":30.0,"aliases_he":["שוקולד מריר 70%","שוקולד מריר"],"aliases_en":["bittersweet chocolate","semisweet chocolate"],"source":"curated"},
    {"food_id":"food_410","name_he":"פצפוצי אורז","name_en":"Rice Cakes",
     "category":"grain","calories_kcal":387.0,"protein_g":8.0,"carbs_g":82.0,"fat_g":3.5,
     "fiber_g":3.5,"default_unit":"unit","default_serving_g":9.0,"aliases_he":["קרקרי אורז","עוגיית אורז"],"aliases_en":["puffed rice cakes","galettes de riz"],"source":"curated"},
]
