"""Extended food library — batch 4 (food_501 to food_650)."""
from typing import List, Dict

EXTENDED_FOODS_4: List[Dict] = [
    # === MORE BEEF ===
    {"food_id": "food_501", "name_he": "בשר בקר טחון רזה", "name_en": "Lean Ground Beef", "category": "protein", "calories_kcal": 215, "protein_g": 26.0, "carbs_g": 0.0, "fat_g": 12.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 75.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_502", "name_he": "סטייק פילה מיניון", "name_en": "Filet Mignon", "category": "protein", "calories_kcal": 227, "protein_g": 26.0, "carbs_g": 0.0, "fat_g": 13.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 54.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_503", "name_he": "צלעות בקר", "name_en": "Beef Ribs", "category": "protein", "calories_kcal": 291, "protein_g": 22.0, "carbs_g": 0.0, "fat_g": 22.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 80.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_504", "name_he": "נתח בקר לצלייה", "name_en": "Beef Chuck Roast", "category": "protein", "calories_kcal": 255, "protein_g": 26.0, "carbs_g": 0.0, "fat_g": 16.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 66.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_505", "name_he": "שקדי עגל", "name_en": "Veal Sweetbreads", "category": "protein", "calories_kcal": 148, "protein_g": 17.0, "carbs_g": 0.0, "fat_g": 8.5, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 116.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_506", "name_he": "כבד בקר", "name_en": "Beef Liver", "category": "protein", "calories_kcal": 135, "protein_g": 20.0, "carbs_g": 4.0, "fat_g": 3.8, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 76.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_507", "name_he": "לשון בקר", "name_en": "Beef Tongue", "category": "protein", "calories_kcal": 224, "protein_g": 17.0, "carbs_g": 3.7, "fat_g": 16.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 60.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},

    # === LAMB ===
    {"food_id": "food_508", "name_he": "כתף כבש", "name_en": "Lamb Shoulder", "category": "protein", "calories_kcal": 253, "protein_g": 21.0, "carbs_g": 0.0, "fat_g": 18.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 72.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_509", "name_he": "צלעות כבש", "name_en": "Lamb Chops", "category": "protein", "calories_kcal": 294, "protein_g": 24.0, "carbs_g": 0.0, "fat_g": 21.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 80.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_510", "name_he": "כבש טחון", "name_en": "Ground Lamb", "category": "protein", "calories_kcal": 282, "protein_g": 17.0, "carbs_g": 0.0, "fat_g": 23.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 79.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},

    # === PORK ===
    {"food_id": "food_511", "name_he": "סינטה חזיר", "name_en": "Pork Loin", "category": "protein", "calories_kcal": 182, "protein_g": 25.0, "carbs_g": 0.0, "fat_g": 9.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 55.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_512", "name_he": "בטן חזיר", "name_en": "Pork Belly", "category": "protein", "calories_kcal": 518, "protein_g": 9.3, "carbs_g": 0.0, "fat_g": 53.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 42.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_513", "name_he": "צלעות חזיר", "name_en": "Pork Ribs", "category": "protein", "calories_kcal": 278, "protein_g": 19.0, "carbs_g": 0.0, "fat_g": 22.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 75.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_514", "name_he": "נקניק חזיר", "name_en": "Pork Sausage", "category": "protein", "calories_kcal": 301, "protein_g": 12.0, "carbs_g": 2.0, "fat_g": 27.0, "fiber_g": 0.0, "sugar_g": 1.0, "sodium_mg": 749.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},

    # === MORE POULTRY ===
    {"food_id": "food_515", "name_he": "כנפיים עוף", "name_en": "Chicken Wings", "category": "protein", "calories_kcal": 203, "protein_g": 17.0, "carbs_g": 0.0, "fat_g": 14.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 82.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_516", "name_he": "עוף שלם קלוי", "name_en": "Whole Roast Chicken", "category": "protein", "calories_kcal": 215, "protein_g": 18.0, "carbs_g": 0.0, "fat_g": 15.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 77.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_517", "name_he": "חזה הודו", "name_en": "Turkey Breast", "category": "protein", "calories_kcal": 135, "protein_g": 30.0, "carbs_g": 0.0, "fat_g": 1.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 63.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_518", "name_he": "שוק הודו", "name_en": "Turkey Leg", "category": "protein", "calories_kcal": 159, "protein_g": 23.0, "carbs_g": 0.0, "fat_g": 7.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 79.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_519", "name_he": "ברווז", "name_en": "Duck Breast", "category": "protein", "calories_kcal": 201, "protein_g": 23.5, "carbs_g": 0.0, "fat_g": 11.2, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 74.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},

    # === MORE FISH & SEAFOOD ===
    {"food_id": "food_520", "name_he": "פורל", "name_en": "Rainbow Trout", "category": "protein", "calories_kcal": 148, "protein_g": 21.0, "carbs_g": 0.0, "fat_g": 6.6, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 52.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_521", "name_he": "פייק", "name_en": "Pike", "category": "protein", "calories_kcal": 88, "protein_g": 19.0, "carbs_g": 0.0, "fat_g": 0.7, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 39.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_522", "name_he": "הליבוט", "name_en": "Halibut", "category": "protein", "calories_kcal": 110, "protein_g": 23.0, "carbs_g": 0.0, "fat_g": 1.4, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 68.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_523", "name_he": "מקרל", "name_en": "Mackerel", "category": "protein", "calories_kcal": 205, "protein_g": 19.0, "carbs_g": 0.0, "fat_g": 13.9, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 90.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_524", "name_he": "הרינג", "name_en": "Herring", "category": "protein", "calories_kcal": 158, "protein_g": 18.0, "carbs_g": 0.0, "fat_g": 9.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 90.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_525", "name_he": "מולים", "name_en": "Mussels", "category": "protein", "calories_kcal": 86, "protein_g": 12.0, "carbs_g": 3.7, "fat_g": 2.2, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 286.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_526", "name_he": "צדפות", "name_en": "Oysters", "category": "protein", "calories_kcal": 68, "protein_g": 7.0, "carbs_g": 3.9, "fat_g": 2.5, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 211.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_527", "name_he": "קלמרי", "name_en": "Calamari / Squid", "category": "protein", "calories_kcal": 92, "protein_g": 15.6, "carbs_g": 3.1, "fat_g": 1.4, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 44.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_528", "name_he": "תמנון", "name_en": "Octopus", "category": "protein", "calories_kcal": 82, "protein_g": 14.9, "carbs_g": 2.2, "fat_g": 1.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 230.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},

    # === PLANT PROTEINS ===
    {"food_id": "food_529", "name_he": "אפונה ירוקה", "name_en": "Green Peas", "category": "legumes", "calories_kcal": 81, "protein_g": 5.4, "carbs_g": 14.5, "fat_g": 0.4, "fiber_g": 5.1, "sugar_g": 5.7, "sodium_mg": 5.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_530", "name_he": "פולי סויה", "name_en": "Soybeans Cooked", "category": "legumes", "calories_kcal": 173, "protein_g": 16.6, "carbs_g": 10.0, "fat_g": 9.0, "fiber_g": 6.0, "sugar_g": 3.0, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_531", "name_he": "שעועית שחורה", "name_en": "Black Beans Cooked", "category": "legumes", "calories_kcal": 132, "protein_g": 8.9, "carbs_g": 24.0, "fat_g": 0.5, "fiber_g": 8.7, "sugar_g": 0.3, "sodium_mg": 2.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_532", "name_he": "שעועית פינטו", "name_en": "Pinto Beans Cooked", "category": "legumes", "calories_kcal": 143, "protein_g": 9.0, "carbs_g": 26.0, "fat_g": 0.7, "fiber_g": 9.0, "sugar_g": 0.4, "sodium_mg": 2.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_533", "name_he": "שעועית ליים", "name_en": "Lima Beans Cooked", "category": "legumes", "calories_kcal": 115, "protein_g": 7.8, "carbs_g": 20.9, "fat_g": 0.4, "fiber_g": 7.0, "sugar_g": 2.9, "sodium_mg": 3.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_534", "name_he": "טמפה", "name_en": "Tempeh", "category": "protein", "calories_kcal": 193, "protein_g": 19.9, "carbs_g": 7.6, "fat_g": 11.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 9.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_535", "name_he": "סייטן", "name_en": "Seitan", "category": "protein", "calories_kcal": 370, "protein_g": 75.0, "carbs_g": 14.0, "fat_g": 1.9, "fiber_g": 0.6, "sugar_g": 0.0, "sodium_mg": 390.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_536", "name_he": "שעועית מאש", "name_en": "Mung Beans Cooked", "category": "legumes", "calories_kcal": 105, "protein_g": 7.0, "carbs_g": 19.2, "fat_g": 0.4, "fiber_g": 7.6, "sugar_g": 2.0, "sodium_mg": 2.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},

    # === DAIRY & EGGS ===
    {"food_id": "food_537", "name_he": "גבינה צהובה עממית", "name_en": "Cheddar Cheese", "category": "dairy", "calories_kcal": 403, "protein_g": 25.0, "carbs_g": 1.3, "fat_g": 33.0, "fiber_g": 0.0, "sugar_g": 0.5, "sodium_mg": 621.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_538", "name_he": "גבינת עיזים", "name_en": "Goat Cheese", "category": "dairy", "calories_kcal": 364, "protein_g": 21.6, "carbs_g": 0.1, "fat_g": 30.5, "fiber_g": 0.0, "sugar_g": 0.1, "sodium_mg": 515.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_539", "name_he": "גבינת פרמזן", "name_en": "Parmesan Cheese", "category": "dairy", "calories_kcal": 431, "protein_g": 38.0, "carbs_g": 4.1, "fat_g": 29.0, "fiber_g": 0.0, "sugar_g": 0.8, "sodium_mg": 1529.0, "default_unit": "gram", "default_serving_g": 20.0, "source": "curated"},
    {"food_id": "food_540", "name_he": "גבינת ריקוטה", "name_en": "Ricotta Cheese", "category": "dairy", "calories_kcal": 174, "protein_g": 11.3, "carbs_g": 3.0, "fat_g": 13.0, "fiber_g": 0.0, "sugar_g": 0.3, "sodium_mg": 84.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_541", "name_he": "גבינת קממבר", "name_en": "Camembert Cheese", "category": "dairy", "calories_kcal": 300, "protein_g": 19.8, "carbs_g": 0.5, "fat_g": 24.3, "fiber_g": 0.0, "sugar_g": 0.5, "sodium_mg": 842.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_542", "name_he": "שמנת חמוצה", "name_en": "Sour Cream", "category": "dairy", "calories_kcal": 198, "protein_g": 2.4, "carbs_g": 4.6, "fat_g": 19.4, "fiber_g": 0.0, "sugar_g": 3.8, "sodium_mg": 53.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_543", "name_he": "חמאה", "name_en": "Butter", "category": "fats", "calories_kcal": 717, "protein_g": 0.9, "carbs_g": 0.1, "fat_g": 81.0, "fiber_g": 0.0, "sugar_g": 0.1, "sodium_mg": 714.0, "default_unit": "gram", "default_serving_g": 10.0, "source": "curated"},
    {"food_id": "food_544", "name_he": "קצפת", "name_en": "Heavy Whipping Cream", "category": "dairy", "calories_kcal": 340, "protein_g": 2.1, "carbs_g": 2.8, "fat_g": 36.1, "fiber_g": 0.0, "sugar_g": 2.8, "sodium_mg": 27.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_545", "name_he": "ביצה קשה", "name_en": "Hard Boiled Egg", "category": "protein", "calories_kcal": 155, "protein_g": 13.0, "carbs_g": 1.1, "fat_g": 10.6, "fiber_g": 0.0, "sugar_g": 1.1, "sodium_mg": 124.0, "default_unit": "unit", "default_serving_g": 50.0, "source": "curated"},
    {"food_id": "food_546", "name_he": "חלבון ביצה", "name_en": "Egg White", "category": "protein", "calories_kcal": 52, "protein_g": 11.0, "carbs_g": 0.7, "fat_g": 0.2, "fiber_g": 0.0, "sugar_g": 0.7, "sodium_mg": 166.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_547", "name_he": "חלמון ביצה", "name_en": "Egg Yolk", "category": "protein", "calories_kcal": 322, "protein_g": 16.0, "carbs_g": 3.6, "fat_g": 27.0, "fiber_g": 0.0, "sugar_g": 0.6, "sodium_mg": 48.0, "default_unit": "gram", "default_serving_g": 20.0, "source": "curated"},

    # === GRAINS & BREADS ===
    {"food_id": "food_548", "name_he": "קמח לבן", "name_en": "All Purpose Flour", "category": "grains", "calories_kcal": 364, "protein_g": 10.3, "carbs_g": 76.3, "fat_g": 1.0, "fiber_g": 2.7, "sugar_g": 0.3, "sodium_mg": 2.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_549", "name_he": "קמח כוסמין", "name_en": "Spelt Flour", "category": "grains", "calories_kcal": 338, "protein_g": 14.6, "carbs_g": 70.0, "fat_g": 2.4, "fiber_g": 10.9, "sugar_g": 0.0, "sodium_mg": 0.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_550", "name_he": "לחם שיפון", "name_en": "Rye Bread", "category": "grains", "calories_kcal": 259, "protein_g": 8.5, "carbs_g": 48.3, "fat_g": 3.3, "fiber_g": 5.8, "sugar_g": 3.8, "sodium_mg": 603.0, "default_unit": "gram", "default_serving_g": 40.0, "source": "curated"},
    {"food_id": "food_551", "name_he": "לחם לבן", "name_en": "White Bread", "category": "grains", "calories_kcal": 265, "protein_g": 9.0, "carbs_g": 49.0, "fat_g": 3.2, "fiber_g": 2.7, "sugar_g": 5.0, "sodium_mg": 491.0, "default_unit": "gram", "default_serving_g": 40.0, "source": "curated"},
    {"food_id": "food_552", "name_he": "בגט", "name_en": "Baguette", "category": "grains", "calories_kcal": 272, "protein_g": 9.4, "carbs_g": 54.0, "fat_g": 1.5, "fiber_g": 2.3, "sugar_g": 2.0, "sodium_mg": 536.0, "default_unit": "gram", "default_serving_g": 60.0, "source": "curated"},
    {"food_id": "food_553", "name_he": "קרואסון", "name_en": "Croissant", "category": "grains", "calories_kcal": 406, "protein_g": 8.2, "carbs_g": 45.0, "fat_g": 21.0, "fiber_g": 2.6, "sugar_g": 10.5, "sodium_mg": 375.0, "default_unit": "unit", "default_serving_g": 60.0, "source": "curated"},
    {"food_id": "food_554", "name_he": "מאפין אוכמניות", "name_en": "Blueberry Muffin", "category": "snacks", "calories_kcal": 377, "protein_g": 5.5, "carbs_g": 56.0, "fat_g": 15.0, "fiber_g": 1.7, "sugar_g": 28.0, "sodium_mg": 378.0, "default_unit": "unit", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_555", "name_he": "ביסקוויט", "name_en": "Biscuit", "category": "grains", "calories_kcal": 362, "protein_g": 7.1, "carbs_g": 46.0, "fat_g": 16.3, "fiber_g": 1.5, "sugar_g": 4.5, "sodium_mg": 586.0, "default_unit": "unit", "default_serving_g": 60.0, "source": "curated"},
    {"food_id": "food_556", "name_he": "קורנפלקס", "name_en": "Corn Flakes Cereal", "category": "grains", "calories_kcal": 357, "protein_g": 7.5, "carbs_g": 84.0, "fat_g": 0.4, "fiber_g": 2.0, "sugar_g": 8.0, "sodium_mg": 527.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_557", "name_he": "גרנולה", "name_en": "Granola", "category": "grains", "calories_kcal": 471, "protein_g": 10.0, "carbs_g": 64.0, "fat_g": 20.0, "fiber_g": 6.6, "sugar_g": 24.0, "sodium_mg": 30.0, "default_unit": "gram", "default_serving_g": 50.0, "source": "curated"},
    {"food_id": "food_558", "name_he": "שיבולת שועל מיידנטית", "name_en": "Instant Oatmeal", "category": "grains", "calories_kcal": 367, "protein_g": 12.5, "carbs_g": 67.0, "fat_g": 7.0, "fiber_g": 5.9, "sugar_g": 1.1, "sodium_mg": 385.0, "default_unit": "gram", "default_serving_g": 40.0, "source": "curated"},
    {"food_id": "food_559", "name_he": "פסטה פנה", "name_en": "Penne Pasta Cooked", "category": "grains", "calories_kcal": 131, "protein_g": 5.0, "carbs_g": 25.0, "fat_g": 1.1, "fiber_g": 1.8, "sugar_g": 0.6, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_560", "name_he": "ספגטי מבושל", "name_en": "Spaghetti Cooked", "category": "grains", "calories_kcal": 158, "protein_g": 5.8, "carbs_g": 31.0, "fat_g": 0.9, "fiber_g": 1.8, "sugar_g": 0.6, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_561", "name_he": "ריזוטו", "name_en": "Risotto", "category": "grains", "calories_kcal": 130, "protein_g": 3.5, "carbs_g": 22.0, "fat_g": 3.5, "fiber_g": 0.5, "sugar_g": 0.5, "sodium_mg": 260.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},

    # === VEGETABLES ===
    {"food_id": "food_562", "name_he": "סלק", "name_en": "Beetroot", "category": "vegetables", "calories_kcal": 43, "protein_g": 1.6, "carbs_g": 9.6, "fat_g": 0.2, "fiber_g": 2.8, "sugar_g": 6.8, "sodium_mg": 78.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_563", "name_he": "אספרגוס", "name_en": "Asparagus", "category": "vegetables", "calories_kcal": 20, "protein_g": 2.2, "carbs_g": 3.9, "fat_g": 0.1, "fiber_g": 2.1, "sugar_g": 1.9, "sodium_mg": 2.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_564", "name_he": "חסה", "name_en": "Romaine Lettuce", "category": "vegetables", "calories_kcal": 17, "protein_g": 1.2, "carbs_g": 3.3, "fat_g": 0.3, "fiber_g": 2.1, "sugar_g": 1.2, "sodium_mg": 8.0, "default_unit": "gram", "default_serving_g": 80.0, "source": "curated"},
    {"food_id": "food_565", "name_he": "תרד", "name_en": "Spinach Raw", "category": "vegetables", "calories_kcal": 23, "protein_g": 2.9, "carbs_g": 3.6, "fat_g": 0.4, "fiber_g": 2.2, "sugar_g": 0.4, "sodium_mg": 79.0, "default_unit": "gram", "default_serving_g": 80.0, "source": "curated"},
    {"food_id": "food_566", "name_he": "כרובית", "name_en": "Cauliflower", "category": "vegetables", "calories_kcal": 25, "protein_g": 1.9, "carbs_g": 5.0, "fat_g": 0.3, "fiber_g": 2.0, "sugar_g": 1.9, "sodium_mg": 30.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_567", "name_he": "ברוקולי", "name_en": "Broccoli", "category": "vegetables", "calories_kcal": 34, "protein_g": 2.8, "carbs_g": 6.6, "fat_g": 0.4, "fiber_g": 2.6, "sugar_g": 1.7, "sodium_mg": 33.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_568", "name_he": "כרוב ניצנים", "name_en": "Brussels Sprouts", "category": "vegetables", "calories_kcal": 43, "protein_g": 3.4, "carbs_g": 9.0, "fat_g": 0.3, "fiber_g": 3.8, "sugar_g": 2.2, "sodium_mg": 25.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_569", "name_he": "כרוב סגול", "name_en": "Red Cabbage", "category": "vegetables", "calories_kcal": 31, "protein_g": 1.4, "carbs_g": 7.4, "fat_g": 0.2, "fiber_g": 2.1, "sugar_g": 3.8, "sodium_mg": 27.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_570", "name_he": "ארטישוק", "name_en": "Artichoke", "category": "vegetables", "calories_kcal": 47, "protein_g": 3.3, "carbs_g": 10.5, "fat_g": 0.2, "fiber_g": 5.4, "sugar_g": 1.0, "sodium_mg": 94.0, "default_unit": "unit", "default_serving_g": 120.0, "source": "curated"},
    {"food_id": "food_571", "name_he": "שעורה מבושלת", "name_en": "Barley Cooked", "category": "grains", "calories_kcal": 123, "protein_g": 2.3, "carbs_g": 28.2, "fat_g": 0.4, "fiber_g": 3.8, "sugar_g": 0.3, "sodium_mg": 3.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_572", "name_he": "פלפל כתום", "name_en": "Orange Bell Pepper", "category": "vegetables", "calories_kcal": 31, "protein_g": 1.0, "carbs_g": 7.4, "fat_g": 0.3, "fiber_g": 2.5, "sugar_g": 4.7, "sodium_mg": 3.0, "default_unit": "unit", "default_serving_g": 120.0, "source": "curated"},
    {"food_id": "food_573", "name_he": "אנדיב", "name_en": "Endive", "category": "vegetables", "calories_kcal": 17, "protein_g": 1.3, "carbs_g": 3.4, "fat_g": 0.2, "fiber_g": 3.1, "sugar_g": 0.3, "sodium_mg": 22.0, "default_unit": "gram", "default_serving_g": 80.0, "source": "curated"},
    {"food_id": "food_574", "name_he": "קישוא", "name_en": "Zucchini", "category": "vegetables", "calories_kcal": 17, "protein_g": 1.2, "carbs_g": 3.1, "fat_g": 0.3, "fiber_g": 1.0, "sugar_g": 2.5, "sodium_mg": 8.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_575", "name_he": "פטריות שמפיניון", "name_en": "Button Mushrooms", "category": "vegetables", "calories_kcal": 22, "protein_g": 3.1, "carbs_g": 3.3, "fat_g": 0.3, "fiber_g": 1.0, "sugar_g": 2.0, "sodium_mg": 5.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_576", "name_he": "פטריות פורטובלו", "name_en": "Portobello Mushrooms", "category": "vegetables", "calories_kcal": 22, "protein_g": 2.1, "carbs_g": 3.9, "fat_g": 0.4, "fiber_g": 1.3, "sugar_g": 2.1, "sodium_mg": 9.0, "default_unit": "unit", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_577", "name_he": "בצל ירוק", "name_en": "Green Onion / Scallion", "category": "vegetables", "calories_kcal": 32, "protein_g": 1.8, "carbs_g": 7.3, "fat_g": 0.2, "fiber_g": 2.6, "sugar_g": 2.3, "sodium_mg": 16.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_578", "name_he": "ג'ינג'ר טרי", "name_en": "Fresh Ginger", "category": "vegetables", "calories_kcal": 80, "protein_g": 1.8, "carbs_g": 18.0, "fat_g": 0.8, "fiber_g": 2.0, "sugar_g": 1.7, "sodium_mg": 13.0, "default_unit": "gram", "default_serving_g": 5.0, "source": "curated"},
    {"food_id": "food_579", "name_he": "פלפל חריף", "name_en": "Chili Pepper", "category": "vegetables", "calories_kcal": 40, "protein_g": 1.9, "carbs_g": 8.8, "fat_g": 0.4, "fiber_g": 1.5, "sugar_g": 5.3, "sodium_mg": 9.0, "default_unit": "gram", "default_serving_g": 10.0, "source": "curated"},
    {"food_id": "food_580", "name_he": "כרישה", "name_en": "Leek", "category": "vegetables", "calories_kcal": 61, "protein_g": 1.5, "carbs_g": 14.2, "fat_g": 0.3, "fiber_g": 1.8, "sugar_g": 3.9, "sodium_mg": 20.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},

    # === FRUITS ===
    {"food_id": "food_581", "name_he": "פסיפלורה", "name_en": "Passion Fruit", "category": "fruits", "calories_kcal": 97, "protein_g": 2.2, "carbs_g": 23.4, "fat_g": 0.7, "fiber_g": 10.4, "sugar_g": 11.2, "sodium_mg": 28.0, "default_unit": "unit", "default_serving_g": 60.0, "source": "curated"},
    {"food_id": "food_582", "name_he": "פפאיה", "name_en": "Papaya", "category": "fruits", "calories_kcal": 43, "protein_g": 0.5, "carbs_g": 11.0, "fat_g": 0.3, "fiber_g": 1.7, "sugar_g": 7.8, "sodium_mg": 8.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_583", "name_he": "גויאבה", "name_en": "Guava", "category": "fruits", "calories_kcal": 68, "protein_g": 2.6, "carbs_g": 14.3, "fat_g": 1.0, "fiber_g": 5.4, "sugar_g": 8.9, "sodium_mg": 2.0, "default_unit": "unit", "default_serving_g": 90.0, "source": "curated"},
    {"food_id": "food_584", "name_he": "תמר", "name_en": "Dates Medjool", "category": "fruits", "calories_kcal": 277, "protein_g": 1.8, "carbs_g": 75.0, "fat_g": 0.2, "fiber_g": 6.7, "sugar_g": 63.4, "sodium_mg": 1.0, "default_unit": "unit", "default_serving_g": 24.0, "source": "curated"},
    {"food_id": "food_585", "name_he": "רימון", "name_en": "Pomegranate", "category": "fruits", "calories_kcal": 83, "protein_g": 1.7, "carbs_g": 18.7, "fat_g": 1.2, "fiber_g": 4.0, "sugar_g": 13.7, "sodium_mg": 3.0, "default_unit": "unit", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_586", "name_he": "לוקאט", "name_en": "Loquat", "category": "fruits", "calories_kcal": 47, "protein_g": 0.4, "carbs_g": 12.1, "fat_g": 0.2, "fiber_g": 1.7, "sugar_g": 6.1, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_587", "name_he": "מנגו", "name_en": "Mango", "category": "fruits", "calories_kcal": 60, "protein_g": 0.8, "carbs_g": 15.0, "fat_g": 0.4, "fiber_g": 1.6, "sugar_g": 13.7, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_588", "name_he": "אוכמניות", "name_en": "Blueberries", "category": "fruits", "calories_kcal": 57, "protein_g": 0.7, "carbs_g": 14.5, "fat_g": 0.3, "fiber_g": 2.4, "sugar_g": 10.0, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_589", "name_he": "פטל", "name_en": "Raspberries", "category": "fruits", "calories_kcal": 52, "protein_g": 1.2, "carbs_g": 11.9, "fat_g": 0.7, "fiber_g": 6.5, "sugar_g": 4.4, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_590", "name_he": "תות שדה", "name_en": "Strawberries", "category": "fruits", "calories_kcal": 32, "protein_g": 0.7, "carbs_g": 7.7, "fat_g": 0.3, "fiber_g": 2.0, "sugar_g": 4.9, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_591", "name_he": "אננס", "name_en": "Pineapple", "category": "fruits", "calories_kcal": 50, "protein_g": 0.5, "carbs_g": 13.1, "fat_g": 0.1, "fiber_g": 1.4, "sugar_g": 9.9, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_592", "name_he": "אבוקדו", "name_en": "Avocado", "category": "fruits", "calories_kcal": 160, "protein_g": 2.0, "carbs_g": 8.5, "fat_g": 14.7, "fiber_g": 6.7, "sugar_g": 0.7, "sodium_mg": 7.0, "default_unit": "unit", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_593", "name_he": "ענבים ירוקים", "name_en": "Green Grapes", "category": "fruits", "calories_kcal": 69, "protein_g": 0.7, "carbs_g": 18.1, "fat_g": 0.2, "fiber_g": 0.9, "sugar_g": 15.5, "sodium_mg": 2.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},

    # === FAST FOOD & PREPARED ===
    {"food_id": "food_594", "name_he": "המבורגר קלאסי", "name_en": "Classic Hamburger", "category": "prepared_food", "calories_kcal": 295, "protein_g": 17.0, "carbs_g": 24.0, "fat_g": 14.0, "fiber_g": 1.0, "sugar_g": 5.0, "sodium_mg": 509.0, "default_unit": "unit", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_595", "name_he": "המבורגר עם גבינה", "name_en": "Cheeseburger", "category": "prepared_food", "calories_kcal": 354, "protein_g": 20.0, "carbs_g": 27.0, "fat_g": 17.0, "fiber_g": 1.0, "sugar_g": 5.0, "sodium_mg": 791.0, "default_unit": "unit", "default_serving_g": 170.0, "source": "curated"},
    {"food_id": "food_596", "name_he": "נאגטס עוף", "name_en": "Chicken Nuggets", "category": "prepared_food", "calories_kcal": 297, "protein_g": 14.0, "carbs_g": 18.0, "fat_g": 18.0, "fiber_g": 0.5, "sugar_g": 0.0, "sodium_mg": 675.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_597", "name_he": "פיצה מרגריטה", "name_en": "Pizza Margherita", "category": "prepared_food", "calories_kcal": 266, "protein_g": 11.0, "carbs_g": 33.0, "fat_g": 10.0, "fiber_g": 2.3, "sugar_g": 3.6, "sodium_mg": 598.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_598", "name_he": "פיצה פפרוני", "name_en": "Pepperoni Pizza", "category": "prepared_food", "calories_kcal": 297, "protein_g": 12.0, "carbs_g": 32.0, "fat_g": 13.0, "fiber_g": 2.0, "sugar_g": 3.0, "sodium_mg": 760.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_599", "name_he": "צ'יפס מקפוא", "name_en": "Frozen French Fries", "category": "prepared_food", "calories_kcal": 162, "protein_g": 2.5, "carbs_g": 27.0, "fat_g": 5.4, "fiber_g": 2.8, "sugar_g": 0.2, "sodium_mg": 230.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_600", "name_he": "כרכר תירס", "name_en": "Corn Dog", "category": "prepared_food", "calories_kcal": 262, "protein_g": 6.7, "carbs_g": 23.0, "fat_g": 16.0, "fiber_g": 0.8, "sugar_g": 4.6, "sodium_mg": 572.0, "default_unit": "unit", "default_serving_g": 75.0, "source": "curated"},
    {"food_id": "food_601", "name_he": "בוריטו עוף", "name_en": "Chicken Burrito", "category": "prepared_food", "calories_kcal": 206, "protein_g": 12.0, "carbs_g": 21.0, "fat_g": 7.9, "fiber_g": 1.7, "sugar_g": 1.5, "sodium_mg": 540.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_602", "name_he": "טאקו עוף", "name_en": "Chicken Taco", "category": "prepared_food", "calories_kcal": 226, "protein_g": 15.0, "carbs_g": 20.0, "fat_g": 9.1, "fiber_g": 2.0, "sugar_g": 1.0, "sodium_mg": 480.0, "default_unit": "unit", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_603", "name_he": "קסדיה", "name_en": "Quesadilla", "category": "prepared_food", "calories_kcal": 306, "protein_g": 14.0, "carbs_g": 28.0, "fat_g": 15.0, "fiber_g": 1.7, "sugar_g": 1.0, "sodium_mg": 574.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_604", "name_he": "נאצ'וס", "name_en": "Nachos with Cheese", "category": "prepared_food", "calories_kcal": 346, "protein_g": 9.5, "carbs_g": 36.0, "fat_g": 18.0, "fiber_g": 3.0, "sugar_g": 2.0, "sodium_mg": 671.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_605", "name_he": "ספרינג רול מטוגן", "name_en": "Fried Spring Roll", "category": "prepared_food", "calories_kcal": 223, "protein_g": 5.0, "carbs_g": 23.0, "fat_g": 13.0, "fiber_g": 1.5, "sugar_g": 2.0, "sodium_mg": 392.0, "default_unit": "unit", "default_serving_g": 70.0, "source": "curated"},
    {"food_id": "food_606", "name_he": "פפר-ג'ק", "name_en": "Pepper Jack Cheese", "category": "dairy", "calories_kcal": 367, "protein_g": 22.8, "carbs_g": 1.2, "fat_g": 29.8, "fiber_g": 0.0, "sugar_g": 0.3, "sodium_mg": 626.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},

    # === SOUPS & STEWS ===
    {"food_id": "food_607", "name_he": "מרק עגבניות", "name_en": "Tomato Soup", "category": "prepared_food", "calories_kcal": 74, "protein_g": 1.8, "carbs_g": 11.9, "fat_g": 2.9, "fiber_g": 1.5, "sugar_g": 7.3, "sodium_mg": 471.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_608", "name_he": "מרק עוף עם אטריות", "name_en": "Chicken Noodle Soup", "category": "prepared_food", "calories_kcal": 32, "protein_g": 2.6, "carbs_g": 3.3, "fat_g": 0.8, "fiber_g": 0.3, "sugar_g": 0.5, "sodium_mg": 320.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_609", "name_he": "מרק עדשים", "name_en": "Lentil Soup", "category": "prepared_food", "calories_kcal": 99, "protein_g": 6.0, "carbs_g": 16.0, "fat_g": 2.0, "fiber_g": 3.6, "sugar_g": 2.0, "sodium_mg": 380.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_610", "name_he": "מרק מינסטרונה", "name_en": "Minestrone Soup", "category": "prepared_food", "calories_kcal": 62, "protein_g": 2.7, "carbs_g": 11.0, "fat_g": 1.5, "fiber_g": 2.0, "sugar_g": 3.0, "sodium_mg": 445.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},

    # === SAUCES & CONDIMENTS ===
    {"food_id": "food_611", "name_he": "רוטב חמוץ מתוק", "name_en": "Sweet and Sour Sauce", "category": "condiments", "calories_kcal": 91, "protein_g": 0.4, "carbs_g": 22.8, "fat_g": 0.1, "fiber_g": 0.3, "sugar_g": 18.0, "sodium_mg": 373.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_612", "name_he": "מיונז", "name_en": "Mayonnaise", "category": "condiments", "calories_kcal": 680, "protein_g": 1.0, "carbs_g": 0.6, "fat_g": 75.0, "fiber_g": 0.0, "sugar_g": 0.4, "sodium_mg": 635.0, "default_unit": "gram", "default_serving_g": 15.0, "source": "curated"},
    {"food_id": "food_613", "name_he": "חרדל", "name_en": "Yellow Mustard", "category": "condiments", "calories_kcal": 66, "protein_g": 4.4, "carbs_g": 8.0, "fat_g": 3.6, "fiber_g": 3.2, "sugar_g": 2.5, "sodium_mg": 1252.0, "default_unit": "gram", "default_serving_g": 10.0, "source": "curated"},
    {"food_id": "food_614", "name_he": "קטשופ", "name_en": "Tomato Ketchup", "category": "condiments", "calories_kcal": 112, "protein_g": 1.5, "carbs_g": 28.0, "fat_g": 0.1, "fiber_g": 0.3, "sugar_g": 22.0, "sodium_mg": 1040.0, "default_unit": "gram", "default_serving_g": 15.0, "source": "curated"},
    {"food_id": "food_615", "name_he": "רוטב ברביקיו", "name_en": "BBQ Sauce", "category": "condiments", "calories_kcal": 172, "protein_g": 1.2, "carbs_g": 40.6, "fat_g": 0.5, "fiber_g": 0.5, "sugar_g": 31.0, "sodium_mg": 838.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_616", "name_he": "רוטב סויה", "name_en": "Soy Sauce", "category": "condiments", "calories_kcal": 53, "protein_g": 8.1, "carbs_g": 4.9, "fat_g": 0.1, "fiber_g": 0.0, "sugar_g": 1.7, "sodium_mg": 5493.0, "default_unit": "gram", "default_serving_g": 15.0, "source": "curated"},
    {"food_id": "food_617", "name_he": "רוטב טריאקי", "name_en": "Teriyaki Sauce", "category": "condiments", "calories_kcal": 89, "protein_g": 5.2, "carbs_g": 17.0, "fat_g": 0.0, "fiber_g": 0.1, "sugar_g": 12.0, "sodium_mg": 2438.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_618", "name_he": "חומוס", "name_en": "Hummus", "category": "condiments", "calories_kcal": 177, "protein_g": 8.0, "carbs_g": 14.3, "fat_g": 9.6, "fiber_g": 6.0, "sugar_g": 0.0, "sodium_mg": 379.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_619", "name_he": "גואקמולה", "name_en": "Guacamole", "category": "condiments", "calories_kcal": 155, "protein_g": 2.0, "carbs_g": 8.8, "fat_g": 13.5, "fiber_g": 6.5, "sugar_g": 0.9, "sodium_mg": 358.0, "default_unit": "gram", "default_serving_g": 50.0, "source": "curated"},
    {"food_id": "food_620", "name_he": "סלסה", "name_en": "Tomato Salsa", "category": "condiments", "calories_kcal": 36, "protein_g": 1.8, "carbs_g": 7.1, "fat_g": 0.4, "fiber_g": 1.7, "sugar_g": 3.5, "sodium_mg": 568.0, "default_unit": "gram", "default_serving_g": 60.0, "source": "curated"},

    # === NUTS & SEEDS ===
    {"food_id": "food_621", "name_he": "אגוזי לוז", "name_en": "Hazelnuts", "category": "nuts", "calories_kcal": 628, "protein_g": 15.0, "carbs_g": 16.7, "fat_g": 60.8, "fiber_g": 9.7, "sugar_g": 4.3, "sodium_mg": 0.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_622", "name_he": "אגוזי פקאן", "name_en": "Pecans", "category": "nuts", "calories_kcal": 691, "protein_g": 9.2, "carbs_g": 14.0, "fat_g": 72.0, "fiber_g": 9.6, "sugar_g": 3.97, "sodium_mg": 0.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_623", "name_he": "פיסטוקים", "name_en": "Pistachios", "category": "nuts", "calories_kcal": 562, "protein_g": 20.2, "carbs_g": 27.5, "fat_g": 45.3, "fiber_g": 10.3, "sugar_g": 7.7, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_624", "name_he": "גרעיני דלעת", "name_en": "Pumpkin Seeds", "category": "nuts", "calories_kcal": 559, "protein_g": 30.2, "carbs_g": 10.7, "fat_g": 49.0, "fiber_g": 6.0, "sugar_g": 1.4, "sodium_mg": 7.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_625", "name_he": "גרעיני חמנייה", "name_en": "Sunflower Seeds", "category": "nuts", "calories_kcal": 584, "protein_g": 20.8, "carbs_g": 20.0, "fat_g": 51.5, "fiber_g": 8.6, "sugar_g": 2.6, "sodium_mg": 9.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_626", "name_he": "זרעי קיה", "name_en": "Chia Seeds", "category": "nuts", "calories_kcal": 486, "protein_g": 16.5, "carbs_g": 42.1, "fat_g": 30.7, "fiber_g": 34.4, "sugar_g": 0.0, "sodium_mg": 16.0, "default_unit": "gram", "default_serving_g": 15.0, "source": "curated"},
    {"food_id": "food_627", "name_he": "זרעי פשתן", "name_en": "Flaxseeds", "category": "nuts", "calories_kcal": 534, "protein_g": 18.3, "carbs_g": 28.9, "fat_g": 42.2, "fiber_g": 27.3, "sugar_g": 1.5, "sodium_mg": 30.0, "default_unit": "gram", "default_serving_g": 15.0, "source": "curated"},

    # === BREAKFAST FOODS ===
    {"food_id": "food_628", "name_he": "פנקייק", "name_en": "Pancake", "category": "grains", "calories_kcal": 227, "protein_g": 5.9, "carbs_g": 32.0, "fat_g": 9.2, "fiber_g": 0.9, "sugar_g": 6.1, "sodium_mg": 478.0, "default_unit": "unit", "default_serving_g": 90.0, "source": "curated"},
    {"food_id": "food_629", "name_he": "וופל", "name_en": "Waffle", "category": "grains", "calories_kcal": 291, "protein_g": 7.9, "carbs_g": 37.0, "fat_g": 12.3, "fiber_g": 1.2, "sugar_g": 5.9, "sodium_mg": 520.0, "default_unit": "unit", "default_serving_g": 75.0, "source": "curated"},
    {"food_id": "food_630", "name_he": "ביצים מקושקשות", "name_en": "Scrambled Eggs", "category": "protein", "calories_kcal": 148, "protein_g": 10.1, "carbs_g": 1.6, "fat_g": 11.3, "fiber_g": 0.0, "sugar_g": 1.4, "sodium_mg": 270.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_631", "name_he": "אומלט", "name_en": "Omelette", "category": "protein", "calories_kcal": 154, "protein_g": 10.6, "carbs_g": 0.4, "fat_g": 12.3, "fiber_g": 0.0, "sugar_g": 0.3, "sodium_mg": 342.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_632", "name_he": "טוסט עם חמאה", "name_en": "Buttered Toast", "category": "grains", "calories_kcal": 313, "protein_g": 7.6, "carbs_g": 38.0, "fat_g": 14.5, "fiber_g": 2.2, "sugar_g": 3.0, "sodium_mg": 540.0, "default_unit": "gram", "default_serving_g": 60.0, "source": "curated"},
    {"food_id": "food_633", "name_he": "בייגל", "name_en": "Plain Bagel", "category": "grains", "calories_kcal": 245, "protein_g": 9.5, "carbs_g": 47.9, "fat_g": 1.5, "fiber_g": 2.0, "sugar_g": 5.0, "sodium_mg": 422.0, "default_unit": "unit", "default_serving_g": 98.0, "source": "curated"},
    {"food_id": "food_634", "name_he": "שייק חלבון ווניל", "name_en": "Vanilla Protein Shake", "category": "beverages", "calories_kcal": 160, "protein_g": 25.0, "carbs_g": 8.0, "fat_g": 3.5, "fiber_g": 1.0, "sugar_g": 4.0, "sodium_mg": 200.0, "default_unit": "gram", "default_serving_g": 300.0, "source": "curated"},

    # === BEVERAGES ===
    {"food_id": "food_635", "name_he": "מיץ תפוזים טרי", "name_en": "Fresh Orange Juice", "category": "beverages", "calories_kcal": 45, "protein_g": 0.7, "carbs_g": 10.4, "fat_g": 0.2, "fiber_g": 0.2, "sugar_g": 8.4, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_636", "name_he": "מיץ תפוחים", "name_en": "Apple Juice", "category": "beverages", "calories_kcal": 46, "protein_g": 0.1, "carbs_g": 11.3, "fat_g": 0.1, "fiber_g": 0.2, "sugar_g": 9.6, "sodium_mg": 4.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_637", "name_he": "חלב סויה", "name_en": "Soy Milk", "category": "beverages", "calories_kcal": 42, "protein_g": 3.3, "carbs_g": 3.0, "fat_g": 1.8, "fiber_g": 0.4, "sugar_g": 2.6, "sodium_mg": 40.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_638", "name_he": "חלב שקדים", "name_en": "Almond Milk Unsweetened", "category": "beverages", "calories_kcal": 15, "protein_g": 0.6, "carbs_g": 0.3, "fat_g": 1.2, "fiber_g": 0.3, "sugar_g": 0.0, "sodium_mg": 72.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_639", "name_he": "קפה שחור", "name_en": "Black Coffee", "category": "beverages", "calories_kcal": 2, "protein_g": 0.3, "carbs_g": 0.0, "fat_g": 0.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 5.0, "default_unit": "gram", "default_serving_g": 240.0, "source": "curated"},
    {"food_id": "food_640", "name_he": "קפה לאטה", "name_en": "Latte Coffee", "category": "beverages", "calories_kcal": 67, "protein_g": 3.4, "carbs_g": 6.4, "fat_g": 2.9, "fiber_g": 0.0, "sugar_g": 6.0, "sodium_mg": 58.0, "default_unit": "gram", "default_serving_g": 350.0, "source": "curated"},
    {"food_id": "food_641", "name_he": "תה ירוק", "name_en": "Green Tea", "category": "beverages", "calories_kcal": 1, "protein_g": 0.2, "carbs_g": 0.0, "fat_g": 0.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 1.0, "default_unit": "gram", "default_serving_g": 240.0, "source": "curated"},
    {"food_id": "food_642", "name_he": "שוקו חם", "name_en": "Hot Cocoa", "category": "beverages", "calories_kcal": 76, "protein_g": 3.2, "carbs_g": 13.7, "fat_g": 1.4, "fiber_g": 1.3, "sugar_g": 10.0, "sodium_mg": 136.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_643", "name_he": "לאסי יוגורט", "name_en": "Mango Lassi", "category": "beverages", "calories_kcal": 100, "protein_g": 2.7, "carbs_g": 18.0, "fat_g": 2.5, "fiber_g": 0.5, "sugar_g": 16.0, "sodium_mg": 50.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_644", "name_he": "מיץ גזר טרי", "name_en": "Fresh Carrot Juice", "category": "beverages", "calories_kcal": 40, "protein_g": 0.9, "carbs_g": 9.3, "fat_g": 0.2, "fiber_g": 0.7, "sugar_g": 4.0, "sodium_mg": 69.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},

    # === DESSERTS & SWEETS ===
    {"food_id": "food_645", "name_he": "עוגת שוקולד", "name_en": "Chocolate Cake", "category": "sweets", "calories_kcal": 371, "protein_g": 4.7, "carbs_g": 51.0, "fat_g": 16.7, "fiber_g": 2.0, "sugar_g": 33.0, "sodium_mg": 252.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_646", "name_he": "ביסקוויטי שוקולד", "name_en": "Chocolate Chip Cookies", "category": "sweets", "calories_kcal": 488, "protein_g": 5.8, "carbs_g": 64.0, "fat_g": 23.0, "fiber_g": 2.4, "sugar_g": 38.0, "sodium_mg": 291.0, "default_unit": "unit", "default_serving_g": 25.0, "source": "curated"},
    {"food_id": "food_647", "name_he": "ברווני שוקולד", "name_en": "Brownie", "category": "sweets", "calories_kcal": 412, "protein_g": 5.0, "carbs_g": 57.0, "fat_g": 19.0, "fiber_g": 2.0, "sugar_g": 40.0, "sodium_mg": 171.0, "default_unit": "gram", "default_serving_g": 50.0, "source": "curated"},
    {"food_id": "food_648", "name_he": "גלידת וניל", "name_en": "Vanilla Ice Cream", "category": "sweets", "calories_kcal": 207, "protein_g": 3.5, "carbs_g": 23.6, "fat_g": 11.0, "fiber_g": 0.0, "sugar_g": 21.2, "sodium_mg": 80.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_649", "name_he": "גלידת שוקולד", "name_en": "Chocolate Ice Cream", "category": "sweets", "calories_kcal": 216, "protein_g": 3.8, "carbs_g": 28.0, "fat_g": 11.0, "fiber_g": 0.5, "sugar_g": 24.0, "sodium_mg": 71.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_650", "name_he": "יוגורט קפוא", "name_en": "Frozen Yogurt", "category": "sweets", "calories_kcal": 127, "protein_g": 3.0, "carbs_g": 22.0, "fat_g": 3.3, "fiber_g": 0.0, "sugar_g": 21.0, "sodium_mg": 68.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
]
