"""
Extended food library — universal foods (Western, Asian, fast food, etc.)
IDs: food_111 onward. All values per 100g unless noted.
"""
from typing import Dict, List

EXTENDED_FOODS: List[Dict] = [

    # ── BEEF ──────────────────────────────────────────────────────────────────
    {"food_id":"food_111","name_he":"סטייק ריב-איי","name_en":"Ribeye Steak",
     "category":"protein","calories_kcal":291.0,"protein_g":24.0,"carbs_g":0.0,"fat_g":21.0,
     "default_serving_g":200.0,"aliases_he":["ריב איי","סטייק"],"aliases_en":["ribeye","rib eye steak"],"source":"curated"},
    {"food_id":"food_112","name_he":"סטייק סירלוין","name_en":"Sirloin Steak",
     "category":"protein","calories_kcal":207.0,"protein_g":26.0,"carbs_g":0.0,"fat_g":11.0,
     "default_serving_g":200.0,"aliases_he":["סירלויין","פילה בקר"],"aliases_en":["sirloin","NY strip"],"source":"curated"},
    {"food_id":"food_113","name_he":"בשר טחון 80/20","name_en":"Ground Beef 80/20",
     "category":"protein","calories_kcal":254.0,"protein_g":17.0,"carbs_g":0.0,"fat_g":20.0,
     "default_serving_g":150.0,"aliases_he":["בקר טחון","קציצות בקר"],"aliases_en":["minced beef","ground chuck"],"source":"curated"},
    {"food_id":"food_114","name_he":"צלעות בקר","name_en":"Beef Ribs",
     "category":"protein","calories_kcal":291.0,"protein_g":19.0,"carbs_g":0.0,"fat_g":23.0,
     "default_serving_g":200.0,"aliases_he":["ריבס"],"aliases_en":["beef short ribs","bbq ribs"],"source":"curated"},
    {"food_id":"food_115","name_he":"טנדרלוין בקר","name_en":"Beef Tenderloin",
     "category":"protein","calories_kcal":179.0,"protein_g":28.0,"carbs_g":0.0,"fat_g":7.0,
     "default_serving_g":180.0,"aliases_he":["פילה מיניון"],"aliases_en":["filet mignon","beef fillet"],"source":"curated"},

    # ── PORK ──────────────────────────────────────────────────────────────────
    {"food_id":"food_116","name_he":"צלע חזיר","name_en":"Pork Chop",
     "category":"protein","calories_kcal":231.0,"protein_g":26.0,"carbs_g":0.0,"fat_g":14.0,
     "default_serving_g":150.0,"aliases_he":["חזיר"],"aliases_en":["pork loin chop"],"source":"curated"},
    {"food_id":"food_117","name_he":"בייקון","name_en":"Bacon",
     "category":"protein","calories_kcal":541.0,"protein_g":37.0,"carbs_g":1.4,"fat_g":42.0,
     "default_unit":"slice","default_serving_g":15.0,"aliases_he":["חזיר מעושן"],"aliases_en":["streaky bacon","smoked bacon"],"source":"curated"},
    {"food_id":"food_118","name_he":"נקניק חזיר","name_en":"Pork Sausage",
     "category":"protein","calories_kcal":339.0,"protein_g":14.0,"carbs_g":3.0,"fat_g":30.0,
     "default_unit":"unit","default_serving_g":80.0,"aliases_he":["סוסייג"],"aliases_en":["bratwurst","pork link sausage"],"source":"curated"},
    {"food_id":"food_119","name_he":"הוט דוג","name_en":"Hot Dog",
     "category":"protein","calories_kcal":290.0,"protein_g":12.0,"carbs_g":2.0,"fat_g":26.0,
     "default_unit":"unit","default_serving_g":45.0,"aliases_he":["נקניקייה","נקניקיות"],"aliases_en":["frankfurter","wiener"],"source":"curated"},
    {"food_id":"food_120","name_he":"שינקן","name_en":"Ham",
     "category":"protein","calories_kcal":145.0,"protein_g":21.0,"carbs_g":1.5,"fat_g":6.0,
     "default_serving_g":80.0,"aliases_he":["חמין","שינקן מעושן"],"aliases_en":["deli ham","sliced ham"],"source":"curated"},

    # ── PROCESSED MEATS ───────────────────────────────────────────────────────
    {"food_id":"food_121","name_he":"סלמי","name_en":"Salami",
     "category":"protein","calories_kcal":425.0,"protein_g":23.0,"carbs_g":1.0,"fat_g":36.0,
     "default_unit":"slice","default_serving_g":10.0,"aliases_he":["סלמי איטלקי"],"aliases_en":["italian salami","hard salami"],"source":"curated"},
    {"food_id":"food_122","name_he":"פפרוני","name_en":"Pepperoni",
     "category":"protein","calories_kcal":504.0,"protein_g":21.0,"carbs_g":1.3,"fat_g":45.0,
     "default_unit":"slice","default_serving_g":10.0,"aliases_he":["פיצה פפרוני"],"aliases_en":["pizza pepperoni"],"source":"curated"},
    {"food_id":"food_123","name_he":"קוריזו","name_en":"Chorizo",
     "category":"protein","calories_kcal":455.0,"protein_g":25.0,"carbs_g":2.0,"fat_g":38.0,
     "default_serving_g":60.0,"aliases_he":["נקניק ספרדי"],"aliases_en":["spanish chorizo","mexican chorizo"],"source":"curated"},
    {"food_id":"food_124","name_he":"פרושוטו","name_en":"Prosciutto",
     "category":"protein","calories_kcal":215.0,"protein_g":26.0,"carbs_g":0.3,"fat_g":12.0,
     "default_unit":"slice","default_serving_g":15.0,"aliases_he":["פרוסוטו","שינקן איטלקי"],"aliases_en":["parma ham","cured ham"],"source":"curated"},

    # ── POULTRY (extended) ────────────────────────────────────────────────────
    {"food_id":"food_125","name_he":"ירך עוף","name_en":"Chicken Thigh",
     "category":"protein","calories_kcal":209.0,"protein_g":26.0,"carbs_g":0.0,"fat_g":11.0,
     "default_serving_g":120.0,"aliases_he":["עוף ירך","ירכיים"],"aliases_en":["chicken thigh boneless","dark meat chicken"],"source":"curated"},
    {"food_id":"food_126","name_he":"כנפי עוף","name_en":"Chicken Wings",
     "category":"protein","calories_kcal":203.0,"protein_g":30.0,"carbs_g":0.0,"fat_g":8.0,
     "default_unit":"unit","default_serving_g":40.0,"aliases_he":["כנפיים","כנפי בופלו"],"aliases_en":["buffalo wings","chicken wingettes"],"source":"curated"},
    {"food_id":"food_127","name_he":"חזה ברווז","name_en":"Duck Breast",
     "category":"protein","calories_kcal":201.0,"protein_g":28.0,"carbs_g":0.0,"fat_g":9.7,
     "default_serving_g":150.0,"aliases_he":["ברווז"],"aliases_en":["duck","magret de canard"],"source":"curated"},
    {"food_id":"food_128","name_he":"כרעי עוף","name_en":"Chicken Drumstick",
     "category":"protein","calories_kcal":172.0,"protein_g":28.0,"carbs_g":0.0,"fat_g":6.0,
     "default_unit":"unit","default_serving_g":80.0,"aliases_he":["שוקי עוף"],"aliases_en":["drumstick","leg quarter"],"source":"curated"},

    # ── FISH & SEAFOOD (extended) ─────────────────────────────────────────────
    {"food_id":"food_129","name_he":"טילאפיה","name_en":"Tilapia",
     "category":"protein","calories_kcal":96.0,"protein_g":20.0,"carbs_g":0.0,"fat_g":2.1,
     "default_serving_g":150.0,"aliases_he":["דג ניל","פילה לבן"],"aliases_en":["tilapia fillet","white fish fillet"],"source":"curated"},
    {"food_id":"food_130","name_he":"פורל","name_en":"Trout",
     "category":"protein","calories_kcal":190.0,"protein_g":26.0,"carbs_g":0.0,"fat_g":9.0,
     "default_serving_g":150.0,"aliases_he":["פורל קשת","פורל נחל"],"aliases_en":["rainbow trout","brook trout"],"source":"curated"},
    {"food_id":"food_131","name_he":"מקרל","name_en":"Mackerel",
     "category":"protein","calories_kcal":205.0,"protein_g":19.0,"carbs_g":0.0,"fat_g":14.0,
     "default_serving_g":100.0,"aliases_he":["סקומבריה"],"aliases_en":["atlantic mackerel","canned mackerel"],"source":"curated"},
    {"food_id":"food_132","name_he":"הרינג","name_en":"Herring",
     "category":"protein","calories_kcal":158.0,"protein_g":18.0,"carbs_g":0.0,"fat_g":9.0,
     "default_serving_g":100.0,"aliases_he":["מטיאס","דג מלוח"],"aliases_en":["pickled herring","matjes"],"source":"curated"},
    {"food_id":"food_133","name_he":"אנשובי","name_en":"Anchovy",
     "category":"protein","calories_kcal":210.0,"protein_g":29.0,"carbs_g":0.0,"fat_g":10.0,
     "default_serving_g":20.0,"aliases_he":["אנצ'ובי"],"aliases_en":["anchovies","canned anchovies"],"source":"curated"},
    {"food_id":"food_134","name_he":"סרטן ים","name_en":"Crab",
     "category":"protein","calories_kcal":87.0,"protein_g":18.0,"carbs_g":0.0,"fat_g":1.5,
     "default_serving_g":100.0,"aliases_he":["קרב"],"aliases_en":["crab meat","blue crab"],"source":"curated"},
    {"food_id":"food_135","name_he":"שרימפס מבושל","name_en":"Cooked Shrimp",
     "category":"protein","calories_kcal":99.0,"protein_g":24.0,"carbs_g":0.0,"fat_g":0.3,
     "default_serving_g":100.0,"aliases_he":["קריל מבושל"],"aliases_en":["boiled shrimp","cooked prawns"],"source":"curated"},
    {"food_id":"food_136","name_he":"קלמרי","name_en":"Calamari",
     "category":"protein","calories_kcal":92.0,"protein_g":16.0,"carbs_g":3.0,"fat_g":1.4,
     "default_serving_g":100.0,"aliases_he":["דיונון","קלמארי"],"aliases_en":["squid","fried calamari"],"source":"curated"},
    {"food_id":"food_137","name_he":"סלמון מעושן","name_en":"Smoked Salmon",
     "category":"protein","calories_kcal":117.0,"protein_g":18.0,"carbs_g":0.0,"fat_g":4.7,
     "default_serving_g":80.0,"aliases_he":["לוקס"],"aliases_en":["lox","nova salmon"],"source":"curated"},
    {"food_id":"food_138","name_he":"הליבוט","name_en":"Halibut",
     "category":"protein","calories_kcal":111.0,"protein_g":23.0,"carbs_g":0.0,"fat_g":2.3,
     "default_serving_g":150.0,"aliases_he":["פלנדר","דג פלנדר"],"aliases_en":["halibut fillet","pacific halibut"],"source":"curated"},

    # ── PLANT PROTEINS ────────────────────────────────────────────────────────
    {"food_id":"food_139","name_he":"טמפה","name_en":"Tempeh",
     "category":"protein","calories_kcal":195.0,"protein_g":19.0,"carbs_g":9.4,"fat_g":11.0,
     "fiber_g":9.0,"default_serving_g":100.0,"aliases_he":["תמפה"],"aliases_en":["fermented soy","tempeh block"],"source":"curated"},
    {"food_id":"food_140","name_he":"סייטן","name_en":"Seitan",
     "category":"protein","calories_kcal":168.0,"protein_g":25.0,"carbs_g":14.0,"fat_g":1.9,
     "default_serving_g":100.0,"aliases_he":["גלוטן חיטה","בשר חיטה"],"aliases_en":["wheat gluten","wheat meat"],"source":"curated"},
    {"food_id":"food_141","name_he":"אבקת חלבון מי גבינה","name_en":"Whey Protein Powder",
     "category":"protein","calories_kcal":352.0,"protein_g":75.0,"carbs_g":8.0,"fat_g":3.0,
     "default_serving_g":30.0,"aliases_he":["ווי פרוטאין","שייק חלבון"],"aliases_en":["whey protein","protein powder"],"source":"curated"},
    {"food_id":"food_142","name_he":"טופו משי","name_en":"Silken Tofu",
     "category":"protein","calories_kcal":55.0,"protein_g":4.8,"carbs_g":2.3,"fat_g":2.5,
     "default_serving_g":100.0,"aliases_he":["טופו רך"],"aliases_en":["soft tofu","silky tofu"],"source":"curated"},
    {"food_id":"food_143","name_he":"כבד עוף","name_en":"Chicken Liver",
     "category":"protein","calories_kcal":175.0,"protein_g":27.0,"carbs_g":1.0,"fat_g":6.0,
     "default_serving_g":100.0,"aliases_he":["כבדי עוף"],"aliases_en":["chicken livers","chopped liver"],"source":"curated"},

    # ── DAIRY – CHEESES ───────────────────────────────────────────────────────
    {"food_id":"food_144","name_he":"גבינת צ'דר","name_en":"Cheddar Cheese",
     "category":"dairy","calories_kcal":403.0,"protein_g":25.0,"carbs_g":1.3,"fat_g":33.0,
     "default_unit":"slice","default_serving_g":20.0,"aliases_he":["צ'דר","גבינה אנגלית"],"aliases_en":["cheddar","sharp cheddar"],"source":"curated"},
    {"food_id":"food_145","name_he":"גבינת פרמזן","name_en":"Parmesan Cheese",
     "category":"dairy","calories_kcal":431.0,"protein_g":38.0,"carbs_g":4.0,"fat_g":29.0,
     "default_unit":"tablespoon","default_serving_g":10.0,"aliases_he":["פרמזן","גרנה פדנו"],"aliases_en":["parmigiano","grated parmesan"],"source":"curated"},
    {"food_id":"food_146","name_he":"גבינת גאודה","name_en":"Gouda Cheese",
     "category":"dairy","calories_kcal":356.0,"protein_g":25.0,"carbs_g":2.2,"fat_g":28.0,
     "default_unit":"slice","default_serving_g":20.0,"aliases_he":["גאודה"],"aliases_en":["gouda","aged gouda"],"source":"curated"},
    {"food_id":"food_147","name_he":"גבינת בְּרִי","name_en":"Brie Cheese",
     "category":"dairy","calories_kcal":334.0,"protein_g":21.0,"carbs_g":0.5,"fat_g":28.0,
     "default_serving_g":30.0,"aliases_he":["ברי"],"aliases_en":["brie","camembert"],"source":"curated"},
    {"food_id":"food_148","name_he":"גבינה כחולה","name_en":"Blue Cheese",
     "category":"dairy","calories_kcal":353.0,"protein_g":21.0,"carbs_g":2.3,"fat_g":29.0,
     "default_serving_g":30.0,"aliases_he":["גורגונזולה","רוקפור"],"aliases_en":["gorgonzola","roquefort","stilton"],"source":"curated"},
    {"food_id":"food_149","name_he":"גבינת שמנת","name_en":"Cream Cheese",
     "category":"dairy","calories_kcal":342.0,"protein_g":6.0,"carbs_g":4.1,"fat_g":34.0,
     "default_unit":"tablespoon","default_serving_g":30.0,"aliases_he":["פילדלפיה","ממרח גבינה"],"aliases_en":["philadelphia","soft cheese spread"],"source":"curated"},
    {"food_id":"food_150","name_he":"ריקוטה","name_en":"Ricotta",
     "category":"dairy","calories_kcal":174.0,"protein_g":11.0,"carbs_g":3.0,"fat_g":13.0,
     "default_serving_g":100.0,"aliases_he":["גבינת ריקוטה"],"aliases_en":["ricotta cheese","whey cheese"],"source":"curated"},
    {"food_id":"food_151","name_he":"גבינת שוויצרית","name_en":"Swiss Cheese",
     "category":"dairy","calories_kcal":380.0,"protein_g":27.0,"carbs_g":5.4,"fat_g":28.0,
     "default_unit":"slice","default_serving_g":20.0,"aliases_he":["אמנטל","גרוייר"],"aliases_en":["emmental","gruyere","swiss"],"source":"curated"},
    {"food_id":"food_152","name_he":"מסקרפונה","name_en":"Mascarpone",
     "category":"dairy","calories_kcal":429.0,"protein_g":4.6,"carbs_g":5.8,"fat_g":44.0,
     "default_unit":"tablespoon","default_serving_g":30.0,"aliases_he":["גבינת מסקרפונה","קרם מסקרפונה"],"aliases_en":["mascarpone cheese","italian cream cheese"],"source":"curated"},
    {"food_id":"food_153","name_he":"חלב מלא","name_en":"Whole Milk",
     "category":"dairy","calories_kcal":61.0,"protein_g":3.2,"carbs_g":4.8,"fat_g":3.3,
     "default_unit":"cup","default_serving_g":250.0,"aliases_he":["חלב 3%","חלב שמן"],"aliases_en":["full fat milk","3% milk"],"source":"curated"},
    {"food_id":"food_154","name_he":"חלב דל שומן","name_en":"Skim Milk",
     "category":"dairy","calories_kcal":35.0,"protein_g":3.4,"carbs_g":5.0,"fat_g":0.2,
     "default_unit":"cup","default_serving_g":250.0,"aliases_he":["חלב 0%","חלב מוחלב"],"aliases_en":["nonfat milk","fat free milk"],"source":"curated"},
    {"food_id":"food_155","name_he":"שמנת לבישול","name_en":"Heavy Cream",
     "category":"dairy","calories_kcal":345.0,"protein_g":2.8,"carbs_g":2.8,"fat_g":37.0,
     "default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["שמנת לבישול 38%","קרם"],"aliases_en":["heavy whipping cream","double cream"],"source":"curated"},
    {"food_id":"food_156","name_he":"גלידת וניל","name_en":"Vanilla Ice Cream",
     "category":"dairy","calories_kcal":207.0,"protein_g":3.5,"carbs_g":24.0,"fat_g":11.0,
     "default_serving_g":100.0,"aliases_he":["גלידה","גלידה לבנה"],"aliases_en":["ice cream","soft serve vanilla"],"source":"curated"},

    # ── GRAINS – BREADS & PASTA ───────────────────────────────────────────────
    {"food_id":"food_157","name_he":"לחם לבן","name_en":"White Bread",
     "category":"grain","calories_kcal":266.0,"protein_g":9.0,"carbs_g":50.0,"fat_g":3.2,
     "fiber_g":2.3,"default_unit":"slice","default_serving_g":30.0,"aliases_he":["לחם רגיל","לחם טוסט"],"aliases_en":["white sandwich bread","toast bread"],"source":"curated"},
    {"food_id":"food_158","name_he":"לחם שיפון","name_en":"Rye Bread",
     "category":"grain","calories_kcal":259.0,"protein_g":9.0,"carbs_g":48.0,"fat_g":3.3,
     "fiber_g":6.2,"default_unit":"slice","default_serving_g":30.0,"aliases_he":["לחם שחור","פומפרניקל"],"aliases_en":["dark rye","pumpernickel"],"source":"curated"},
    {"food_id":"food_159","name_he":"לחם מחמצת","name_en":"Sourdough Bread",
     "category":"grain","calories_kcal":274.0,"protein_g":9.0,"carbs_g":52.0,"fat_g":1.5,
     "fiber_g":2.4,"default_unit":"slice","default_serving_g":40.0,"aliases_he":["לחם סאורדו","לחם על בסיס מחמצת"],"aliases_en":["sourdough","levain bread"],"source":"curated"},
    {"food_id":"food_160","name_he":"בייגל","name_en":"Bagel",
     "category":"grain","calories_kcal":250.0,"protein_g":10.0,"carbs_g":48.0,"fat_g":1.5,
     "fiber_g":2.1,"default_unit":"unit","default_serving_g":100.0,"aliases_he":["בייגל שומשום","בייגל רגיל"],"aliases_en":["plain bagel","sesame bagel"],"source":"curated"},
    {"food_id":"food_161","name_he":"קרואסון","name_en":"Croissant",
     "category":"grain","calories_kcal":406.0,"protein_g":8.2,"carbs_g":46.0,"fat_g":21.0,
     "fiber_g":2.0,"default_unit":"unit","default_serving_g":60.0,"aliases_he":["קרוסון","מאפה צרפתי"],"aliases_en":["butter croissant","french pastry"],"source":"curated"},
    {"food_id":"food_162","name_he":"טורטייה קמח","name_en":"Flour Tortilla",
     "category":"grain","calories_kcal":313.0,"protein_g":8.0,"carbs_g":53.0,"fat_g":7.0,
     "fiber_g":2.4,"default_unit":"unit","default_serving_g":45.0,"aliases_he":["לאפה","טורטיה"],"aliases_en":["soft tortilla","wrap"],"source":"curated"},
    {"food_id":"food_163","name_he":"טורטייה תירס","name_en":"Corn Tortilla",
     "category":"grain","calories_kcal":218.0,"protein_g":6.0,"carbs_g":46.0,"fat_g":2.5,
     "fiber_g":6.3,"default_unit":"unit","default_serving_g":30.0,"aliases_he":["לאפה תירס","טאקו"],"aliases_en":["corn wrap","taco shell"],"source":"curated"},
    {"food_id":"food_164","name_he":"נאן","name_en":"Naan Bread",
     "category":"grain","calories_kcal":317.0,"protein_g":9.0,"carbs_g":55.0,"fat_g":7.3,
     "fiber_g":1.9,"default_unit":"unit","default_serving_g":90.0,"aliases_he":["לחם הודי","נאן חמאה"],"aliases_en":["indian bread","butter naan"],"source":"curated"},
    {"food_id":"food_165","name_he":"אנגליש מאפין","name_en":"English Muffin",
     "category":"grain","calories_kcal":227.0,"protein_g":8.0,"carbs_g":44.0,"fat_g":2.0,
     "fiber_g":2.6,"default_unit":"unit","default_serving_g":57.0,"aliases_he":["מאפין אנגלי"],"aliases_en":["toasted english muffin"],"source":"curated"},
    {"food_id":"food_166","name_he":"פסטה לבנה מבושלת","name_en":"White Pasta Cooked",
     "category":"grain","calories_kcal":158.0,"protein_g":5.8,"carbs_g":31.0,"fat_g":0.9,
     "fiber_g":1.8,"default_serving_g":180.0,"aliases_he":["ספגטי","פסטה רגילה","מקרוני מבושל"],"aliases_en":["spaghetti cooked","penne cooked","fettuccine"],"source":"curated"},
    {"food_id":"food_167","name_he":"אטריות ביצה מבושלות","name_en":"Egg Noodles Cooked",
     "category":"grain","calories_kcal":138.0,"protein_g":4.8,"carbs_g":26.0,"fat_g":2.0,
     "fiber_g":1.4,"default_serving_g":160.0,"aliases_he":["נודלס","מיין"],"aliases_en":["egg noodles","chinese noodles"],"source":"curated"},
    {"food_id":"food_168","name_he":"אטריות אורז מבושלות","name_en":"Rice Noodles Cooked",
     "category":"grain","calories_kcal":109.0,"protein_g":0.9,"carbs_g":24.0,"fat_g":0.2,
     "fiber_g":0.9,"default_serving_g":160.0,"aliases_he":["אטריות תאילנדיות","אטריות מאורז"],"aliases_en":["vermicelli","pad thai noodles"],"source":"curated"},
    {"food_id":"food_169","name_he":"אורז יסמין מבושל","name_en":"Jasmine Rice Cooked",
     "category":"grain","calories_kcal":130.0,"protein_g":2.7,"carbs_g":28.0,"fat_g":0.3,
     "fiber_g":0.3,"default_serving_g":150.0,"aliases_he":["אורז תאילנדי","אורז ריחני"],"aliases_en":["jasmine rice","thai rice"],"source":"curated"},
    {"food_id":"food_170","name_he":"אורז בסמטי מבושל","name_en":"Basmati Rice Cooked",
     "category":"grain","calories_kcal":130.0,"protein_g":3.5,"carbs_g":26.0,"fat_g":0.4,
     "fiber_g":0.4,"default_serving_g":150.0,"aliases_he":["אורז הודי","אורז ארוך"],"aliases_en":["long grain rice","indian rice"],"source":"curated"},
    {"food_id":"food_171","name_he":"פולנטה מבושלת","name_en":"Polenta Cooked",
     "category":"grain","calories_kcal":70.0,"protein_g":1.7,"carbs_g":14.0,"fat_g":0.7,
     "fiber_g":1.2,"default_serving_g":200.0,"aliases_he":["קורנמיל","גריסים תירס"],"aliases_en":["cornmeal mush","grits"],"source":"curated"},
    {"food_id":"food_172","name_he":"קורנפלקס","name_en":"Cornflakes",
     "category":"grain","calories_kcal":357.0,"protein_g":7.0,"carbs_g":84.0,"fat_g":0.4,
     "fiber_g":2.7,"default_serving_g":40.0,"aliases_he":["קורן פלקס","דגני בוקר"],"aliases_en":["corn flakes","breakfast cereal"],"source":"curated"},
    {"food_id":"food_173","name_he":"מוזלי","name_en":"Muesli",
     "category":"grain","calories_kcal":367.0,"protein_g":10.0,"carbs_g":66.0,"fat_g":7.0,
     "fiber_g":7.5,"default_serving_g":50.0,"aliases_he":["מוזלי שוויצרי","דגני בוקר עם פירות"],"aliases_en":["swiss muesli","bircher muesli"],"source":"curated"},
    {"food_id":"food_174","name_he":"אבקת קמח לבן","name_en":"All-Purpose Flour",
     "category":"grain","calories_kcal":364.0,"protein_g":10.0,"carbs_g":76.0,"fat_g":1.0,
     "fiber_g":2.7,"default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["קמח","קמח חיטה"],"aliases_en":["wheat flour","plain flour"],"source":"curated"},

    # ── VEGETABLES (universal) ────────────────────────────────────────────────
    {"food_id":"food_175","name_he":"כרישה","name_en":"Leek",
     "category":"vegetable","calories_kcal":61.0,"protein_g":1.5,"carbs_g":14.0,"fat_g":0.3,
     "fiber_g":1.8,"default_serving_g":100.0,"aliases_he":["כרישות"],"aliases_en":["leeks","wild leek"],"source":"curated"},
    {"food_id":"food_176","name_he":"סלרי","name_en":"Celery",
     "category":"vegetable","calories_kcal":16.0,"protein_g":0.7,"carbs_g":3.0,"fat_g":0.2,
     "fiber_g":1.6,"default_unit":"unit","default_serving_g":40.0,"aliases_he":["סלרי מקל","עלי סלרי"],"aliases_en":["celery stalk","celery ribs"],"source":"curated"},
    {"food_id":"food_177","name_he":"כרוב ניצנים","name_en":"Brussels Sprouts",
     "category":"vegetable","calories_kcal":43.0,"protein_g":3.4,"carbs_g":9.0,"fat_g":0.3,
     "fiber_g":3.8,"default_serving_g":100.0,"aliases_he":["ניצני בריסל"],"aliases_en":["brussel sprouts"],"source":"curated"},
    {"food_id":"food_178","name_he":"ארטישוק","name_en":"Artichoke",
     "category":"vegetable","calories_kcal":47.0,"protein_g":3.3,"carbs_g":11.0,"fat_g":0.2,
     "fiber_g":5.4,"default_unit":"unit","default_serving_g":150.0,"aliases_he":["ארחישוק","לב ארטישוק"],"aliases_en":["globe artichoke","artichoke heart"],"source":"curated"},
    {"food_id":"food_179","name_he":"שעועית ירוקה","name_en":"Green Beans",
     "category":"vegetable","calories_kcal":31.0,"protein_g":1.8,"carbs_g":7.0,"fat_g":0.2,
     "fiber_g":2.7,"default_serving_g":100.0,"aliases_he":["פול ירוק","שעועית"],"aliases_en":["french beans","string beans","haricots verts"],"source":"curated"},
    {"food_id":"food_180","name_he":"קייל","name_en":"Kale",
     "category":"vegetable","calories_kcal":49.0,"protein_g":4.3,"carbs_g":9.0,"fat_g":0.9,
     "fiber_g":3.6,"default_serving_g":80.0,"aliases_he":["כרוב עלים","קאלה"],"aliases_en":["curly kale","lacinato kale"],"source":"curated"},
    {"food_id":"food_181","name_he":"מנגולד","name_en":"Swiss Chard",
     "category":"vegetable","calories_kcal":19.0,"protein_g":1.8,"carbs_g":3.7,"fat_g":0.2,
     "fiber_g":1.6,"default_serving_g":100.0,"aliases_he":["עלי מנגולד","ביט"],"aliases_en":["chard","rainbow chard"],"source":"curated"},
    {"food_id":"food_182","name_he":"רוקט","name_en":"Arugula",
     "category":"vegetable","calories_kcal":25.0,"protein_g":2.6,"carbs_g":3.7,"fat_g":0.7,
     "fiber_g":1.6,"default_serving_g":50.0,"aliases_he":["גרגר נחלים","עלי רוקט"],"aliases_en":["rocket","rucola"],"source":"curated"},
    {"food_id":"food_183","name_he":"בוק צ'וי","name_en":"Bok Choy",
     "category":"vegetable","calories_kcal":13.0,"protein_g":1.5,"carbs_g":2.2,"fat_g":0.2,
     "fiber_g":1.0,"default_serving_g":100.0,"aliases_he":["כרוב סיני","פאק צ'וי"],"aliases_en":["pak choi","chinese cabbage"],"source":"curated"},
    {"food_id":"food_184","name_he":"סלק","name_en":"Beetroot",
     "category":"vegetable","calories_kcal":43.0,"protein_g":1.6,"carbs_g":10.0,"fat_g":0.2,
     "fiber_g":2.8,"default_unit":"unit","default_serving_g":100.0,"aliases_he":["סלק אדום","סלק מבושל"],"aliases_en":["beet","red beet","cooked beet"],"source":"curated"},
    {"food_id":"food_185","name_he":"לפת","name_en":"Turnip",
     "category":"vegetable","calories_kcal":28.0,"protein_g":0.9,"carbs_g":6.4,"fat_g":0.1,
     "fiber_g":1.8,"default_serving_g":100.0,"aliases_he":["לפת לבנה"],"aliases_en":["white turnip"],"source":"curated"},
    {"food_id":"food_186","name_he":"דלעת חמאה","name_en":"Butternut Squash",
     "category":"vegetable","calories_kcal":45.0,"protein_g":1.0,"carbs_g":12.0,"fat_g":0.1,
     "fiber_g":2.0,"default_serving_g":150.0,"aliases_he":["דלעת","קישוא חורף"],"aliases_en":["squash","winter squash"],"source":"curated"},
    {"food_id":"food_187","name_he":"פלפל ירוק חריף","name_en":"Jalapeño",
     "category":"vegetable","calories_kcal":29.0,"protein_g":0.9,"carbs_g":6.5,"fat_g":0.4,
     "fiber_g":2.8,"default_unit":"unit","default_serving_g":15.0,"aliases_he":["ח'לפניו","פלפל חריף ירוק"],"aliases_en":["chili pepper","green chili"],"source":"curated"},
    {"food_id":"food_188","name_he":"בצל ירוק","name_en":"Green Onion",
     "category":"vegetable","calories_kcal":32.0,"protein_g":1.8,"carbs_g":7.3,"fat_g":0.2,
     "fiber_g":2.6,"default_serving_g":30.0,"aliases_he":["עירית","בצלצל ירוק"],"aliases_en":["scallion","spring onion","chives"],"source":"curated"},
    {"food_id":"food_189","name_he":"עגבניות מיובשות","name_en":"Sun-Dried Tomatoes",
     "category":"vegetable","calories_kcal":258.0,"protein_g":14.0,"carbs_g":55.0,"fat_g":3.0,
     "fiber_g":12.0,"default_serving_g":20.0,"aliases_he":["עגבניות מיובשות בשמן"],"aliases_en":["dried tomatoes","sun dried tomatoes in oil"],"source":"curated"},
    {"food_id":"food_190","name_he":"כמיה","name_en":"Okra",
     "category":"vegetable","calories_kcal":33.0,"protein_g":1.9,"carbs_g":7.5,"fat_g":0.2,
     "fiber_g":3.2,"default_serving_g":100.0,"aliases_he":["במיה","בניה"],"aliases_en":["ladies finger","gumbo"],"source":"curated"},
    {"food_id":"food_191","name_he":"קימצ'י","name_en":"Kimchi",
     "category":"vegetable","calories_kcal":15.0,"protein_g":1.1,"carbs_g":2.4,"fat_g":0.5,
     "fiber_g":1.6,"default_serving_g":70.0,"aliases_he":["ירקות מותססים קוריאנים"],"aliases_en":["korean fermented cabbage","kimchee"],"source":"curated"},
    {"food_id":"food_192","name_he":"כרכום טרי","name_en":"Turmeric Root",
     "category":"vegetable","calories_kcal":312.0,"protein_g":9.7,"carbs_g":68.0,"fat_g":3.3,
     "fiber_g":22.0,"default_unit":"teaspoon","default_serving_g":3.0,"aliases_he":["כורכום"],"aliases_en":["fresh turmeric","curcuma"],"source":"curated"},
    {"food_id":"food_193","name_he":"שורש ג'ינג'ר","name_en":"Ginger Root",
     "category":"vegetable","calories_kcal":80.0,"protein_g":1.8,"carbs_g":18.0,"fat_g":0.8,
     "fiber_g":2.0,"default_unit":"teaspoon","default_serving_g":5.0,"aliases_he":["ג'ינג'ר","שורש ג'ינג'ר טרי"],"aliases_en":["fresh ginger","ginger"],"source":"curated"},
    {"food_id":"food_194","name_he":"שעועית אדומה","name_en":"Kidney Beans",
     "category":"legume","calories_kcal":127.0,"protein_g":8.7,"carbs_g":23.0,"fat_g":0.5,
     "fiber_g":6.8,"default_serving_g":150.0,"aliases_he":["שעועית אדומה מבושלת","שעועית צ'ילי"],"aliases_en":["red kidney beans","cooked kidney beans"],"source":"curated"},
    {"food_id":"food_195","name_he":"שעועית ירוקה קפואה","name_en":"Frozen Green Beans",
     "category":"vegetable","calories_kcal":29.0,"protein_g":1.7,"carbs_g":6.3,"fat_g":0.1,
     "fiber_g":2.6,"default_serving_g":100.0,"aliases_he":["שעועית ירוקה קפואה","שעועית מבושלת"],"aliases_en":["snap beans","frozen beans"],"source":"curated"},

    # ── FRUITS (extended) ─────────────────────────────────────────────────────
    {"food_id":"food_196","name_he":"אננס","name_en":"Pineapple",
     "category":"fruit","calories_kcal":50.0,"protein_g":0.5,"carbs_g":13.0,"fat_g":0.1,
     "fiber_g":1.4,"sugar_g":9.9,"default_serving_g":150.0,"aliases_he":["אנאנס"],"aliases_en":["fresh pineapple","pineapple chunks"],"source":"curated"},
    {"food_id":"food_197","name_he":"פפאיה","name_en":"Papaya",
     "category":"fruit","calories_kcal":43.0,"protein_g":0.5,"carbs_g":11.0,"fat_g":0.3,
     "fiber_g":1.7,"sugar_g":7.8,"default_serving_g":150.0,"aliases_he":["פאפאיה"],"aliases_en":["papaw","pawpaw"],"source":"curated"},
    {"food_id":"food_198","name_he":"מלון","name_en":"Cantaloupe Melon",
     "category":"fruit","calories_kcal":34.0,"protein_g":0.8,"carbs_g":8.2,"fat_g":0.2,
     "fiber_g":0.9,"sugar_g":7.9,"default_serving_g":200.0,"aliases_he":["מלון כתום","מלון ירוק"],"aliases_en":["honeydew melon","rockmelon"],"source":"curated"},
    {"food_id":"food_199","name_he":"שזיף","name_en":"Plum",
     "category":"fruit","calories_kcal":46.0,"protein_g":0.7,"carbs_g":11.0,"fat_g":0.3,
     "fiber_g":1.4,"sugar_g":9.9,"default_unit":"unit","default_serving_g":80.0,"aliases_he":["שזיפים","שזיף אדום"],"aliases_en":["fresh plum","italian plum"],"source":"curated"},
    {"food_id":"food_200","name_he":"משמש","name_en":"Apricot",
     "category":"fruit","calories_kcal":48.0,"protein_g":1.4,"carbs_g":11.0,"fat_g":0.4,
     "fiber_g":2.0,"sugar_g":9.2,"default_unit":"unit","default_serving_g":50.0,"aliases_he":["אפרסמון","משמשים"],"aliases_en":["fresh apricot"],"source":"curated"},
    {"food_id":"food_201","name_he":"פסיפלורה","name_en":"Passion Fruit",
     "category":"fruit","calories_kcal":97.0,"protein_g":2.2,"carbs_g":23.0,"fat_g":0.7,
     "fiber_g":10.4,"sugar_g":11.2,"default_unit":"unit","default_serving_g":18.0,"aliases_he":["מרקת התשוקה","פסיפרות"],"aliases_en":["passionfruit","granadilla"],"source":"curated"},
    {"food_id":"food_202","name_he":"ליצ'י","name_en":"Lychee",
     "category":"fruit","calories_kcal":66.0,"protein_g":0.8,"carbs_g":17.0,"fat_g":0.4,
     "fiber_g":1.3,"sugar_g":15.2,"default_serving_g":100.0,"aliases_he":["לאיצ'י"],"aliases_en":["lychees","litchi"],"source":"curated"},
    {"food_id":"food_203","name_he":"חמוציות","name_en":"Cranberries",
     "category":"fruit","calories_kcal":46.0,"protein_g":0.4,"carbs_g":12.0,"fat_g":0.1,
     "fiber_g":4.6,"sugar_g":4.0,"default_serving_g":100.0,"aliases_he":["קרנברי"],"aliases_en":["fresh cranberries","dried cranberries"],"source":"curated"},
    {"food_id":"food_204","name_he":"פטל","name_en":"Raspberries",
     "category":"fruit","calories_kcal":52.0,"protein_g":1.2,"carbs_g":12.0,"fat_g":0.7,
     "fiber_g":6.5,"sugar_g":4.4,"default_serving_g":100.0,"aliases_he":["פטל אדום"],"aliases_en":["red raspberries","fresh raspberries"],"source":"curated"},
    {"food_id":"food_205","name_he":"אוכמניות שחורות","name_en":"Blackberries",
     "category":"fruit","calories_kcal":43.0,"protein_g":1.4,"carbs_g":10.0,"fat_g":0.5,
     "fiber_g":5.3,"sugar_g":4.9,"default_serving_g":100.0,"aliases_he":["פאול","ברמבל"],"aliases_en":["fresh blackberries"],"source":"curated"},
    {"food_id":"food_206","name_he":"צימוקים","name_en":"Raisins",
     "category":"fruit","calories_kcal":299.0,"protein_g":3.1,"carbs_g":79.0,"fat_g":0.5,
     "fiber_g":3.7,"sugar_g":59.2,"default_serving_g":30.0,"aliases_he":["ענבים מיובשים"],"aliases_en":["seedless raisins","golden raisins"],"source":"curated"},
    {"food_id":"food_207","name_he":"שזיפים מיובשים","name_en":"Prunes",
     "category":"fruit","calories_kcal":240.0,"protein_g":2.2,"carbs_g":64.0,"fat_g":0.4,
     "fiber_g":7.1,"sugar_g":38.1,"default_serving_g":30.0,"aliases_he":["שזיפים יבשים","שזיף מיובש"],"aliases_en":["dried plums","dried prunes"],"source":"curated"},
    {"food_id":"food_208","name_he":"משמשים מיובשים","name_en":"Dried Apricots",
     "category":"fruit","calories_kcal":241.0,"protein_g":3.4,"carbs_g":63.0,"fat_g":0.5,
     "fiber_g":7.3,"sugar_g":53.4,"default_serving_g":30.0,"aliases_he":["משמש יבש"],"aliases_en":["dried apricot halves"],"source":"curated"},
    {"food_id":"food_209","name_he":"לימון","name_en":"Lemon",
     "category":"fruit","calories_kcal":29.0,"protein_g":1.1,"carbs_g":9.0,"fat_g":0.3,
     "fiber_g":2.8,"default_unit":"unit","default_serving_g":60.0,"aliases_he":["לימונים","מיץ לימון"],"aliases_en":["fresh lemon","lemon juice"],"source":"curated"},
    {"food_id":"food_210","name_he":"ליים","name_en":"Lime",
     "category":"fruit","calories_kcal":30.0,"protein_g":0.7,"carbs_g":11.0,"fat_g":0.2,
     "fiber_g":2.8,"default_unit":"unit","default_serving_g":50.0,"aliases_he":["לייים","ליים ירוק"],"aliases_en":["fresh lime","key lime"],"source":"curated"},
    {"food_id":"food_211","name_he":"אשכולית","name_en":"Grapefruit",
     "category":"fruit","calories_kcal":42.0,"protein_g":0.8,"carbs_g":11.0,"fat_g":0.1,
     "fiber_g":1.6,"sugar_g":7.0,"default_unit":"unit","default_serving_g":200.0,"aliases_he":["אשכוליות","פרי הדר"],"aliases_en":["red grapefruit","white grapefruit"],"source":"curated"},
    {"food_id":"food_212","name_he":"קוקוס טרי","name_en":"Coconut Meat",
     "category":"fruit","calories_kcal":354.0,"protein_g":3.3,"carbs_g":15.0,"fat_g":33.0,
     "fiber_g":9.0,"default_serving_g":30.0,"aliases_he":["בשר קוקוס","קוקוס מגורד"],"aliases_en":["shredded coconut","desiccated coconut"],"source":"curated"},
    {"food_id":"food_213","name_he":"תאנים טריות","name_en":"Fresh Figs",
     "category":"fruit","calories_kcal":74.0,"protein_g":0.8,"carbs_g":19.0,"fat_g":0.3,
     "fiber_g":2.9,"sugar_g":16.3,"default_unit":"unit","default_serving_g":50.0,"aliases_he":["תאנה","תאנים"],"aliases_en":["fresh fig","black fig"],"source":"curated"},

    # ── FAST FOOD & PREPARED DISHES ───────────────────────────────────────────
    {"food_id":"food_214","name_he":"צ'יפס תפוח אדמה","name_en":"French Fries",
     "category":"other","calories_kcal":312.0,"protein_g":3.4,"carbs_g":41.0,"fat_g":15.0,
     "fiber_g":3.8,"default_serving_g":150.0,"aliases_he":["ציפס","תפוח אדמה מטוגן"],"aliases_en":["potato fries","chips","steak fries"],"source":"curated"},
    {"food_id":"food_215","name_he":"המבורגר","name_en":"Hamburger",
     "category":"other","calories_kcal":295.0,"protein_g":17.0,"carbs_g":25.0,"fat_g":13.0,
     "default_unit":"unit","default_serving_g":200.0,"aliases_he":["הבורגר","בורגר בקר"],"aliases_en":["beef burger","cheeseburger"],"source":"curated"},
    {"food_id":"food_216","name_he":"פיצה מרגריטה","name_en":"Pizza Margherita",
     "category":"other","calories_kcal":266.0,"protein_g":11.0,"carbs_g":33.0,"fat_g":10.0,
     "fiber_g":2.3,"default_unit":"slice","default_serving_g":100.0,"aliases_he":["פיצה","פיצה גבינה"],"aliases_en":["margherita pizza","cheese pizza"],"source":"curated"},
    {"food_id":"food_217","name_he":"ספגטי בולונז","name_en":"Spaghetti Bolognese",
     "category":"other","calories_kcal":150.0,"protein_g":9.0,"carbs_g":16.0,"fat_g":5.5,
     "fiber_g":2.0,"default_serving_g":300.0,"aliases_he":["ספגטי עם רוטב בשר"],"aliases_en":["pasta bolognese","meat sauce pasta"],"source":"curated"},
    {"food_id":"food_218","name_he":"מק אנד צ'יז","name_en":"Mac and Cheese",
     "category":"other","calories_kcal":172.0,"protein_g":7.0,"carbs_g":21.0,"fat_g":6.8,
     "fiber_g":1.0,"default_serving_g":240.0,"aliases_he":["פסטה עם גבינה","מקרוני גבינה"],"aliases_en":["macaroni and cheese","kraft mac and cheese"],"source":"curated"},
    {"food_id":"food_219","name_he":"עוף מטוגן","name_en":"Fried Chicken",
     "category":"other","calories_kcal":246.0,"protein_g":24.0,"carbs_g":8.8,"fat_g":13.0,
     "default_unit":"unit","default_serving_g":100.0,"aliases_he":["עוף פריך","קנטאקי"],"aliases_en":["KFC-style chicken","crispy fried chicken"],"source":"curated"},
    {"food_id":"food_220","name_he":"נאגטס עוף","name_en":"Chicken Nuggets",
     "category":"other","calories_kcal":297.0,"protein_g":16.0,"carbs_g":19.0,"fat_g":18.0,
     "default_unit":"unit","default_serving_g":15.0,"aliases_he":["נגטס","ניגטס עוף"],"aliases_en":["mcnuggets","chicken strips"],"source":"curated"},
    {"food_id":"food_221","name_he":"כנפי בופלו","name_en":"Buffalo Wings",
     "category":"other","calories_kcal":289.0,"protein_g":28.0,"carbs_g":2.7,"fat_g":18.0,
     "default_unit":"unit","default_serving_g":40.0,"aliases_he":["כנפיים חריפות"],"aliases_en":["hot wings","spicy chicken wings"],"source":"curated"},
    {"food_id":"food_222","name_he":"אוניינג' רינגס","name_en":"Onion Rings",
     "category":"other","calories_kcal":411.0,"protein_g":4.9,"carbs_g":43.0,"fat_g":25.0,
     "default_serving_g":100.0,"aliases_he":["טבעות בצל"],"aliases_en":["fried onion rings","crispy onion rings"],"source":"curated"},
    {"food_id":"food_223","name_he":"אגרולים","name_en":"Spring Rolls",
     "category":"other","calories_kcal":170.0,"protein_g":3.8,"carbs_g":24.0,"fat_g":6.5,
     "default_unit":"unit","default_serving_g":70.0,"aliases_he":["ספרינג רול","אגרול"],"aliases_en":["egg rolls","fried spring rolls"],"source":"curated"},
    {"food_id":"food_224","name_he":"גיוזה","name_en":"Gyoza Dumplings",
     "category":"other","calories_kcal":225.0,"protein_g":9.0,"carbs_g":32.0,"fat_g":7.5,
     "default_unit":"unit","default_serving_g":15.0,"aliases_he":["דמפלינגס","כופתאות"],"aliases_en":["potstickers","pan-fried dumplings"],"source":"curated"},
    {"food_id":"food_225","name_he":"סושי ראול","name_en":"Sushi Roll",
     "category":"other","calories_kcal":165.0,"protein_g":7.0,"carbs_g":28.0,"fat_g":3.0,
     "default_unit":"unit","default_serving_g":30.0,"aliases_he":["מאקי","קליפורניה ראול"],"aliases_en":["california roll","maki roll","sushi"],"source":"curated"},
    {"food_id":"food_226","name_he":"פד תאי","name_en":"Pad Thai",
     "category":"other","calories_kcal":181.0,"protein_g":6.0,"carbs_g":26.0,"fat_g":6.0,
     "fiber_g":1.5,"default_serving_g":300.0,"aliases_he":["פאד תאי","אטריות תאילנדיות מוקפצות"],"aliases_en":["thai stir-fried noodles","pad thai noodles"],"source":"curated"},
    {"food_id":"food_227","name_he":"אורז מוקפץ","name_en":"Fried Rice",
     "category":"other","calories_kcal":163.0,"protein_g":4.0,"carbs_g":28.0,"fat_g":3.5,
     "default_serving_g":200.0,"aliases_he":["אורז סיני","אורז מטוגן"],"aliases_en":["chinese fried rice","egg fried rice"],"source":"curated"},
    {"food_id":"food_228","name_he":"טאקו בקר","name_en":"Beef Taco",
     "category":"other","calories_kcal":217.0,"protein_g":10.0,"carbs_g":20.0,"fat_g":11.0,
     "default_unit":"unit","default_serving_g":100.0,"aliases_he":["טאקו"],"aliases_en":["ground beef taco","street taco"],"source":"curated"},
    {"food_id":"food_229","name_he":"בוריטו","name_en":"Burrito",
     "category":"other","calories_kcal":163.0,"protein_g":6.0,"carbs_g":24.0,"fat_g":4.0,
     "default_unit":"unit","default_serving_g":300.0,"aliases_he":["בוריטו עוף"],"aliases_en":["chicken burrito","bean burrito"],"source":"curated"},
    {"food_id":"food_230","name_he":"קסדייה","name_en":"Quesadilla",
     "category":"other","calories_kcal":309.0,"protein_g":14.0,"carbs_g":31.0,"fat_g":15.0,
     "default_unit":"unit","default_serving_g":150.0,"aliases_he":["קסדיה","גבינה בטורטייה"],"aliases_en":["cheese quesadilla","chicken quesadilla"],"source":"curated"},
    {"food_id":"food_231","name_he":"קרוב'י שחרב","name_en":"Caesar Salad",
     "category":"other","calories_kcal":158.0,"protein_g":7.4,"carbs_g":11.0,"fat_g":10.0,
     "fiber_g":1.6,"default_serving_g":200.0,"aliases_he":["סלט קיסר","קיסר"],"aliases_en":["caesar salad with croutons","classic caesar"],"source":"curated"},
    {"food_id":"food_232","name_he":"ריזוטו","name_en":"Risotto",
     "category":"other","calories_kcal":166.0,"protein_g":3.9,"carbs_g":28.0,"fat_g":4.1,
     "fiber_g":0.8,"default_serving_g":250.0,"aliases_he":["ריזוטו פטריות","אורז איטלקי"],"aliases_en":["mushroom risotto","parmesan risotto"],"source":"curated"},
    {"food_id":"food_233","name_he":"לזניה","name_en":"Lasagna",
     "category":"other","calories_kcal":166.0,"protein_g":9.0,"carbs_g":16.0,"fat_g":7.0,
     "fiber_g":1.5,"default_serving_g":250.0,"aliases_he":["לזניה בשר","לזניה ירקות"],"aliases_en":["meat lasagna","pasta lasagne"],"source":"curated"},
    {"food_id":"food_234","name_he":"שווארמה","name_en":"Shawarma",
     "category":"other","calories_kcal":220.0,"protein_g":15.0,"carbs_g":12.0,"fat_g":12.0,
     "default_serving_g":200.0,"aliases_he":["שווארמה עוף","שווארמה בקר"],"aliases_en":["chicken shawarma","beef shawarma","kebab wrap"],"source":"curated"},
    {"food_id":"food_235","name_he":"קבב","name_en":"Kebab",
     "category":"other","calories_kcal":246.0,"protein_g":18.0,"carbs_g":5.0,"fat_g":17.0,
     "default_serving_g":100.0,"aliases_he":["קבב בשר","קוופטה"],"aliases_en":["ground meat kebab","kofta"],"source":"curated"},
    {"food_id":"food_236","name_he":"דג בציפוי","name_en":"Fish and Chips",
     "category":"other","calories_kcal":270.0,"protein_g":15.0,"carbs_g":31.0,"fat_g":9.3,
     "default_serving_g":300.0,"aliases_he":["דג מטוגן עם ציפס"],"aliases_en":["battered fish","beer-battered fish"],"source":"curated"},
    {"food_id":"food_237","name_he":"מנה ביריאני","name_en":"Chicken Biryani",
     "category":"other","calories_kcal":148.0,"protein_g":9.0,"carbs_g":23.0,"fat_g":2.5,
     "fiber_g":1.2,"default_serving_g":300.0,"aliases_he":["בריאני"],"aliases_en":["rice biryani","lamb biryani"],"source":"curated"},
    {"food_id":"food_238","name_he":"נודלס ראמן","name_en":"Ramen",
     "category":"other","calories_kcal":436.0,"protein_g":12.0,"carbs_g":62.0,"fat_g":16.0,
     "fiber_g":2.5,"default_serving_g":400.0,"aliases_he":["ראמן יפני","מרק נודלס"],"aliases_en":["japanese ramen","tonkotsu ramen","miso ramen"],"source":"curated"},
    {"food_id":"food_239","name_he":"כרוב מוקפץ","name_en":"Stir-Fry Vegetables",
     "category":"other","calories_kcal":60.0,"protein_g":3.0,"carbs_g":8.5,"fat_g":2.0,
     "fiber_g":3.0,"default_serving_g":200.0,"aliases_he":["ירקות מוקפצים","חלאם"],"aliases_en":["mixed stir-fry","asian stir-fried veggies"],"source":"curated"},
    {"food_id":"food_240","name_he":"מרק עוף","name_en":"Chicken Soup",
     "category":"other","calories_kcal":40.0,"protein_g":4.0,"carbs_g":3.0,"fat_g":1.5,
     "fiber_g":0.5,"default_serving_g":300.0,"aliases_he":["מרק עוף עם אטריות","ציר עוף"],"aliases_en":["chicken broth","chicken noodle soup"],"source":"curated"},
    {"food_id":"food_241","name_he":"מרק עגבניות","name_en":"Tomato Soup",
     "category":"other","calories_kcal":68.0,"protein_g":1.7,"carbs_g":11.0,"fat_g":2.0,
     "fiber_g":1.0,"default_serving_g":300.0,"aliases_he":["מרק עגבניות קרמי","מרק עגבניות שמנת"],"aliases_en":["cream of tomato","tomato bisque"],"source":"curated"},
    {"food_id":"food_242","name_he":"גנוצ'י","name_en":"Gnocchi",
     "category":"other","calories_kcal":130.0,"protein_g":3.4,"carbs_g":28.0,"fat_g":0.7,
     "fiber_g":1.5,"default_serving_g":200.0,"aliases_he":["ניוקי"],"aliases_en":["potato gnocchi","ricotta gnocchi"],"source":"curated"},
    {"food_id":"food_243","name_he":"פנקייקס","name_en":"Pancakes",
     "category":"other","calories_kcal":227.0,"protein_g":6.0,"carbs_g":38.0,"fat_g":6.3,
     "default_unit":"unit","default_serving_g":70.0,"aliases_he":["פנקייק","חביתיות"],"aliases_en":["buttermilk pancakes","american pancakes"],"source":"curated"},
    {"food_id":"food_244","name_he":"ואפל","name_en":"Waffle",
     "category":"other","calories_kcal":291.0,"protein_g":8.0,"carbs_g":37.0,"fat_g":13.0,
     "default_unit":"unit","default_serving_g":75.0,"aliases_he":["ואפל בלגי"],"aliases_en":["belgian waffle","homemade waffle"],"source":"curated"},

    # ── SNACKS ────────────────────────────────────────────────────────────────
    {"food_id":"food_245","name_he":"צ'יפס תפוח אדמה קלוי","name_en":"Potato Chips",
     "category":"other","calories_kcal":536.0,"protein_g":7.0,"carbs_g":53.0,"fat_g":35.0,
     "fiber_g":4.4,"default_serving_g":30.0,"aliases_he":["ביסלי","פרינגלס","קריספי"],"aliases_en":["crisps","potato crisps","pringles"],"source":"curated"},
    {"food_id":"food_246","name_he":"צ'יפס תירס","name_en":"Tortilla Chips",
     "category":"other","calories_kcal":489.0,"protein_g":7.3,"carbs_g":65.0,"fat_g":23.0,
     "fiber_g":4.5,"default_serving_g":30.0,"aliases_he":["דורטוס","ביסלי תירס","נאצ'וס"],"aliases_en":["doritos","nachos chips"],"source":"curated"},
    {"food_id":"food_247","name_he":"פופקורן מוכן","name_en":"Popcorn",
     "category":"other","calories_kcal":387.0,"protein_g":13.0,"carbs_g":78.0,"fat_g":4.5,
     "fiber_g":14.5,"default_serving_g":30.0,"aliases_he":["פופקורן"],"aliases_en":["air popped popcorn","movie popcorn"],"source":"curated"},
    {"food_id":"food_248","name_he":"פרצלים","name_en":"Pretzels",
     "category":"other","calories_kcal":380.0,"protein_g":10.0,"carbs_g":80.0,"fat_g":2.8,
     "fiber_g":2.8,"default_serving_g":30.0,"aliases_he":["מלוחים","ברצלים"],"aliases_en":["soft pretzel","hard pretzels"],"source":"curated"},
    {"food_id":"food_249","name_he":"עוגיות שוקולד צ'יפס","name_en":"Chocolate Chip Cookies",
     "category":"other","calories_kcal":488.0,"protein_g":5.4,"carbs_g":69.0,"fat_g":21.0,
     "fiber_g":2.1,"default_unit":"unit","default_serving_g":15.0,"aliases_he":["עוגיות","ביסקוויטים"],"aliases_en":["choc chip cookie","american cookies"],"source":"curated"},
    {"food_id":"food_250","name_he":"חטיף חלבון","name_en":"Protein Bar",
     "category":"other","calories_kcal":350.0,"protein_g":25.0,"carbs_g":35.0,"fat_g":10.0,
     "fiber_g":4.0,"default_unit":"unit","default_serving_g":60.0,"aliases_he":["חטיף אנרגיה","בר חלבון"],"aliases_en":["energy bar","quest bar","clif bar"],"source":"curated"},
    {"food_id":"food_251","name_he":"חטיף גרנולה","name_en":"Granola Bar",
     "category":"other","calories_kcal":471.0,"protein_g":7.0,"carbs_g":64.0,"fat_g":20.0,
     "fiber_g":5.0,"default_unit":"unit","default_serving_g":47.0,"aliases_he":["בר גרנולה"],"aliases_en":["oat bar","nature valley bar"],"source":"curated"},
    {"food_id":"food_252","name_he":"גומי דובים","name_en":"Gummy Bears",
     "category":"other","calories_kcal":332.0,"protein_g":7.0,"carbs_g":77.0,"fat_g":0.5,
     "default_serving_g":30.0,"aliases_he":["סוכריות גומי"],"aliases_en":["gummy candy","haribo"],"source":"curated"},
    {"food_id":"food_253","name_he":"שוקולד חלב","name_en":"Milk Chocolate",
     "category":"other","calories_kcal":535.0,"protein_g":7.6,"carbs_g":59.0,"fat_g":30.0,
     "fiber_g":3.4,"default_serving_g":30.0,"aliases_he":["שוקולד","שוקולד רגיל"],"aliases_en":["chocolate bar","cadbury milk chocolate"],"source":"curated"},

    # ── DESSERTS ──────────────────────────────────────────────────────────────
    {"food_id":"food_254","name_he":"בראוניז","name_en":"Brownie",
     "category":"other","calories_kcal":466.0,"protein_g":5.9,"carbs_g":63.0,"fat_g":22.0,
     "fiber_g":2.6,"default_unit":"unit","default_serving_g":50.0,"aliases_he":["בראוני","עוגת שוקולד"],"aliases_en":["chocolate brownie","fudge brownie"],"source":"curated"},
    {"food_id":"food_255","name_he":"עוגת גבינה","name_en":"Cheesecake",
     "category":"other","calories_kcal":321.0,"protein_g":5.9,"carbs_g":26.0,"fat_g":23.0,
     "default_unit":"slice","default_serving_g":120.0,"aliases_he":["צ'יזקייק","עוגת גבינה אפויה"],"aliases_en":["new york cheesecake","baked cheesecake"],"source":"curated"},
    {"food_id":"food_256","name_he":"עוגת תפוחים","name_en":"Apple Pie",
     "category":"other","calories_kcal":237.0,"protein_g":2.0,"carbs_g":34.0,"fat_g":11.0,
     "fiber_g":1.6,"default_unit":"slice","default_serving_g":125.0,"aliases_he":["פאי תפוחים","טארט תפוחים"],"aliases_en":["apple tart","apple crumble"],"source":"curated"},
    {"food_id":"food_257","name_he":"דונאט","name_en":"Glazed Donut",
     "category":"other","calories_kcal":452.0,"protein_g":5.0,"carbs_g":51.0,"fat_g":25.0,
     "default_unit":"unit","default_serving_g":50.0,"aliases_he":["סופגנייה","דאנקין"],"aliases_en":["doughnut","krispy kreme"],"source":"curated"},
    {"food_id":"food_258","name_he":"מאפין אוכמניות","name_en":"Blueberry Muffin",
     "category":"other","calories_kcal":442.0,"protein_g":7.0,"carbs_g":65.0,"fat_g":17.0,
     "fiber_g":1.8,"default_unit":"unit","default_serving_g":100.0,"aliases_he":["מאפין","קאפקייק"],"aliases_en":["muffin","cupcake"],"source":"curated"},
    {"food_id":"food_259","name_he":"טירמיסו","name_en":"Tiramisu",
     "category":"other","calories_kcal":240.0,"protein_g":5.4,"carbs_g":24.0,"fat_g":14.0,
     "default_serving_g":100.0,"aliases_he":["טירמיזו"],"aliases_en":["tiramisu cake","italian dessert"],"source":"curated"},
    {"food_id":"food_260","name_he":"בקלאווה","name_en":"Baklava",
     "category":"other","calories_kcal":428.0,"protein_g":6.2,"carbs_g":53.0,"fat_g":22.0,
     "default_unit":"unit","default_serving_g":40.0,"aliases_he":["בקלבה"],"aliases_en":["honey baklava","pistachio baklava"],"source":"curated"},
    {"food_id":"food_261","name_he":"קרם ברולה","name_en":"Crème Brûlée",
     "category":"other","calories_kcal":287.0,"protein_g":4.0,"carbs_g":27.0,"fat_g":18.0,
     "default_serving_g":120.0,"aliases_he":["קרם ברולה","קרם שרוף"],"aliases_en":["creme brulee","french custard"],"source":"curated"},
    {"food_id":"food_262","name_he":"ג'לי","name_en":"Jello",
     "category":"other","calories_kcal":62.0,"protein_g":1.3,"carbs_g":15.0,"fat_g":0.0,
     "default_serving_g":100.0,"aliases_he":["ג'לי","ג'לטין"],"aliases_en":["gelatin","jell-o"],"source":"curated"},
    {"food_id":"food_263","name_he":"פאנה קוטה","name_en":"Panna Cotta",
     "category":"other","calories_kcal":198.0,"protein_g":3.0,"carbs_g":21.0,"fat_g":12.0,
     "default_serving_g":120.0,"aliases_he":["פנה קוטה","קרם לבן"],"aliases_en":["italian panna cotta","vanilla panna cotta"],"source":"curated"},

    # ── SAUCES & CONDIMENTS (extended) ───────────────────────────────────────
    {"food_id":"food_264","name_he":"רוטב ברביקיו","name_en":"BBQ Sauce",
     "category":"condiment","calories_kcal":172.0,"protein_g":0.9,"carbs_g":40.0,"fat_g":0.5,
     "default_unit":"tablespoon","default_serving_g":20.0,"aliases_he":["רוטב בי-בי-קיו"],"aliases_en":["barbecue sauce","smoky bbq"],"source":"curated"},
    {"food_id":"food_265","name_he":"רוטב חריף","name_en":"Hot Sauce",
     "category":"condiment","calories_kcal":11.0,"protein_g":0.3,"carbs_g":1.6,"fat_g":0.7,
     "default_unit":"teaspoon","default_serving_g":5.0,"aliases_he":["טבסקו","רוטב חריף ירוק"],"aliases_en":["tabasco","sriracha","frank's red hot"],"source":"curated"},
    {"food_id":"food_266","name_he":"פסטו","name_en":"Pesto",
     "category":"condiment","calories_kcal":467.0,"protein_g":8.5,"carbs_g":8.3,"fat_g":46.0,
     "fiber_g":2.5,"default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["פסטו בזיליקום","ממרח בזיליקום"],"aliases_en":["basil pesto","genovese pesto"],"source":"curated"},
    {"food_id":"food_267","name_he":"רוטב מרינרה","name_en":"Marinara Sauce",
     "category":"condiment","calories_kcal":53.0,"protein_g":2.0,"carbs_g":9.0,"fat_g":1.5,
     "fiber_g":1.5,"default_unit":"tablespoon","default_serving_g":60.0,"aliases_he":["רוטב עגבניות","רוטב פסטה"],"aliases_en":["tomato sauce","pasta sauce","arrabiata"],"source":"curated"},
    {"food_id":"food_268","name_he":"רוטב טריאקי","name_en":"Teriyaki Sauce",
     "category":"condiment","calories_kcal":89.0,"protein_g":6.6,"carbs_g":15.0,"fat_g":0.2,
     "default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["טריאקי","רוטב יפני"],"aliases_en":["japanese teriyaki","teriyaki glaze"],"source":"curated"},
    {"food_id":"food_269","name_he":"רוטב ראנץ'","name_en":"Ranch Dressing",
     "category":"condiment","calories_kcal":459.0,"protein_g":1.7,"carbs_g":6.8,"fat_g":48.0,
     "default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["רוטב ראנץ"],"aliases_en":["ranch dip","buttermilk ranch"],"source":"curated"},
    {"food_id":"food_270","name_he":"חומץ בלסמי","name_en":"Balsamic Vinegar",
     "category":"condiment","calories_kcal":88.0,"protein_g":0.5,"carbs_g":17.0,"fat_g":0.0,
     "default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["חומץ בלסמי","גלאזה בלסמי"],"aliases_en":["balsamic glaze","aged balsamic"],"source":"curated"},
    {"food_id":"food_271","name_he":"גוואקמולי","name_en":"Guacamole",
     "category":"condiment","calories_kcal":157.0,"protein_g":2.0,"carbs_g":9.0,"fat_g":14.0,
     "fiber_g":6.5,"default_unit":"tablespoon","default_serving_g":30.0,"aliases_he":["גוואקמוולי","ממרח אבוקדו"],"aliases_en":["avocado dip","fresh guac"],"source":"curated"},
    {"food_id":"food_272","name_he":"רוטב אויסטר","name_en":"Oyster Sauce",
     "category":"condiment","calories_kcal":50.0,"protein_g":1.7,"carbs_g":11.0,"fat_g":0.1,
     "default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["רוטב צדפות","רוטב סיני"],"aliases_en":["chinese oyster sauce"],"source":"curated"},
    {"food_id":"food_273","name_he":"רוטב הויסין","name_en":"Hoisin Sauce",
     "category":"condiment","calories_kcal":220.0,"protein_g":3.2,"carbs_g":45.0,"fat_g":2.7,
     "default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["הויסין","רוטב ברבקיו סיני"],"aliases_en":["hoisin","peking sauce"],"source":"curated"},
    {"food_id":"food_274","name_he":"חמאת קקאו","name_en":"Nutella",
     "category":"condiment","calories_kcal":539.0,"protein_g":6.3,"carbs_g":57.9,"fat_g":30.9,
     "fiber_g":3.4,"default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["נוטלה","ממרח שוקולד-אגוזים"],"aliases_en":["hazelnut spread","chocolate hazelnut spread"],"source":"curated"},
    {"food_id":"food_275","name_he":"ריבה","name_en":"Jam",
     "category":"condiment","calories_kcal":278.0,"protein_g":0.4,"carbs_g":69.0,"fat_g":0.1,
     "default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["מרמלדה","ריבת תות"],"aliases_en":["strawberry jam","grape jelly","fruit spread"],"source":"curated"},

    # ── BEVERAGES (extended) ──────────────────────────────────────────────────
    {"food_id":"food_276","name_he":"קפה לאטה","name_en":"Latte",
     "category":"beverage","calories_kcal":54.0,"protein_g":3.6,"carbs_g":5.4,"fat_g":2.0,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["לאטה","קפה עם חלב"],"aliases_en":["cafe latte","flat white"],"source":"curated"},
    {"food_id":"food_277","name_he":"קפוצ'ינו","name_en":"Cappuccino",
     "category":"beverage","calories_kcal":40.0,"protein_g":2.7,"carbs_g":4.0,"fat_g":1.5,
     "default_unit":"cup","default_serving_g":180.0,"aliases_he":["קפוצינו"],"aliases_en":["cappuccino","italian coffee"],"source":"curated"},
    {"food_id":"food_278","name_he":"שייק חלבון","name_en":"Protein Shake",
     "category":"beverage","calories_kcal":120.0,"protein_g":20.0,"carbs_g":7.0,"fat_g":1.5,
     "default_unit":"cup","default_serving_g":300.0,"aliases_he":["שייק חלבון","שייק אחרי אימון"],"aliases_en":["whey shake","post-workout shake"],"source":"curated"},
    {"food_id":"food_279","name_he":"שייק פירות","name_en":"Fruit Smoothie",
     "category":"beverage","calories_kcal":57.0,"protein_g":0.5,"carbs_g":14.0,"fat_g":0.3,
     "default_unit":"cup","default_serving_g":300.0,"aliases_he":["סמוזי","שייק פירות"],"aliases_en":["mixed berry smoothie","fruit blend"],"source":"curated"},
    {"food_id":"food_280","name_he":"לימונדה","name_en":"Lemonade",
     "category":"beverage","calories_kcal":40.0,"protein_g":0.1,"carbs_g":10.0,"fat_g":0.1,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["לימונדה טבעית"],"aliases_en":["fresh lemonade","homemade lemonade"],"source":"curated"},
    {"food_id":"food_281","name_he":"מיץ ענבים","name_en":"Grape Juice",
     "category":"beverage","calories_kcal":60.0,"protein_g":0.4,"carbs_g":15.0,"fat_g":0.1,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["מיץ ענבים 100%"],"aliases_en":["100% grape juice","purple grape juice"],"source":"curated"},
    {"food_id":"food_282","name_he":"קומבוצ'ה","name_en":"Kombucha",
     "category":"beverage","calories_kcal":9.0,"protein_g":0.0,"carbs_g":2.5,"fat_g":0.0,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["קומבוצ'ה","משקה מותסס"],"aliases_en":["fermented tea","kombucha drink"],"source":"curated"},
    {"food_id":"food_283","name_he":"מי קוקוס","name_en":"Coconut Water",
     "category":"beverage","calories_kcal":19.0,"protein_g":0.7,"carbs_g":3.7,"fat_g":0.2,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["מים מקוקוס","מי קוקוס טבעיים"],"aliases_en":["fresh coconut water","vita coco"],"source":"curated"},
    {"food_id":"food_284","name_he":"יין אדום","name_en":"Red Wine",
     "category":"beverage","calories_kcal":85.0,"protein_g":0.1,"carbs_g":2.7,"fat_g":0.0,
     "default_unit":"cup","default_serving_g":150.0,"aliases_he":["יין","יין אדום יבש"],"aliases_en":["dry red wine","cabernet sauvignon"],"source":"curated"},
    {"food_id":"food_285","name_he":"בירה קלה","name_en":"Light Beer",
     "category":"beverage","calories_kcal":29.0,"protein_g":0.4,"carbs_g":1.6,"fat_g":0.0,
     "default_unit":"cup","default_serving_g":355.0,"aliases_he":["בירה דיאט"],"aliases_en":["lite beer","low calorie beer"],"source":"curated"},
    {"food_id":"food_286","name_he":"מרק עצמות","name_en":"Bone Broth",
     "category":"beverage","calories_kcal":38.0,"protein_g":6.0,"carbs_g":3.3,"fat_g":0.5,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["ציר עצמות","מרק ציר"],"aliases_en":["beef bone broth","collagen broth"],"source":"curated"},
    {"food_id":"food_287","name_he":"חלב שקדים ללא סוכר","name_en":"Unsweetened Almond Milk",
     "category":"beverage","calories_kcal":15.0,"protein_g":0.6,"carbs_g":0.6,"fat_g":1.2,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["חלב שקדים"],"aliases_en":["almond milk plain","unsweetened almond"],"source":"curated"},

    # ── OILS & FATS (extended) ────────────────────────────────────────────────
    {"food_id":"food_288","name_he":"גהי","name_en":"Ghee",
     "category":"fat","calories_kcal":900.0,"protein_g":0.0,"carbs_g":0.0,"fat_g":100.0,
     "default_unit":"tablespoon","default_serving_g":14.0,"aliases_he":["חמאה מזוקקת","שמן גהי"],"aliases_en":["clarified butter","indian ghee"],"source":"curated"},
    {"food_id":"food_289","name_he":"שמן שומשום","name_en":"Sesame Oil",
     "category":"fat","calories_kcal":884.0,"protein_g":0.0,"carbs_g":0.0,"fat_g":100.0,
     "default_unit":"tablespoon","default_serving_g":14.0,"aliases_he":["שמן שומשום קלוי","שמן אסיאתי"],"aliases_en":["toasted sesame oil","asian sesame oil"],"source":"curated"},
    {"food_id":"food_290","name_he":"שמן אבוקדו","name_en":"Avocado Oil",
     "category":"fat","calories_kcal":884.0,"protein_g":0.0,"carbs_g":0.0,"fat_g":100.0,
     "default_unit":"tablespoon","default_serving_g":14.0,"aliases_he":[],"aliases_en":["cold pressed avocado oil"],"source":"curated"},
    {"food_id":"food_291","name_he":"מרגרינה","name_en":"Margarine",
     "category":"fat","calories_kcal":720.0,"protein_g":0.1,"carbs_g":0.4,"fat_g":81.0,
     "default_unit":"tablespoon","default_serving_g":14.0,"aliases_he":["מרגרינה קשה","שומן צמחי"],"aliases_en":["vegetable spread","non-dairy butter"],"source":"curated"},

    # ── SPICES & HERBS ────────────────────────────────────────────────────────
    {"food_id":"food_292","name_he":"פפריקה","name_en":"Paprika",
     "category":"condiment","calories_kcal":282.0,"protein_g":14.0,"carbs_g":54.0,"fat_g":13.0,
     "fiber_g":34.0,"default_unit":"teaspoon","default_serving_g":2.5,"aliases_he":["פפריקה מעושנת","פפריקה מתוקה"],"aliases_en":["smoked paprika","sweet paprika"],"source":"curated"},
    {"food_id":"food_293","name_he":"כמון","name_en":"Cumin",
     "category":"condiment","calories_kcal":375.0,"protein_g":18.0,"carbs_g":44.0,"fat_g":22.0,
     "fiber_g":11.0,"default_unit":"teaspoon","default_serving_g":2.5,"aliases_he":["כמון טחון"],"aliases_en":["ground cumin","cumin seeds"],"source":"curated"},
    {"food_id":"food_294","name_he":"כורכום","name_en":"Turmeric",
     "category":"condiment","calories_kcal":312.0,"protein_g":9.7,"carbs_g":68.0,"fat_g":3.3,
     "fiber_g":22.0,"default_unit":"teaspoon","default_serving_g":2.5,"aliases_he":["כרכום"],"aliases_en":["ground turmeric","curcuma powder"],"source":"curated"},
    {"food_id":"food_295","name_he":"קינמון","name_en":"Cinnamon",
     "category":"condiment","calories_kcal":247.0,"protein_g":4.0,"carbs_g":81.0,"fat_g":1.2,
     "fiber_g":53.0,"default_unit":"teaspoon","default_serving_g":2.5,"aliases_he":["קינמון טחון"],"aliases_en":["ground cinnamon","ceylon cinnamon"],"source":"curated"},
    {"food_id":"food_296","name_he":"בזיליקום","name_en":"Basil",
     "category":"condiment","calories_kcal":23.0,"protein_g":3.2,"carbs_g":2.7,"fat_g":0.6,
     "fiber_g":1.6,"default_unit":"teaspoon","default_serving_g":2.0,"aliases_he":["עלי בזיליקום","בזיליקום טרי"],"aliases_en":["fresh basil","sweet basil"],"source":"curated"},
    {"food_id":"food_297","name_he":"אורגנו","name_en":"Oregano",
     "category":"condiment","calories_kcal":265.0,"protein_g":9.0,"carbs_g":69.0,"fat_g":4.3,
     "fiber_g":43.0,"default_unit":"teaspoon","default_serving_g":1.0,"aliases_he":["אורגנום","אורגנו יבש"],"aliases_en":["dried oregano","italian oregano"],"source":"curated"},
    {"food_id":"food_298","name_he":"רוזמרין","name_en":"Rosemary",
     "category":"condiment","calories_kcal":131.0,"protein_g":3.3,"carbs_g":21.0,"fat_g":5.9,
     "fiber_g":14.0,"default_unit":"teaspoon","default_serving_g":1.5,"aliases_he":["עשבי תיבול","שיח רוזמרין"],"aliases_en":["fresh rosemary","dried rosemary"],"source":"curated"},
    {"food_id":"food_299","name_he":"קארי","name_en":"Curry Powder",
     "category":"condiment","calories_kcal":325.0,"protein_g":14.0,"carbs_g":58.0,"fat_g":14.0,
     "fiber_g":33.0,"default_unit":"teaspoon","default_serving_g":2.5,"aliases_he":["אבקת קארי","תבלין קארי"],"aliases_en":["madras curry","indian curry blend"],"source":"curated"},

    # ── INTERNATIONAL / ETHNIC ────────────────────────────────────────────────
    {"food_id":"food_300","name_he":"מיסו","name_en":"Miso Paste",
     "category":"condiment","calories_kcal":199.0,"protein_g":12.0,"carbs_g":27.0,"fat_g":6.0,
     "fiber_g":5.4,"default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["מרק מיסו"],"aliases_en":["white miso","red miso","shiro miso"],"source":"curated"},
    {"food_id":"food_301","name_he":"נורי","name_en":"Nori Seaweed",
     "category":"vegetable","calories_kcal":35.0,"protein_g":5.8,"carbs_g":4.4,"fat_g":0.3,
     "fiber_g":0.3,"default_unit":"unit","default_serving_g":2.5,"aliases_he":["אצת נורי","אצה יפנית"],"aliases_en":["dried seaweed","sushi nori"],"source":"curated"},
    {"food_id":"food_302","name_he":"קוקוס חלב","name_en":"Coconut Milk",
     "category":"other","calories_kcal":230.0,"protein_g":2.3,"carbs_g":5.5,"fat_g":24.0,
     "fiber_g":2.2,"default_unit":"cup","default_serving_g":240.0,"aliases_he":["חלב קוקוס","קרם קוקוס"],"aliases_en":["full fat coconut milk","coconut cream"],"source":"curated"},
    {"food_id":"food_303","name_he":"אבקת קקאו","name_en":"Cocoa Powder",
     "category":"other","calories_kcal":228.0,"protein_g":20.0,"carbs_g":58.0,"fat_g":14.0,
     "fiber_g":33.0,"default_unit":"tablespoon","default_serving_g":10.0,"aliases_he":["אבקת שוקולד","קקאו"],"aliases_en":["unsweetened cocoa","cacao powder"],"source":"curated"},
    {"food_id":"food_304","name_he":"טחינה מוכנה לאכילה","name_en":"Ready-to-Eat Tahini",
     "category":"condiment","calories_kcal":170.0,"protein_g":5.0,"carbs_g":8.0,"fat_g":14.0,
     "fiber_g":1.5,"default_unit":"tablespoon","default_serving_g":30.0,"aliases_he":["טחינה מדוללת","טחינה לאכילה"],"aliases_en":["tahini sauce","diluted tahini"],"source":"curated"},
    {"food_id":"food_305","name_he":"אינג'ירה","name_en":"Injera",
     "category":"grain","calories_kcal":89.0,"protein_g":3.6,"carbs_g":18.0,"fat_g":0.6,
     "fiber_g":3.0,"default_unit":"unit","default_serving_g":60.0,"aliases_he":["לחם אתיופי","אינג'רה"],"aliases_en":["ethiopian flatbread","teff bread"],"source":"curated"},
    {"food_id":"food_306","name_he":"גאודה מעושן","name_en":"Smoked Gouda",
     "category":"dairy","calories_kcal":370.0,"protein_g":23.0,"carbs_g":3.0,"fat_g":30.0,
     "default_unit":"slice","default_serving_g":20.0,"aliases_he":["גבינה מעושנת"],"aliases_en":["smoked cheese","aged smoked gouda"],"source":"curated"},
    {"food_id":"food_307","name_he":"טמפה מוקפץ","name_en":"Stir-Fried Tempeh",
     "category":"protein","calories_kcal":215.0,"protein_g":18.0,"carbs_g":10.0,"fat_g":12.0,
     "default_serving_g":100.0,"aliases_he":["טמפה מבושל"],"aliases_en":["cooked tempeh","tempeh stir fry"],"source":"curated"},
    {"food_id":"food_308","name_he":"קארי מסאמן","name_en":"Massaman Curry",
     "category":"other","calories_kcal":165.0,"protein_g":7.0,"carbs_g":15.0,"fat_g":9.0,
     "fiber_g":2.0,"default_serving_g":300.0,"aliases_he":["קארי תאילנדי","קארי ירוק"],"aliases_en":["thai green curry","thai red curry"],"source":"curated"},
    {"food_id":"food_309","name_he":"סמוסות","name_en":"Samosa",
     "category":"other","calories_kcal":308.0,"protein_g":5.8,"carbs_g":31.0,"fat_g":18.0,
     "default_unit":"unit","default_serving_g":50.0,"aliases_he":["סמוסה","מאפה הודי"],"aliases_en":["vegetable samosa","fried samosa"],"source":"curated"},
    {"food_id":"food_310","name_he":"מנגו לסי","name_en":"Mango Lassi",
     "category":"beverage","calories_kcal":80.0,"protein_g":2.5,"carbs_g":16.0,"fat_g":1.2,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["לאסי מנגו","שייק יוגורט מנגו"],"aliases_en":["yogurt mango drink","indian mango lassi"],"source":"curated"},
]
