"""
Extended food library batch 3 — food_411 onward. All values per 100g.
"""
from typing import Dict, List

EXTENDED_FOODS_3: List[Dict] = [

    # ── PROTEINS – DELI & CURED ───────────────────────────────────────────────
    {"food_id":"food_411","name_he":"מורטדלה","name_en":"Mortadella",
     "category":"protein","calories_kcal":311.0,"protein_g":14.0,"carbs_g":2.8,"fat_g":27.0,
     "default_unit":"slice","default_serving_g":30.0,"aliases_he":["בולוניה","נקניק איטלקי"],"aliases_en":["bologna","italian sausage"],"source":"curated"},
    {"food_id":"food_412","name_he":"קוֹרְנְ בֵּיף","name_en":"Corned Beef",
     "category":"protein","calories_kcal":250.0,"protein_g":18.0,"carbs_g":0.5,"fat_g":19.0,
     "default_serving_g":100.0,"aliases_he":["בקר מקופסה"],"aliases_en":["canned corned beef","salt beef"],"source":"curated"},
    {"food_id":"food_413","name_he":"לחם בשר","name_en":"Meatloaf",
     "category":"protein","calories_kcal":230.0,"protein_g":16.0,"carbs_g":10.0,"fat_g":13.0,
     "default_serving_g":120.0,"aliases_he":["עוגת בשר"],"aliases_en":["classic meatloaf","beef meatloaf"],"source":"curated"},
    {"food_id":"food_414","name_he":"קציצות","name_en":"Meatballs",
     "category":"protein","calories_kcal":248.0,"protein_g":18.0,"carbs_g":7.0,"fat_g":17.0,
     "default_unit":"unit","default_serving_g":30.0,"aliases_he":["כדורי בשר","קציצות בקר"],"aliases_en":["beef meatballs","spaghetti meatballs"],"source":"curated"},
    {"food_id":"food_415","name_he":"פפריקש עוף","name_en":"Chicken Paprikash",
     "category":"other","calories_kcal":180.0,"protein_g":15.0,"carbs_g":6.0,"fat_g":11.0,
     "default_serving_g":250.0,"aliases_he":["עוף פפריקה","עוף ברוטב"],"aliases_en":["chicken in paprika sauce","hungarian chicken"],"source":"curated"},
    {"food_id":"food_416","name_he":"טונה טרייה","name_en":"Fresh Tuna Steak",
     "category":"protein","calories_kcal":144.0,"protein_g":30.0,"carbs_g":0.0,"fat_g":2.5,
     "default_serving_g":150.0,"aliases_he":["סטייק טונה","טונה אדומה"],"aliases_en":["ahi tuna","yellowfin tuna steak"],"source":"curated"},
    {"food_id":"food_417","name_he":"פיש קייק","name_en":"Fish Cake",
     "category":"protein","calories_kcal":175.0,"protein_g":14.0,"carbs_g":14.0,"fat_g":7.0,
     "default_unit":"unit","default_serving_g":80.0,"aliases_he":["קציצת דגים","פטיסייה דגים"],"aliases_en":["thai fish cake","salmon cake"],"source":"curated"},
    {"food_id":"food_418","name_he":"בייף ג'רקי","name_en":"Beef Jerky",
     "category":"protein","calories_kcal":410.0,"protein_g":55.0,"carbs_g":9.0,"fat_g":16.0,
     "fiber_g":0.5,"default_serving_g":30.0,"aliases_he":["בשר מיובש","ג'רקי"],"aliases_en":["dried beef","meat jerky"],"source":"curated"},

    # ── PLANT-BASED PROTEINS ──────────────────────────────────────────────────
    {"food_id":"food_419","name_he":"בורגר ירק","name_en":"Veggie Burger",
     "category":"protein","calories_kcal":224.0,"protein_g":16.0,"carbs_g":15.0,"fat_g":11.0,
     "fiber_g":4.0,"default_unit":"unit","default_serving_g":100.0,"aliases_he":["המבורגר טבעוני","בורגר צמחי"],"aliases_en":["plant-based burger","beyond burger","impossible burger"],"source":"curated"},
    {"food_id":"food_420","name_he":"נקניקיית טופו","name_en":"Tofu Sausage",
     "category":"protein","calories_kcal":126.0,"protein_g":10.0,"carbs_g":8.0,"fat_g":6.0,
     "default_unit":"unit","default_serving_g":60.0,"aliases_he":["נקניקייה טבעונית","נקניקיית סויה"],"aliases_en":["vegan sausage","soy frank"],"source":"curated"},
    {"food_id":"food_421","name_he":"ציפי'ז מתח","name_en":"Jackfruit Pulled Pork",
     "category":"protein","calories_kcal":95.0,"protein_g":1.7,"carbs_g":23.0,"fat_g":0.6,
     "default_serving_g":150.0,"aliases_he":["ג'קפרוט מושך","בשר צמחי"],"aliases_en":["pulled jackfruit","vegan pulled pork"],"source":"curated"},

    # ── ADDITIONAL CHEESES & DAIRY ────────────────────────────────────────────
    {"food_id":"food_422","name_he":"קשקבל","name_en":"Kashkaval Cheese",
     "category":"dairy","calories_kcal":380.0,"protein_g":24.0,"carbs_g":1.0,"fat_g":31.0,
     "default_unit":"slice","default_serving_g":25.0,"aliases_he":["קשקוואל"],"aliases_en":["kasseri cheese","balkan cheese"],"source":"curated"},
    {"food_id":"food_423","name_he":"חלומי","name_en":"Halloumi",
     "category":"dairy","calories_kcal":320.0,"protein_g":21.0,"carbs_g":0.5,"fat_g":26.0,
     "default_serving_g":80.0,"aliases_he":["גבינת הלומי","גבינה קפריסאית"],"aliases_en":["grilled halloumi","cypriot cheese"],"source":"curated"},
    {"food_id":"food_424","name_he":"פנאר","name_en":"Paneer",
     "category":"dairy","calories_kcal":265.0,"protein_g":18.0,"carbs_g":1.2,"fat_g":21.0,
     "default_serving_g":100.0,"aliases_he":["גבינה הודית","פניר"],"aliases_en":["indian cottage cheese","fresh paneer"],"source":"curated"},
    {"food_id":"food_425","name_he":"גבינה מעושנת","name_en":"Smoked Cheese",
     "category":"dairy","calories_kcal":375.0,"protein_g":23.0,"carbs_g":2.0,"fat_g":31.0,
     "default_unit":"slice","default_serving_g":20.0,"aliases_he":["גבינה מעושנת גאודה"],"aliases_en":["smoked gouda","smoked cheddar"],"source":"curated"},
    {"food_id":"food_426","name_he":"גבינת הוּמוֹס","name_en":"Havarti Cheese",
     "category":"dairy","calories_kcal":371.0,"protein_g":23.0,"carbs_g":2.0,"fat_g":30.0,
     "default_unit":"slice","default_serving_g":20.0,"aliases_he":["גבינה הולנדית"],"aliases_en":["danish havarti","butter cheese"],"source":"curated"},
    {"food_id":"food_427","name_he":"פרוּמאז' בלאן","name_en":"Fromage Blanc",
     "category":"dairy","calories_kcal":77.0,"protein_g":8.0,"carbs_g":4.0,"fat_g":3.0,
     "default_serving_g":100.0,"aliases_he":["גבינה לבנה צרפתית"],"aliases_en":["french white cheese","quark"],"source":"curated"},
    {"food_id":"food_428","name_he":"קוורק","name_en":"Quark",
     "category":"dairy","calories_kcal":65.0,"protein_g":11.0,"carbs_g":4.0,"fat_g":0.2,
     "default_serving_g":150.0,"aliases_he":["גבינת קוורק"],"aliases_en":["skyr","icelandic yogurt","german quark"],"source":"curated"},

    # ── MORE GRAINS / STARCHES ────────────────────────────────────────────────
    {"food_id":"food_429","name_he":"אמרנט מבושל","name_en":"Amaranth Cooked",
     "category":"grain","calories_kcal":102.0,"protein_g":4.0,"carbs_g":19.0,"fat_g":1.6,
     "fiber_g":2.1,"default_serving_g":150.0,"aliases_he":["אמרנט"],"aliases_en":["whole grain amaranth","ancient grain amaranth"],"source":"curated"},
    {"food_id":"food_430","name_he":"דוחן מבושל","name_en":"Millet Cooked",
     "category":"grain","calories_kcal":119.0,"protein_g":3.5,"carbs_g":23.0,"fat_g":1.0,
     "fiber_g":1.3,"default_serving_g":150.0,"aliases_he":["דחן"],"aliases_en":["cooked millet","pearl millet"],"source":"curated"},
    {"food_id":"food_431","name_he":"פריקה","name_en":"Freekeh",
     "category":"grain","calories_kcal":353.0,"protein_g":12.0,"carbs_g":65.0,"fat_g":2.7,
     "fiber_g":16.0,"default_serving_g":150.0,"aliases_he":["פרכה","חיטה ירוקה"],"aliases_en":["roasted green wheat","frik"],"source":"curated"},
    {"food_id":"food_432","name_he":"שעורה מבושלת","name_en":"Pearl Barley",
     "category":"grain","calories_kcal":123.0,"protein_g":2.3,"carbs_g":28.0,"fat_g":0.4,
     "fiber_g":3.8,"default_serving_g":150.0,"aliases_he":["גריסי פנינה","שעורה"],"aliases_en":["barley cooked","pot barley"],"source":"curated"},
    {"food_id":"food_433","name_he":"נוּגָט","name_en":"Nougat",
     "category":"other","calories_kcal":393.0,"protein_g":4.0,"carbs_g":81.0,"fat_g":7.5,
     "default_serving_g":30.0,"aliases_he":["נוגאט","טורון"],"aliases_en":["honey nougat","almond nougat","torrone"],"source":"curated"},
    {"food_id":"food_434","name_he":"פסטה אורז","name_en":"Rice Pasta",
     "category":"grain","calories_kcal":130.0,"protein_g":2.5,"carbs_g":29.0,"fat_g":0.3,
     "fiber_g":1.5,"default_serving_g":180.0,"aliases_he":["פסטה ללא גלוטן"],"aliases_en":["gluten-free pasta","rice penne"],"source":"curated"},
    {"food_id":"food_435","name_he":"פסטה מחיטת כוסמין","name_en":"Spelt Pasta",
     "category":"grain","calories_kcal":135.0,"protein_g":6.0,"carbs_g":25.0,"fat_g":1.2,
     "fiber_g":3.5,"default_serving_g":180.0,"aliases_he":["פסטה כוסמין"],"aliases_en":["ancient grain pasta"],"source":"curated"},
    {"food_id":"food_436","name_he":"לחמניה","name_en":"Dinner Roll",
     "category":"grain","calories_kcal":283.0,"protein_g":9.0,"carbs_g":55.0,"fat_g":3.5,
     "fiber_g":1.8,"default_unit":"unit","default_serving_g":35.0,"aliases_he":["לחמנייה","כיכר קטנה"],"aliases_en":["bread roll","hamburger bun","hot dog bun"],"source":"curated"},
    {"food_id":"food_437","name_he":"לחמנייה קוקי","name_en":"Brioche Bun",
     "category":"grain","calories_kcal":349.0,"protein_g":8.0,"carbs_g":46.0,"fat_g":15.0,
     "default_unit":"unit","default_serving_g":60.0,"aliases_he":["לחמנייה עשירה"],"aliases_en":["enriched bun","eggy bun"],"source":"curated"},

    # ── MORE VEGETABLES ───────────────────────────────────────────────────────
    {"food_id":"food_438","name_he":"ברוקוליני","name_en":"Broccolini",
     "category":"vegetable","calories_kcal":35.0,"protein_g":3.5,"carbs_g":6.0,"fat_g":0.5,
     "fiber_g":3.0,"default_serving_g":100.0,"aliases_he":["ברוקולי מיני"],"aliases_en":["baby broccoli","tenderstem broccoli"],"source":"curated"},
    {"food_id":"food_439","name_he":"פלפלת","name_en":"Bell Pepper Yellow",
     "category":"vegetable","calories_kcal":27.0,"protein_g":1.0,"carbs_g":6.3,"fat_g":0.2,
     "fiber_g":0.9,"default_unit":"unit","default_serving_g":150.0,"aliases_he":["פלפל צהוב"],"aliases_en":["yellow capsicum","sweet yellow pepper"],"source":"curated"},
    {"food_id":"food_440","name_he":"כרוב ניצנים מרוטב","name_en":"Roasted Brussels Sprouts",
     "category":"vegetable","calories_kcal":55.0,"protein_g":3.5,"carbs_g":9.0,"fat_g":1.5,
     "fiber_g":3.5,"default_serving_g":150.0,"aliases_he":["ניצני בריסל צלויים"],"aliases_en":["oven-roasted brussels","crispy sprouts"],"source":"curated"},
    {"food_id":"food_441","name_he":"גוּרְגֶ'ט","name_en":"Savoy Cabbage",
     "category":"vegetable","calories_kcal":27.0,"protein_g":2.0,"carbs_g":6.1,"fat_g":0.1,
     "fiber_g":3.1,"default_serving_g":100.0,"aliases_he":["כרוב מקורזל"],"aliases_en":["curly cabbage","wrinkled cabbage"],"source":"curated"},
    {"food_id":"food_442","name_he":"שומרת","name_en":"Fennel",
     "category":"vegetable","calories_kcal":31.0,"protein_g":1.2,"carbs_g":7.3,"fat_g":0.2,
     "fiber_g":3.1,"default_unit":"unit","default_serving_g":100.0,"aliases_he":["שומר","שומרת ים"],"aliases_en":["fresh fennel","anise fennel","florence fennel"],"source":"curated"},
    {"food_id":"food_443","name_he":"ג'יקמה","name_en":"Jicama",
     "category":"vegetable","calories_kcal":38.0,"protein_g":0.7,"carbs_g":9.0,"fat_g":0.1,
     "fiber_g":4.9,"default_serving_g":100.0,"aliases_he":["צנון מקסיקני"],"aliases_en":["mexican turnip","yam bean"],"source":"curated"},
    {"food_id":"food_444","name_he":"כרפס שורש","name_en":"Celeriac",
     "category":"vegetable","calories_kcal":42.0,"protein_g":1.5,"carbs_g":9.2,"fat_g":0.3,
     "fiber_g":1.8,"default_serving_g":100.0,"aliases_he":["קנרוטש"],"aliases_en":["celery root","knob celery"],"source":"curated"},
    {"food_id":"food_445","name_he":"פרסניפ","name_en":"Parsnip",
     "category":"vegetable","calories_kcal":75.0,"protein_g":1.2,"carbs_g":18.0,"fat_g":0.3,
     "fiber_g":4.9,"default_serving_g":100.0,"aliases_he":["פסנרנ"],"aliases_en":["roasted parsnip","white parsnip"],"source":"curated"},
    {"food_id":"food_446","name_he":"מהאוני ים","name_en":"Wakame",
     "category":"vegetable","calories_kcal":45.0,"protein_g":3.0,"carbs_g":9.1,"fat_g":0.6,
     "fiber_g":0.5,"default_serving_g":30.0,"aliases_he":["אצות ים ירוקות"],"aliases_en":["seaweed salad","green seaweed"],"source":"curated"},
    {"food_id":"food_447","name_he":"עגבנייה מסוג כרם","name_en":"Heirloom Tomato",
     "category":"vegetable","calories_kcal":18.0,"protein_g":0.9,"carbs_g":3.9,"fat_g":0.2,
     "fiber_g":1.2,"default_unit":"unit","default_serving_g":150.0,"aliases_he":["עגבנייה עתיקה","עגבנייה גדולה"],"aliases_en":["beefsteak tomato","heritage tomato"],"source":"curated"},
    {"food_id":"food_448","name_he":"חוחובה","name_en":"Kohlrabi",
     "category":"vegetable","calories_kcal":27.0,"protein_g":1.7,"carbs_g":6.2,"fat_g":0.1,
     "fiber_g":3.6,"default_unit":"unit","default_serving_g":150.0,"aliases_he":["כרוב נפוח","קולרבי"],"aliases_en":["german turnip","purple kohlrabi"],"source":"curated"},
    {"food_id":"food_449","name_he":"מקשה","name_en":"Opo Squash",
     "category":"vegetable","calories_kcal":14.0,"protein_g":0.6,"carbs_g":3.4,"fat_g":0.0,
     "fiber_g":0.5,"default_serving_g":200.0,"aliases_he":["דלעת ארוכה","קישוא ארוך"],"aliases_en":["bottle gourd","lauki"],"source":"curated"},
    {"food_id":"food_450","name_he":"אבוקדו קטן","name_en":"Baby Avocado",
     "category":"fruit","calories_kcal":160.0,"protein_g":2.0,"carbs_g":9.0,"fat_g":15.0,
     "fiber_g":6.7,"default_unit":"unit","default_serving_g":80.0,"aliases_he":["אבוקדו קטן","פינקרטון"],"aliases_en":["small avocado","cocktail avocado"],"source":"curated"},

    # ── INTERNATIONAL DISHES (more) ───────────────────────────────────────────
    {"food_id":"food_451","name_he":"טאבולה","name_en":"Tabbouleh",
     "category":"other","calories_kcal":82.0,"protein_g":2.2,"carbs_g":11.0,"fat_g":4.0,
     "fiber_g":3.5,"default_serving_g":150.0,"aliases_he":["טבולה","סלט פטרוזיליה"],"aliases_en":["parsley salad","levantine tabbouleh"],"source":"curated"},
    {"food_id":"food_452","name_he":"פאלאפל אפוי","name_en":"Baked Falafel",
     "category":"other","calories_kcal":240.0,"protein_g":11.0,"carbs_g":30.0,"fat_g":8.0,
     "fiber_g":6.0,"default_unit":"unit","default_serving_g":17.0,"aliases_he":["פלאפל אפוי","פלאפל בריאות"],"aliases_en":["healthy falafel","oven baked falafel"],"source":"curated"},
    {"food_id":"food_453","name_he":"פרו","name_en":"Peruvian Ceviche",
     "category":"other","calories_kcal":106.0,"protein_g":15.0,"carbs_g":6.0,"fat_g":3.0,
     "fiber_g":0.8,"default_serving_g":200.0,"aliases_he":["סביצ'ה","דג נא בלימון"],"aliases_en":["ceviche","lime-marinated fish"],"source":"curated"},
    {"food_id":"food_454","name_he":"טבולה קינואה","name_en":"Quinoa Tabbouleh",
     "category":"other","calories_kcal":98.0,"protein_g":4.0,"carbs_g":14.0,"fat_g":3.5,
     "fiber_g":3.0,"default_serving_g":150.0,"aliases_he":["טבולה קינואה","סלט קינואה"],"aliases_en":["quinoa salad","grain salad"],"source":"curated"},
    {"food_id":"food_455","name_he":"קוּשְׁקוּשׁ","name_en":"Israeli Couscous",
     "category":"grain","calories_kcal":178.0,"protein_g":6.0,"carbs_g":36.0,"fat_g":1.0,
     "fiber_g":2.5,"default_serving_g":150.0,"aliases_he":["קוסקוס ישראלי","פתיתים"],"aliases_en":["ptitim","pearl couscous","ben-gurion rice"],"source":"curated"},
    {"food_id":"food_456","name_he":"ים טיכוני","name_en":"Mediterranean Salad",
     "category":"other","calories_kcal":90.0,"protein_g":3.0,"carbs_g":8.0,"fat_g":5.5,
     "fiber_g":3.0,"default_serving_g":200.0,"aliases_he":["סלט ים תיכוני","סלט יווני"],"aliases_en":["greek salad","horiatiki","village salad"],"source":"curated"},
    {"food_id":"food_457","name_he":"סלט נייסואז","name_en":"Salad Niçoise",
     "category":"other","calories_kcal":130.0,"protein_g":10.0,"carbs_g":8.0,"fat_g":6.5,
     "fiber_g":2.5,"default_serving_g":250.0,"aliases_he":["סלט נישואז","סלט טונה פרנסואז"],"aliases_en":["nicoise salad","tuna salad nicoise"],"source":"curated"},
    {"food_id":"food_458","name_he":"קופטה","name_en":"Kofta",
     "category":"other","calories_kcal":246.0,"protein_g":18.0,"carbs_g":5.0,"fat_g":17.0,
     "default_unit":"unit","default_serving_g":80.0,"aliases_he":["כדורי בשר ים תיכוניים","קבב כדורי"],"aliases_en":["middle eastern meatballs","moroccan kefta"],"source":"curated"},
    {"food_id":"food_459","name_he":"ג'אמבלאיה","name_en":"Jambalaya",
     "category":"other","calories_kcal":185.0,"protein_g":10.0,"carbs_g":22.0,"fat_g":6.0,
     "fiber_g":1.8,"default_serving_g":300.0,"aliases_he":[],"aliases_en":["creole jambalaya","cajun rice dish"],"source":"curated"},
    {"food_id":"food_460","name_he":"צ'ילי קון קרנה","name_en":"Chili Con Carne",
     "category":"other","calories_kcal":136.0,"protein_g":11.0,"carbs_g":12.0,"fat_g":5.0,
     "fiber_g":4.5,"default_serving_g":300.0,"aliases_he":["צ'ילי בקר","תבשיל צ'ילי"],"aliases_en":["beef chili","tex-mex chili"],"source":"curated"},
    {"food_id":"food_461","name_he":"מינסטרונה","name_en":"Minestrone",
     "category":"other","calories_kcal":55.0,"protein_g":2.5,"carbs_g":9.5,"fat_g":1.2,
     "fiber_g":2.5,"default_serving_g":350.0,"aliases_he":["מרק ירקות איטלקי"],"aliases_en":["italian vegetable soup","pasta e fagioli"],"source":"curated"},
    {"food_id":"food_462","name_he":"קרם ברוקולי","name_en":"Cream of Broccoli Soup",
     "category":"other","calories_kcal":57.0,"protein_g":2.5,"carbs_g":6.5,"fat_g":2.5,
     "fiber_g":1.5,"default_serving_g":300.0,"aliases_he":["מרק ברוקולי","פורי ברוקולי"],"aliases_en":["broccoli cheddar soup","broccoli bisque"],"source":"curated"},
    {"food_id":"food_463","name_he":"רטטוי","name_en":"Ratatouille",
     "category":"other","calories_kcal":63.0,"protein_g":1.5,"carbs_g":10.0,"fat_g":2.5,
     "fiber_g":3.0,"default_serving_g":200.0,"aliases_he":["ירקות מדיטרניים"],"aliases_en":["french vegetable stew","provencal ratatouille"],"source":"curated"},
    {"food_id":"food_464","name_he":"קִישׁ","name_en":"Quiche Lorraine",
     "category":"other","calories_kcal":320.0,"protein_g":10.0,"carbs_g":18.0,"fat_g":23.0,
     "fiber_g":0.8,"default_unit":"slice","default_serving_g":120.0,"aliases_he":["קיש","פאי גבינה ובייקון"],"aliases_en":["bacon quiche","savory tart"],"source":"curated"},

    # ── SANDWICHES & WRAPS ────────────────────────────────────────────────────
    {"food_id":"food_465","name_he":"כריך טונה","name_en":"Tuna Sandwich",
     "category":"other","calories_kcal":175.0,"protein_g":14.0,"carbs_g":20.0,"fat_g":5.0,
     "fiber_g":1.5,"default_serving_g":200.0,"aliases_he":["סנדוויץ' טונה"],"aliases_en":["tuna salad sandwich","tuna melt"],"source":"curated"},
    {"food_id":"food_466","name_he":"כריך הודו","name_en":"Turkey Sandwich",
     "category":"other","calories_kcal":163.0,"protein_g":13.0,"carbs_g":20.0,"fat_g":3.5,
     "fiber_g":2.0,"default_serving_g":200.0,"aliases_he":["סנדוויץ' הודו"],"aliases_en":["turkey club","deli turkey sandwich"],"source":"curated"},
    {"food_id":"food_467","name_he":"ראפ עוף","name_en":"Chicken Wrap",
     "category":"other","calories_kcal":185.0,"protein_g":14.0,"carbs_g":18.0,"fat_g":6.0,
     "fiber_g":2.0,"default_serving_g":220.0,"aliases_he":["ראפ עוף","לאפה עוף"],"aliases_en":["grilled chicken wrap","caesar wrap"],"source":"curated"},
    {"food_id":"food_468","name_he":"פנינה","name_en":"Panini",
     "category":"other","calories_kcal":260.0,"protein_g":12.0,"carbs_g":32.0,"fat_g":9.0,
     "fiber_g":1.5,"default_unit":"unit","default_serving_g":200.0,"aliases_he":["פאניני","כריך חם"],"aliases_en":["pressed sandwich","toasted panini"],"source":"curated"},
    {"food_id":"food_469","name_he":"לחמנייה גבינה","name_en":"Grilled Cheese Sandwich",
     "category":"other","calories_kcal":361.0,"protein_g":15.0,"carbs_g":38.0,"fat_g":17.0,
     "default_unit":"unit","default_serving_g":200.0,"aliases_he":["טוסט גבינה","לחם מטוגן עם גבינה"],"aliases_en":["cheese melt","toasted cheese"],"source":"curated"},
    {"food_id":"food_470","name_he":"בייגלה עם גבינה","name_en":"Bagel with Cream Cheese",
     "category":"other","calories_kcal":257.0,"protein_g":9.0,"carbs_g":39.0,"fat_g":8.0,
     "fiber_g":1.5,"default_unit":"unit","default_serving_g":150.0,"aliases_he":["בייגל עם גבינת שמנת"],"aliases_en":["cream cheese bagel","lox bagel"],"source":"curated"},

    # ── DESSERTS & SWEETS ─────────────────────────────────────────────────────
    {"food_id":"food_471","name_he":"מוּס שוקולד","name_en":"Chocolate Mousse",
     "category":"other","calories_kcal":260.0,"protein_g":4.5,"carbs_g":25.0,"fat_g":16.0,
     "default_serving_g":100.0,"aliases_he":["מוס שוקולד","קרם שוקולד"],"aliases_en":["dark chocolate mousse","whipped chocolate"],"source":"curated"},
    {"food_id":"food_472","name_he":"פוּדינג וניל","name_en":"Vanilla Pudding",
     "category":"other","calories_kcal":130.0,"protein_g":3.0,"carbs_g":23.0,"fat_g":3.0,
     "default_serving_g":120.0,"aliases_he":["פודינג","מג'ל וניל"],"aliases_en":["custard pudding","instant pudding"],"source":"curated"},
    {"food_id":"food_473","name_he":"מהלבייה","name_en":"Muhallebi",
     "category":"other","calories_kcal":120.0,"protein_g":3.0,"carbs_g":21.0,"fat_g":3.0,
     "default_serving_g":150.0,"aliases_he":["מלבי","קרם חלב"],"aliases_en":["malabi","milk pudding","rose water cream"],"source":"curated"},
    {"food_id":"food_474","name_he":"קעקאו-חלב","name_en":"Rice Pudding",
     "category":"other","calories_kcal":130.0,"protein_g":2.5,"carbs_g":25.0,"fat_g":2.8,
     "default_serving_g":150.0,"aliases_he":["פודינג אורז","ריז לה"],"aliases_en":["rice pudding","arroz con leche"],"source":"curated"},
    {"food_id":"food_475","name_he":"עוגת לבן","name_en":"Pound Cake",
     "category":"other","calories_kcal":395.0,"protein_g":6.0,"carbs_g":52.0,"fat_g":18.0,
     "default_unit":"slice","default_serving_g":80.0,"aliases_he":["עוגת חמאה","קייק אנגלי"],"aliases_en":["butter cake","vanilla loaf cake"],"source":"curated"},
    {"food_id":"food_476","name_he":"עוגת תפוחים","name_en":"Apple Crumble",
     "category":"other","calories_kcal":214.0,"protein_g":2.5,"carbs_g":36.0,"fat_g":7.5,
     "fiber_g":2.0,"default_serving_g":150.0,"aliases_he":["קראמבל תפוחים"],"aliases_en":["apple crisp","fruit crumble"],"source":"curated"},
    {"food_id":"food_477","name_he":"גלידת מחית","name_en":"Gelato",
     "category":"other","calories_kcal":160.0,"protein_g":3.2,"carbs_g":27.0,"fat_g":4.8,
     "default_serving_g":100.0,"aliases_he":["ג'לאטו","גלידה איטלקית"],"aliases_en":["italian gelato","artisan ice cream"],"source":"curated"},
    {"food_id":"food_478","name_he":"מקרון","name_en":"Macaron",
     "category":"other","calories_kcal":457.0,"protein_g":6.5,"carbs_g":71.0,"fat_g":17.0,
     "default_unit":"unit","default_serving_g":15.0,"aliases_he":["מקארון","פטיפור"],"aliases_en":["french macaron","macaroon"],"source":"curated"},
    {"food_id":"food_479","name_he":"פרלין שוקולד","name_en":"Chocolate Truffle",
     "category":"other","calories_kcal":500.0,"protein_g":4.5,"carbs_g":50.0,"fat_g":30.0,
     "default_unit":"unit","default_serving_g":15.0,"aliases_he":["טראפל","בונבון"],"aliases_en":["chocolate bonbon","ganache truffle"],"source":"curated"},
    {"food_id":"food_480","name_he":"שוקולד לבן מלא","name_en":"White Chocolate Bar",
     "category":"other","calories_kcal":539.0,"protein_g":5.9,"carbs_g":59.2,"fat_g":32.0,
     "default_serving_g":30.0,"aliases_he":["שוקולד לבן שלם"],"aliases_en":["white chocolate with nuts","milky bar"],"source":"curated"},

    # ── SNACKS & EXTRAS ───────────────────────────────────────────────────────
    {"food_id":"food_481","name_he":"מייזה מיקס","name_en":"Trail Mix",
     "category":"other","calories_kcal":460.0,"protein_g":12.0,"carbs_g":46.0,"fat_g":27.0,
     "fiber_g":6.0,"default_serving_g":40.0,"aliases_he":["תערובת אגוזים ופירות","תערובת לטיול"],"aliases_en":["nuts and raisins mix","hiker mix"],"source":"curated"},
    {"food_id":"food_482","name_he":"צ'יפס בטטה","name_en":"Sweet Potato Fries",
     "category":"other","calories_kcal":185.0,"protein_g":1.6,"carbs_g":28.0,"fat_g":7.5,
     "fiber_g":3.0,"default_serving_g":150.0,"aliases_he":["צ'יפס בטטות","בטטה מטוגנת"],"aliases_en":["oven baked sweet potato fries","yam fries"],"source":"curated"},
    {"food_id":"food_483","name_he":"זיתי קשקבל","name_en":"Cheese-Stuffed Olives",
     "category":"condiment","calories_kcal":196.0,"protein_g":4.0,"carbs_g":3.5,"fat_g":19.0,
     "default_serving_g":30.0,"aliases_he":["זיתים ממולאים","זיתים עם גבינה"],"aliases_en":["stuffed green olives","pimento olives"],"source":"curated"},
    {"food_id":"food_484","name_he":"חטיף עגבניות מיובשות","name_en":"Sundried Tomato Spread",
     "category":"condiment","calories_kcal":90.0,"protein_g":2.0,"carbs_g":10.0,"fat_g":5.0,
     "fiber_g":2.0,"default_unit":"tablespoon","default_serving_g":20.0,"aliases_he":["ממרח עגבניות מיובשות"],"aliases_en":["sun-dried tomato dip","pesto rosso"],"source":"curated"},
    {"food_id":"food_485","name_he":"כרם עוגיות","name_en":"Crackers with Cheese",
     "category":"other","calories_kcal":450.0,"protein_g":13.0,"carbs_g":52.0,"fat_g":22.0,
     "default_serving_g":40.0,"aliases_he":["קרקר עם גבינה","ביסקוויט עם גבינה"],"aliases_en":["cheese and crackers","water biscuits"],"source":"curated"},
    {"food_id":"food_486","name_he":"אדממה מלוחה","name_en":"Salted Edamame",
     "category":"legume","calories_kcal":122.0,"protein_g":11.0,"carbs_g":9.9,"fat_g":5.2,
     "fiber_g":5.2,"default_serving_g":100.0,"aliases_he":["אדממה מבושל עם מלח"],"aliases_en":["boiled edamame","salty soybeans"],"source":"curated"},
    {"food_id":"food_487","name_he":"חציל מולייה","name_en":"Baba Ganoush",
     "category":"condiment","calories_kcal":130.0,"protein_g":3.0,"carbs_g":8.0,"fat_g":10.0,
     "fiber_g":3.5,"default_unit":"tablespoon","default_serving_g":40.0,"aliases_he":["בבגנוש","ממרח חציל"],"aliases_en":["eggplant dip","smoked eggplant spread"],"source":"curated"},
    {"food_id":"food_488","name_he":"פול ממרח","name_en":"Fava Bean Spread",
     "category":"condiment","calories_kcal":88.0,"protein_g":6.5,"carbs_g":14.0,"fat_g":1.5,
     "fiber_g":5.0,"default_unit":"tablespoon","default_serving_g":40.0,"aliases_he":["ממרח פול","פיפוס"],"aliases_en":["fava dip","ful medames spread"],"source":"curated"},
    {"food_id":"food_489","name_he":"פסטת שקדים","name_en":"Marzipan",
     "category":"other","calories_kcal":458.0,"protein_g":9.0,"carbs_g":58.0,"fat_g":23.0,
     "fiber_g":3.5,"default_serving_g":30.0,"aliases_he":["מרציפן","עוגיית שקדים"],"aliases_en":["almond paste","marzipan confection"],"source":"curated"},
    {"food_id":"food_490","name_he":"אחלה","name_en":"Lahmacun",
     "category":"other","calories_kcal":255.0,"protein_g":10.5,"carbs_g":35.0,"fat_g":8.0,
     "fiber_g":2.0,"default_unit":"unit","default_serving_g":120.0,"aliases_he":["לחמג'ון","פיצה טורקית"],"aliases_en":["turkish pizza","minced meat flatbread"],"source":"curated"},

    # ── BEVERAGES (expanded) ──────────────────────────────────────────────────
    {"food_id":"food_491","name_he":"תה קינמון","name_en":"Cinnamon Tea",
     "category":"beverage","calories_kcal":2.0,"protein_g":0.0,"carbs_g":0.5,"fat_g":0.0,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["תה קינמון","שתייה חמה"],"aliases_en":["chai tea","spiced tea"],"source":"curated"},
    {"food_id":"food_492","name_he":"מטה לטה","name_en":"Matcha Latte",
     "category":"beverage","calories_kcal":60.0,"protein_g":3.0,"carbs_g":8.0,"fat_g":1.5,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["מאצ'ה","תה ירוק מטחון"],"aliases_en":["matcha green tea","ceremonial matcha"],"source":"curated"},
    {"food_id":"food_493","name_he":"שייק שוקולד","name_en":"Chocolate Milkshake",
     "category":"beverage","calories_kcal":166.0,"protein_g":4.0,"carbs_g":26.0,"fat_g":5.5,
     "default_unit":"cup","default_serving_g":300.0,"aliases_he":["מילק שייק שוקולד","שייק שוקולד קרח"],"aliases_en":["chocolate shake","thick shake"],"source":"curated"},
    {"food_id":"food_494","name_he":"מיץ גזר","name_en":"Carrot Juice",
     "category":"beverage","calories_kcal":40.0,"protein_g":0.9,"carbs_g":9.3,"fat_g":0.2,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["מיץ גזרים","מיץ גזר טרי"],"aliases_en":["fresh carrot juice","cold-pressed carrot"],"source":"curated"},
    {"food_id":"food_495","name_he":"תה נענע","name_en":"Mint Tea",
     "category":"beverage","calories_kcal":2.0,"protein_g":0.1,"carbs_g":0.4,"fat_g":0.0,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["תה נענע מרוקאי","נענע"],"aliases_en":["moroccan mint tea","fresh mint tea"],"source":"curated"},
    {"food_id":"food_496","name_he":"מיץ אשכולית","name_en":"Grapefruit Juice",
     "category":"beverage","calories_kcal":39.0,"protein_g":0.5,"carbs_g":9.2,"fat_g":0.1,
     "default_unit":"cup","default_serving_g":240.0,"aliases_he":["מיץ אשכוליות"],"aliases_en":["fresh grapefruit juice","ruby red grapefruit juice"],"source":"curated"},
    {"food_id":"food_497","name_he":"שייק ירוק","name_en":"Green Smoothie",
     "category":"beverage","calories_kcal":50.0,"protein_g":2.0,"carbs_g":10.0,"fat_g":0.5,
     "fiber_g":2.0,"default_unit":"cup","default_serving_g":300.0,"aliases_he":["שייק ירקות","שייק תרד"],"aliases_en":["spinach banana smoothie","detox smoothie"],"source":"curated"},

    # ── ADDITIONAL CONDIMENTS ─────────────────────────────────────────────────
    {"food_id":"food_498","name_he":"רוטב יוגורט","name_en":"Tzatziki",
     "category":"condiment","calories_kcal":96.0,"protein_g":5.0,"carbs_g":4.5,"fat_g":6.5,
     "fiber_g":0.5,"default_unit":"tablespoon","default_serving_g":30.0,"aliases_he":["ג'אג'יק","רוטב מלפפון-יוגורט"],"aliases_en":["cucumber yogurt dip","greek tzatziki"],"source":"curated"},
    {"food_id":"food_499","name_he":"אַיוֹלִי","name_en":"Aioli",
     "category":"condiment","calories_kcal":465.0,"protein_g":1.5,"carbs_g":3.0,"fat_g":50.0,
     "default_unit":"tablespoon","default_serving_g":15.0,"aliases_he":["רוטב שום מיונז"],"aliases_en":["garlic aioli","garlic mayo"],"source":"curated"},
    {"food_id":"food_500","name_he":"חומוס שחור","name_en":"Black Bean Dip",
     "category":"condiment","calories_kcal":132.0,"protein_g":7.0,"carbs_g":19.0,"fat_g":3.5,
     "fiber_g":5.5,"default_unit":"tablespoon","default_serving_g":40.0,"aliases_he":["ממרח שעועית שחורה"],"aliases_en":["black bean spread","refried bean dip"],"source":"curated"},
]
