"""Extended food library — batch 5 (food_651 to food_730)."""
from typing import List, Dict

EXTENDED_FOODS_5: List[Dict] = [
    # === INTERNATIONAL DISHES ===
    {"food_id": "food_651", "name_he": "פד תאי", "name_en": "Pad Thai", "category": "prepared_food", "calories_kcal": 181, "protein_g": 8.5, "carbs_g": 27.0, "fat_g": 4.6, "fiber_g": 1.5, "sugar_g": 4.0, "sodium_mg": 430.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_652", "name_he": "אורז מטוגן תאילנדי", "name_en": "Thai Fried Rice", "category": "prepared_food", "calories_kcal": 163, "protein_g": 5.0, "carbs_g": 26.0, "fat_g": 4.5, "fiber_g": 1.0, "sugar_g": 1.5, "sodium_mg": 490.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_653", "name_he": "קארי תאילנדי ירוק", "name_en": "Thai Green Curry", "category": "prepared_food", "calories_kcal": 148, "protein_g": 8.0, "carbs_g": 9.0, "fat_g": 9.5, "fiber_g": 1.5, "sugar_g": 3.0, "sodium_mg": 520.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_654", "name_he": "ראמן יפני", "name_en": "Japanese Ramen", "category": "prepared_food", "calories_kcal": 140, "protein_g": 7.0, "carbs_g": 20.0, "fat_g": 3.5, "fiber_g": 1.0, "sugar_g": 2.0, "sodium_mg": 890.0, "default_unit": "gram", "default_serving_g": 400.0, "source": "curated"},
    {"food_id": "food_655", "name_he": "סושי ניגירי", "name_en": "Sushi Nigiri", "category": "prepared_food", "calories_kcal": 145, "protein_g": 5.4, "carbs_g": 27.0, "fat_g": 0.5, "fiber_g": 0.5, "sugar_g": 3.0, "sodium_mg": 290.0, "default_unit": "gram", "default_serving_g": 120.0, "source": "curated"},
    {"food_id": "food_656", "name_he": "מאקי סושי", "name_en": "Maki Sushi Roll", "category": "prepared_food", "calories_kcal": 175, "protein_g": 5.4, "carbs_g": 31.0, "fat_g": 2.5, "fiber_g": 1.2, "sugar_g": 4.5, "sodium_mg": 397.0, "default_unit": "gram", "default_serving_g": 120.0, "source": "curated"},
    {"food_id": "food_657", "name_he": "ביביםבאפ קוריאני", "name_en": "Korean Bibimbap", "category": "prepared_food", "calories_kcal": 175, "protein_g": 8.5, "carbs_g": 28.0, "fat_g": 3.5, "fiber_g": 2.0, "sugar_g": 3.0, "sodium_mg": 440.0, "default_unit": "gram", "default_serving_g": 300.0, "source": "curated"},
    {"food_id": "food_658", "name_he": "קים צ'י", "name_en": "Kimchi", "category": "vegetables", "calories_kcal": 15, "protein_g": 1.1, "carbs_g": 2.4, "fat_g": 0.5, "fiber_g": 1.6, "sugar_g": 1.5, "sodium_mg": 498.0, "default_unit": "gram", "default_serving_g": 60.0, "source": "curated"},
    {"food_id": "food_659", "name_he": "פו ויאטנמי", "name_en": "Vietnamese Pho", "category": "prepared_food", "calories_kcal": 54, "protein_g": 5.0, "carbs_g": 7.0, "fat_g": 0.4, "fiber_g": 0.5, "sugar_g": 1.5, "sodium_mg": 455.0, "default_unit": "gram", "default_serving_g": 500.0, "source": "curated"},
    {"food_id": "food_660", "name_he": "טיקה מסאלה הודי", "name_en": "Chicken Tikka Masala", "category": "prepared_food", "calories_kcal": 155, "protein_g": 12.5, "carbs_g": 7.0, "fat_g": 8.5, "fiber_g": 1.5, "sugar_g": 4.0, "sodium_mg": 509.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_661", "name_he": "ביריאני אורז", "name_en": "Chicken Biryani", "category": "prepared_food", "calories_kcal": 185, "protein_g": 9.0, "carbs_g": 25.0, "fat_g": 5.5, "fiber_g": 1.0, "sugar_g": 2.0, "sodium_mg": 390.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_662", "name_he": "קוסקוס מרוקאי", "name_en": "Moroccan Couscous", "category": "prepared_food", "calories_kcal": 178, "protein_g": 5.5, "carbs_g": 30.0, "fat_g": 4.0, "fiber_g": 2.5, "sugar_g": 3.0, "sodium_mg": 340.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_663", "name_he": "פלאפל", "name_en": "Falafel", "category": "prepared_food", "calories_kcal": 333, "protein_g": 13.3, "carbs_g": 31.8, "fat_g": 17.8, "fiber_g": 4.9, "sugar_g": 2.8, "sodium_mg": 294.0, "default_unit": "unit", "default_serving_g": 50.0, "source": "curated"},
    {"food_id": "food_664", "name_he": "שוורמה עוף", "name_en": "Chicken Shawarma", "category": "prepared_food", "calories_kcal": 234, "protein_g": 20.0, "carbs_g": 15.0, "fat_g": 10.0, "fiber_g": 1.5, "sugar_g": 2.0, "sodium_mg": 640.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_665", "name_he": "דונר קבב", "name_en": "Doner Kebab", "category": "prepared_food", "calories_kcal": 225, "protein_g": 15.0, "carbs_g": 16.0, "fat_g": 11.0, "fiber_g": 1.5, "sugar_g": 2.5, "sodium_mg": 690.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_666", "name_he": "פסטה בולונז", "name_en": "Spaghetti Bolognese", "category": "prepared_food", "calories_kcal": 193, "protein_g": 10.0, "carbs_g": 22.0, "fat_g": 7.0, "fiber_g": 2.0, "sugar_g": 3.5, "sodium_mg": 410.0, "default_unit": "gram", "default_serving_g": 300.0, "source": "curated"},
    {"food_id": "food_667", "name_he": "פסטה קרבונרה", "name_en": "Pasta Carbonara", "category": "prepared_food", "calories_kcal": 253, "protein_g": 11.0, "carbs_g": 27.0, "fat_g": 11.0, "fiber_g": 1.5, "sugar_g": 1.0, "sodium_mg": 390.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_668", "name_he": "לזניה", "name_en": "Lasagna", "category": "prepared_food", "calories_kcal": 166, "protein_g": 9.5, "carbs_g": 15.0, "fat_g": 7.0, "fiber_g": 1.5, "sugar_g": 3.5, "sodium_mg": 340.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},

    # === SALADS ===
    {"food_id": "food_669", "name_he": "סלט יווני", "name_en": "Greek Salad", "category": "prepared_food", "calories_kcal": 92, "protein_g": 3.0, "carbs_g": 7.0, "fat_g": 6.5, "fiber_g": 2.0, "sugar_g": 4.5, "sodium_mg": 425.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_670", "name_he": "סלט ניסואז", "name_en": "Nicoise Salad", "category": "prepared_food", "calories_kcal": 118, "protein_g": 9.5, "carbs_g": 6.5, "fat_g": 6.0, "fiber_g": 2.5, "sugar_g": 2.0, "sodium_mg": 380.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_671", "name_he": "סלט קיסר", "name_en": "Caesar Salad", "category": "prepared_food", "calories_kcal": 146, "protein_g": 5.8, "carbs_g": 7.0, "fat_g": 11.0, "fiber_g": 1.5, "sugar_g": 1.5, "sodium_mg": 490.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_672", "name_he": "סלט קפרזה", "name_en": "Caprese Salad", "category": "prepared_food", "calories_kcal": 175, "protein_g": 9.5, "carbs_g": 5.5, "fat_g": 13.0, "fiber_g": 1.0, "sugar_g": 3.5, "sodium_mg": 290.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_673", "name_he": "סלט טבולה", "name_en": "Tabbouleh", "category": "prepared_food", "calories_kcal": 98, "protein_g": 3.0, "carbs_g": 15.0, "fat_g": 3.5, "fiber_g": 3.0, "sugar_g": 2.0, "sodium_mg": 200.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},

    # === MORE PROTEINS & DELI ===
    {"food_id": "food_674", "name_he": "פרושוטו", "name_en": "Prosciutto", "category": "protein", "calories_kcal": 215, "protein_g": 25.9, "carbs_g": 0.0, "fat_g": 12.6, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 2400.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_675", "name_he": "סלאמי", "name_en": "Salami", "category": "protein", "calories_kcal": 407, "protein_g": 21.7, "carbs_g": 1.2, "fat_g": 34.4, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 1890.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_676", "name_he": "חזה עוף מעושן", "name_en": "Smoked Chicken Breast", "category": "protein", "calories_kcal": 149, "protein_g": 23.5, "carbs_g": 0.5, "fat_g": 5.4, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 678.0, "default_unit": "gram", "default_serving_g": 80.0, "source": "curated"},
    {"food_id": "food_677", "name_he": "סלמון מעושן", "name_en": "Smoked Salmon", "category": "protein", "calories_kcal": 117, "protein_g": 18.3, "carbs_g": 0.0, "fat_g": 4.3, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 672.0, "default_unit": "gram", "default_serving_g": 60.0, "source": "curated"},
    {"food_id": "food_678", "name_he": "פסטרמה הודו", "name_en": "Turkey Pastrami", "category": "protein", "calories_kcal": 124, "protein_g": 17.3, "carbs_g": 2.0, "fat_g": 5.5, "fiber_g": 0.0, "sugar_g": 2.0, "sodium_mg": 952.0, "default_unit": "gram", "default_serving_g": 60.0, "source": "curated"},
    {"food_id": "food_679", "name_he": "ספיק בקר", "name_en": "Beef Jerky", "category": "protein", "calories_kcal": 410, "protein_g": 33.2, "carbs_g": 11.0, "fat_g": 25.6, "fiber_g": 0.5, "sugar_g": 6.0, "sodium_mg": 1781.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_680", "name_he": "כופתאות בשר", "name_en": "Meatballs", "category": "protein", "calories_kcal": 221, "protein_g": 16.0, "carbs_g": 7.0, "fat_g": 14.0, "fiber_g": 0.5, "sugar_g": 1.5, "sodium_mg": 430.0, "default_unit": "unit", "default_serving_g": 100.0, "source": "curated"},

    # === MORE PLANT-BASED ===
    {"food_id": "food_681", "name_he": "אפונת בר", "name_en": "Snow Peas", "category": "vegetables", "calories_kcal": 42, "protein_g": 2.8, "carbs_g": 7.6, "fat_g": 0.2, "fiber_g": 2.6, "sugar_g": 4.0, "sodium_mg": 4.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_682", "name_he": "אדממה", "name_en": "Edamame", "category": "legumes", "calories_kcal": 122, "protein_g": 11.9, "carbs_g": 8.9, "fat_g": 5.2, "fiber_g": 5.2, "sugar_g": 2.2, "sodium_mg": 6.0, "default_unit": "gram", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_683", "name_he": "נורי (אצה יבשה)", "name_en": "Nori Seaweed", "category": "vegetables", "calories_kcal": 35, "protein_g": 5.8, "carbs_g": 5.1, "fat_g": 0.3, "fiber_g": 0.3, "sugar_g": 0.5, "sodium_mg": 48.0, "default_unit": "gram", "default_serving_g": 10.0, "source": "curated"},
    {"food_id": "food_684", "name_he": "נבטי שעועית", "name_en": "Bean Sprouts", "category": "vegetables", "calories_kcal": 30, "protein_g": 3.1, "carbs_g": 5.9, "fat_g": 0.2, "fiber_g": 1.8, "sugar_g": 4.1, "sodium_mg": 6.0, "default_unit": "gram", "default_serving_g": 80.0, "source": "curated"},
    {"food_id": "food_685", "name_he": "קייל", "name_en": "Kale", "category": "vegetables", "calories_kcal": 49, "protein_g": 4.3, "carbs_g": 8.8, "fat_g": 0.9, "fiber_g": 3.6, "sugar_g": 2.3, "sodium_mg": 38.0, "default_unit": "gram", "default_serving_g": 80.0, "source": "curated"},
    {"food_id": "food_686", "name_he": "עלי מנגולד", "name_en": "Swiss Chard", "category": "vegetables", "calories_kcal": 19, "protein_g": 1.8, "carbs_g": 3.7, "fat_g": 0.2, "fiber_g": 1.6, "sugar_g": 1.1, "sodium_mg": 213.0, "default_unit": "gram", "default_serving_g": 80.0, "source": "curated"},
    {"food_id": "food_687", "name_he": "רוקולה", "name_en": "Arugula / Rocket", "category": "vegetables", "calories_kcal": 25, "protein_g": 2.6, "carbs_g": 3.7, "fat_g": 0.7, "fiber_g": 1.6, "sugar_g": 2.1, "sodium_mg": 27.0, "default_unit": "gram", "default_serving_g": 40.0, "source": "curated"},
    {"food_id": "food_688", "name_he": "שן שועל", "name_en": "Dandelion Greens", "category": "vegetables", "calories_kcal": 45, "protein_g": 2.7, "carbs_g": 9.2, "fat_g": 0.7, "fiber_g": 3.5, "sugar_g": 0.7, "sodium_mg": 76.0, "default_unit": "gram", "default_serving_g": 80.0, "source": "curated"},

    # === MORE SNACKS ===
    {"food_id": "food_689", "name_he": "פופקורן", "name_en": "Popcorn Air-Popped", "category": "snacks", "calories_kcal": 387, "protein_g": 12.9, "carbs_g": 77.9, "fat_g": 4.5, "fiber_g": 14.5, "sugar_g": 0.9, "sodium_mg": 8.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_690", "name_he": "צ'יפס תפוחי אדמה", "name_en": "Potato Chips", "category": "snacks", "calories_kcal": 547, "protein_g": 6.5, "carbs_g": 52.0, "fat_g": 35.0, "fiber_g": 4.8, "sugar_g": 0.3, "sodium_mg": 503.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_691", "name_he": "נאצ'וס תירס", "name_en": "Tortilla Chips", "category": "snacks", "calories_kcal": 489, "protein_g": 7.4, "carbs_g": 63.0, "fat_g": 23.0, "fiber_g": 5.2, "sugar_g": 1.0, "sodium_mg": 350.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_692", "name_he": "פרצלס", "name_en": "Pretzels", "category": "snacks", "calories_kcal": 380, "protein_g": 9.5, "carbs_g": 79.0, "fat_g": 2.9, "fiber_g": 3.0, "sugar_g": 2.5, "sodium_mg": 1714.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_693", "name_he": "גרייסין", "name_en": "Rice Cakes", "category": "snacks", "calories_kcal": 387, "protein_g": 7.7, "carbs_g": 81.5, "fat_g": 2.8, "fiber_g": 1.0, "sugar_g": 0.4, "sodium_mg": 16.0, "default_unit": "unit", "default_serving_g": 9.0, "source": "curated"},
    {"food_id": "food_694", "name_he": "חטיף אנרגיה", "name_en": "Energy Bar", "category": "snacks", "calories_kcal": 380, "protein_g": 10.0, "carbs_g": 60.0, "fat_g": 9.0, "fiber_g": 3.0, "sugar_g": 25.0, "sodium_mg": 100.0, "default_unit": "unit", "default_serving_g": 60.0, "source": "curated"},
    {"food_id": "food_695", "name_he": "חטיף חלבון", "name_en": "Protein Bar", "category": "snacks", "calories_kcal": 360, "protein_g": 20.0, "carbs_g": 40.0, "fat_g": 11.0, "fiber_g": 4.0, "sugar_g": 15.0, "sodium_mg": 200.0, "default_unit": "unit", "default_serving_g": 60.0, "source": "curated"},

    # === OILS, FATS & DRESSINGS ===
    {"food_id": "food_696", "name_he": "שמן קוקוס", "name_en": "Coconut Oil", "category": "fats", "calories_kcal": 862, "protein_g": 0.0, "carbs_g": 0.0, "fat_g": 100.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 0.0, "default_unit": "gram", "default_serving_g": 10.0, "source": "curated"},
    {"food_id": "food_697", "name_he": "שמן שומשום", "name_en": "Sesame Oil", "category": "fats", "calories_kcal": 884, "protein_g": 0.0, "carbs_g": 0.0, "fat_g": 100.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 0.0, "default_unit": "gram", "default_serving_g": 5.0, "source": "curated"},
    {"food_id": "food_698", "name_he": "שמן אבוקדו", "name_en": "Avocado Oil", "category": "fats", "calories_kcal": 884, "protein_g": 0.0, "carbs_g": 0.0, "fat_g": 100.0, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 0.0, "default_unit": "gram", "default_serving_g": 10.0, "source": "curated"},
    {"food_id": "food_699", "name_he": "רוטב וינגרט", "name_en": "Balsamic Vinaigrette", "category": "condiments", "calories_kcal": 180, "protein_g": 0.3, "carbs_g": 8.5, "fat_g": 16.0, "fiber_g": 0.0, "sugar_g": 6.0, "sodium_mg": 420.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_700", "name_he": "רוטב רנץ'", "name_en": "Ranch Dressing", "category": "condiments", "calories_kcal": 428, "protein_g": 1.6, "carbs_g": 5.6, "fat_g": 44.0, "fiber_g": 0.1, "sugar_g": 2.8, "sodium_mg": 722.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_701", "name_he": "טחינה גולמית", "name_en": "Tahini Raw", "category": "condiments", "calories_kcal": 595, "protein_g": 17.0, "carbs_g": 21.2, "fat_g": 53.8, "fiber_g": 9.3, "sugar_g": 0.5, "sodium_mg": 115.0, "default_unit": "gram", "default_serving_g": 20.0, "source": "curated"},

    # === MORE DAIRY ===
    {"food_id": "food_702", "name_he": "קפיר", "name_en": "Kefir", "category": "dairy", "calories_kcal": 61, "protein_g": 3.4, "carbs_g": 4.5, "fat_g": 3.5, "fiber_g": 0.0, "sugar_g": 4.5, "sodium_mg": 40.0, "default_unit": "gram", "default_serving_g": 250.0, "source": "curated"},
    {"food_id": "food_703", "name_he": "גבינת מוצרלה בופלו", "name_en": "Buffalo Mozzarella", "category": "dairy", "calories_kcal": 257, "protein_g": 18.3, "carbs_g": 2.2, "fat_g": 20.0, "fiber_g": 0.0, "sugar_g": 1.0, "sodium_mg": 466.0, "default_unit": "gram", "default_serving_g": 60.0, "source": "curated"},
    {"food_id": "food_704", "name_he": "גבינת בריה", "name_en": "Brie Cheese", "category": "dairy", "calories_kcal": 334, "protein_g": 20.7, "carbs_g": 0.5, "fat_g": 27.7, "fiber_g": 0.0, "sugar_g": 0.5, "sodium_mg": 629.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_705", "name_he": "גבינת אמנטל", "name_en": "Emmental Cheese", "category": "dairy", "calories_kcal": 380, "protein_g": 28.4, "carbs_g": 1.4, "fat_g": 29.7, "fiber_g": 0.0, "sugar_g": 0.5, "sodium_mg": 450.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_706", "name_he": "יוגורט יווני שמן", "name_en": "Full Fat Greek Yogurt", "category": "dairy", "calories_kcal": 97, "protein_g": 9.0, "carbs_g": 3.6, "fat_g": 5.0, "fiber_g": 0.0, "sugar_g": 3.2, "sodium_mg": 35.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},

    # === SWEETENERS & BAKING ===
    {"food_id": "food_707", "name_he": "דבש", "name_en": "Honey", "category": "sweets", "calories_kcal": 304, "protein_g": 0.3, "carbs_g": 82.4, "fat_g": 0.0, "fiber_g": 0.2, "sugar_g": 82.1, "sodium_mg": 4.0, "default_unit": "gram", "default_serving_g": 15.0, "source": "curated"},
    {"food_id": "food_708", "name_he": "מייפל", "name_en": "Maple Syrup", "category": "sweets", "calories_kcal": 260, "protein_g": 0.0, "carbs_g": 67.1, "fat_g": 0.1, "fiber_g": 0.0, "sugar_g": 60.5, "sodium_mg": 9.0, "default_unit": "gram", "default_serving_g": 20.0, "source": "curated"},
    {"food_id": "food_709", "name_he": "שוקולד מריר", "name_en": "Dark Chocolate 70%", "category": "sweets", "calories_kcal": 598, "protein_g": 7.8, "carbs_g": 45.9, "fat_g": 42.6, "fiber_g": 10.9, "sugar_g": 24.0, "sodium_mg": 20.0, "default_unit": "gram", "default_serving_g": 20.0, "source": "curated"},
    {"food_id": "food_710", "name_he": "שוקולד חלב", "name_en": "Milk Chocolate", "category": "sweets", "calories_kcal": 535, "protein_g": 7.7, "carbs_g": 59.4, "fat_g": 29.7, "fiber_g": 3.4, "sugar_g": 51.5, "sodium_mg": 79.0, "default_unit": "gram", "default_serving_g": 20.0, "source": "curated"},
    {"food_id": "food_711", "name_he": "ריבה", "name_en": "Strawberry Jam", "category": "sweets", "calories_kcal": 278, "protein_g": 0.4, "carbs_g": 69.0, "fat_g": 0.1, "fiber_g": 1.2, "sugar_g": 53.0, "sodium_mg": 32.0, "default_unit": "gram", "default_serving_g": 20.0, "source": "curated"},
    {"food_id": "food_712", "name_he": "ממרח שוקולד אגוזים", "name_en": "Chocolate Hazelnut Spread", "category": "sweets", "calories_kcal": 539, "protein_g": 6.3, "carbs_g": 57.5, "fat_g": 30.9, "fiber_g": 3.4, "sugar_g": 55.9, "sodium_mg": 41.0, "default_unit": "gram", "default_serving_g": 20.0, "source": "curated"},
    {"food_id": "food_713", "name_he": "חמאת בוטנים", "name_en": "Peanut Butter", "category": "nuts", "calories_kcal": 588, "protein_g": 25.1, "carbs_g": 20.1, "fat_g": 50.4, "fiber_g": 6.0, "sugar_g": 9.2, "sodium_mg": 422.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},
    {"food_id": "food_714", "name_he": "חמאת שקדים", "name_en": "Almond Butter", "category": "nuts", "calories_kcal": 614, "protein_g": 21.0, "carbs_g": 18.8, "fat_g": 55.5, "fiber_g": 10.3, "sugar_g": 5.1, "sodium_mg": 7.0, "default_unit": "gram", "default_serving_g": 30.0, "source": "curated"},

    # === PREPARED & FROZEN ===
    {"food_id": "food_715", "name_he": "סושי ספייסי טונה", "name_en": "Spicy Tuna Roll", "category": "prepared_food", "calories_kcal": 290, "protein_g": 13.0, "carbs_g": 38.0, "fat_g": 9.0, "fiber_g": 1.5, "sugar_g": 4.0, "sodium_mg": 710.0, "default_unit": "gram", "default_serving_g": 140.0, "source": "curated"},
    {"food_id": "food_716", "name_he": "דים סאם", "name_en": "Dim Sum Dumplings", "category": "prepared_food", "calories_kcal": 192, "protein_g": 10.0, "carbs_g": 21.0, "fat_g": 7.0, "fiber_g": 1.0, "sugar_g": 2.0, "sodium_mg": 480.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_717", "name_he": "פוקצ'ה", "name_en": "Focaccia Bread", "category": "grains", "calories_kcal": 249, "protein_g": 7.4, "carbs_g": 35.0, "fat_g": 8.0, "fiber_g": 2.1, "sugar_g": 1.5, "sodium_mg": 540.0, "default_unit": "gram", "default_serving_g": 80.0, "source": "curated"},
    {"food_id": "food_718", "name_he": "פיתה", "name_en": "Pita Bread", "category": "grains", "calories_kcal": 275, "protein_g": 9.1, "carbs_g": 55.7, "fat_g": 1.2, "fiber_g": 2.2, "sugar_g": 0.9, "sodium_mg": 536.0, "default_unit": "unit", "default_serving_g": 60.0, "source": "curated"},
    {"food_id": "food_719", "name_he": "נאן לחם", "name_en": "Naan Bread", "category": "grains", "calories_kcal": 317, "protein_g": 9.0, "carbs_g": 55.0, "fat_g": 7.5, "fiber_g": 1.9, "sugar_g": 4.0, "sodium_mg": 526.0, "default_unit": "unit", "default_serving_g": 90.0, "source": "curated"},
    {"food_id": "food_720", "name_he": "לחם שאור", "name_en": "Sourdough Bread", "category": "grains", "calories_kcal": 274, "protein_g": 10.6, "carbs_g": 51.8, "fat_g": 2.0, "fiber_g": 2.4, "sugar_g": 2.0, "sodium_mg": 518.0, "default_unit": "gram", "default_serving_g": 40.0, "source": "curated"},

    # === ADDITIONAL PROTEINS ===
    {"food_id": "food_721", "name_he": "אנשובי", "name_en": "Anchovy Fillets", "category": "protein", "calories_kcal": 131, "protein_g": 20.4, "carbs_g": 0.0, "fat_g": 4.8, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 104.0, "default_unit": "gram", "default_serving_g": 20.0, "source": "curated"},
    {"food_id": "food_722", "name_he": "סרדינים בשמן", "name_en": "Sardines in Oil", "category": "protein", "calories_kcal": 208, "protein_g": 24.6, "carbs_g": 0.0, "fat_g": 11.5, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 505.0, "default_unit": "gram", "default_serving_g": 85.0, "source": "curated"},
    {"food_id": "food_723", "name_he": "קלמרי מטוגן", "name_en": "Fried Calamari", "category": "prepared_food", "calories_kcal": 233, "protein_g": 14.0, "carbs_g": 21.0, "fat_g": 9.0, "fiber_g": 0.5, "sugar_g": 0.5, "sodium_mg": 480.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_724", "name_he": "עוף בטריאקי", "name_en": "Teriyaki Chicken", "category": "prepared_food", "calories_kcal": 185, "protein_g": 20.0, "carbs_g": 12.0, "fat_g": 6.0, "fiber_g": 0.3, "sugar_g": 9.0, "sodium_mg": 680.0, "default_unit": "gram", "default_serving_g": 200.0, "source": "curated"},
    {"food_id": "food_725", "name_he": "שיש קבב טלה", "name_en": "Lamb Shish Kebab", "category": "prepared_food", "calories_kcal": 230, "protein_g": 20.0, "carbs_g": 4.0, "fat_g": 15.0, "fiber_g": 0.5, "sugar_g": 1.5, "sodium_mg": 390.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_726", "name_he": "שניצל עוף", "name_en": "Chicken Schnitzel", "category": "prepared_food", "calories_kcal": 252, "protein_g": 22.0, "carbs_g": 13.0, "fat_g": 11.0, "fiber_g": 0.7, "sugar_g": 0.5, "sodium_mg": 460.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_727", "name_he": "שניצל וול", "name_en": "Veal Schnitzel Wiener", "category": "prepared_food", "calories_kcal": 295, "protein_g": 20.0, "carbs_g": 16.0, "fat_g": 16.0, "fiber_g": 0.5, "sugar_g": 0.5, "sodium_mg": 490.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
    {"food_id": "food_728", "name_he": "סטייק סלמון צלוי", "name_en": "Grilled Salmon Steak", "category": "protein", "calories_kcal": 208, "protein_g": 28.0, "carbs_g": 0.0, "fat_g": 10.2, "fiber_g": 0.0, "sugar_g": 0.0, "sodium_mg": 59.0, "default_unit": "gram", "default_serving_g": 180.0, "source": "curated"},
    {"food_id": "food_729", "name_he": "קציצות עדשים", "name_en": "Lentil Patties", "category": "prepared_food", "calories_kcal": 217, "protein_g": 13.5, "carbs_g": 28.0, "fat_g": 5.5, "fiber_g": 7.5, "sugar_g": 2.0, "sodium_mg": 340.0, "default_unit": "unit", "default_serving_g": 100.0, "source": "curated"},
    {"food_id": "food_730", "name_he": "קינואה שחורה", "name_en": "Black Quinoa Cooked", "category": "grains", "calories_kcal": 120, "protein_g": 4.4, "carbs_g": 22.0, "fat_g": 1.9, "fiber_g": 2.8, "sugar_g": 0.9, "sodium_mg": 5.0, "default_unit": "gram", "default_serving_g": 150.0, "source": "curated"},
]
